src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Disclosed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_custom__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <encrypted>true</encrypted>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Restricted</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>A Restricted Case Record means that support team users have a very limited view of this individual’s case. They will only be able to see: Individual name, Individual Case ID, Navigator, Case Status and the Case Record Type.</description>
        <label>Restricted</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Document__c.object
<CustomObject>
    <customHelpPage>Help_Case_Document_VF</customHelpPage>
    <description>Some are restricted, some are collaborative: this object represents all the shared documents on an individual file (assessments, consents ... )</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encrypted>true</encrypted>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Case_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Consent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correspondence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health / Safety Reports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Protocol / Safeguard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFSN - Template</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFSN - Picture Template</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education - IEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service / Support Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Plans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crisis / Contingency Plans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diagnosis Proof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive Behavioural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Psychological / Psychiatric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Document</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Case Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Documents</pluralLabel>
    <recordTypes>
        <fullName>Restricted</fullName>
        <active>true</active>
        <description>Restricted Case Documents will only be shared with the Navigator and the user who added the document. Any documents containing sensitive information should be uploaded as Restricted.</description>
        <label>Restricted</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>Details of the Individual referred in the STADD Program</description>
    <fields>
        <fullName>Individual_Date_of_Birth__c</fullName>
        <description>The birth date of the individual being referred to the program</description>
        <inlineHelpText>Choose in order: day/month/year to complete; any other order will not be accepted by the system</inlineHelpText>
        <label>Individual Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Individual_First_Name__c</fullName>
        <description>The first name of the individual being referred to the STADD program</description>
        <encrypted>true</encrypted>
        <label>Individual First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Individual_Home_Phone_Number__c</fullName>
        <description>The Referral should capture multiple phone numbers for the individual.  This type will capture the type of phone number</description>
        <encrypted>true</encrypted>
        <inlineHelpText>You need to enter at least one phone number</inlineHelpText>
        <label>Individual Home Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Individual_Last_Name__c</fullName>
        <description>The last name of the individual being referred to the STADD program</description>
        <encrypted>true</encrypted>
        <label>Individual Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Address_City__c</fullName>
        <encrypted>true</encrypted>
        <label>Physical Address City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Address_Line_1__c</fullName>
        <description>The address of the physical location where the individual is living</description>
        <encrypted>true</encrypted>
        <label>Physical Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Address_Postal_Code__c</fullName>
        <encrypted>true</encrypted>
        <label>Physical Address Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Case Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Referral Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CaseDocEditContoller_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CaseDocEditContoller_Test {

    static testMethod void myUnitTest() {
       
        Account perAcc = new Account();
        perAcc.LastName ='FN Test';
        perAcc.firstName ='LN Test';
        perAcc.Type_custom__c = 'Private Contact';      
        perAcc.PersonBirthdate = system.today();
        perAcc.Gender__c = 'Male';
        perAcc.Work_Phone__c = '9999999999';
        List<RecordType> accrectype =[Select Id,Name From RecordType Where Name = 'Individual' and SobjectType ='Account' limit 1];// changed recordtype for defect 320
        perAcc.RecordTypeId = accrectype.get(0).id;
        insert perAcc;
        
        Case cas = new case();
        cas.Status = 'New';
        cas.AccountId = perAcc.id;
                
        insert cas;
 
        Referral__c ref = new Referral__c();           
        ref.Status__c = 'Case Created';
        ref.Individual_First_Name__c ='Individual';
        ref.Individual_Last_Name__c ='User';
        ref.Individual_Date_of_Birth__c = system.today();
        ref.Individual_Home_Phone_Number__c = '1231231';
        ref.Physical_Address_City__c='City';
        ref.Physical_Address_Line_1__c ='12th street';
        ref.Physical_Address_Postal_Code__c='22222';
        insert ref;
        
        Case_Document__c casdocument = new Case_Document__c();
        casdocument.Sub_Category__c = 'Legal';
        casdocument.Category__c = 'Individual';
        casdocument.Description__c = 'test';
        casdocument.Name = 'test';
       
        List<RecordType> rectype =[Select Id,Name From RecordType Where Name = 'Restricted' and SobjectType ='Case_Document__c' limit 1];// changed recordtype for defect 320
        string recordtype= rectype.get(0).id;
        
        casdocument.RecordTypeId = recordtype;
        insert casdocument;
        
        Attachment att = new Attachment();
        att.ParentId = casdocument.id;
        att.Name = 'test doc';
        att.body = blob.valueOf('test body');
         
        insert att;
        
        test.starttest();
        
        pagereference pageref = Page.CreateCaseDocAttachPage_Edit; 
        test.setCurrentPageReference(pageref);
        ApexPages.currentPage().getParameters().put('id',casdocument.id); 
        ApexPages.currentPage().getParameters().put('RecordType',recordtype);
        ApexPages.currentPage().getParameters().put('retURL',cas.id);
        //string lkid= ApexPages.currentPage().getParameters().get(System.Label.Case_Lkid);
        //ApexPages.currentPage().getParameters().put(System.Label.Case_Lkid, lkid);
        
        Apexpages.standardcontroller sc = new Apexpages.standardcontroller(casdocument); 
        CaseDocEditContoller obj = new CaseDocEditContoller (sc);   
        //CreateCaseDocAttachController obj = new CreateCaseDocAttachController (sc);
        //obj.Submit();
        system.assertNotEquals(casdocument.id, null);
        test.stoptest();
        
        
    }
    
    static testMethod void GoalTasktest() {
       
        Account perAcc = new Account();
        perAcc.LastName ='FN Test';
        perAcc.firstName ='LN Test';
        perAcc.Type_custom__c = 'Private Contact';      
        perAcc.PersonBirthdate = system.today();
        perAcc.Gender__c = 'Male';
        perAcc.Work_Phone__c = '9999999999';
        List<RecordType> accrectype =[Select Id,Name From RecordType Where Name = 'Individual' and SobjectType ='Account' limit 1];// changed recordtype for defect 320
        perAcc.RecordTypeId = accrectype.get(0).id;
        insert perAcc;
        
        Case cas = new case();
        cas.Status = 'New';
        cas.AccountId = perAcc.id;
                
        insert cas;
 
        Referral__c ref = new Referral__c();           
        ref.Status__c = 'Case Created';
        ref.Individual_First_Name__c ='Individual';
        ref.Individual_Last_Name__c ='User';
        ref.Individual_Date_of_Birth__c = system.today();
        ref.Individual_Home_Phone_Number__c = '1231231';
        ref.Physical_Address_City__c='City';
        ref.Physical_Address_Line_1__c ='12th street';
        ref.Physical_Address_Postal_Code__c='22222';
        insert ref;
        
        Case_Document__c casdocument = new Case_Document__c();
        casdocument.Sub_Category__c = 'Legal';
        casdocument.Category__c = 'Individual';
        casdocument.Description__c = 'test';
        casdocument.Name = 'test';
       
        List<RecordType> rectype =[Select Id,Name From RecordType Where Name = 'Restricted' and SobjectType ='Case_Document__c' limit 1];// changed recordtype for defect 320
        string recordtype= rectype.get(0).id;
        
        casdocument.RecordTypeId = recordtype;
        insert casdocument;
        
        Attachment att = new Attachment();
        att.ParentId = casdocument.id;
        att.Name = 'test doc';
        att.body = blob.valueOf('test body');
         
        insert att;
        
        test.starttest();
        
        pagereference pageref = Page.CreateCaseDocAttachPage; 
        test.setCurrentPageReference(pageref);
        ApexPages.currentPage().getParameters().put('id',casdocument.id); 
        ApexPages.currentPage().getParameters().put('RecordType',recordtype);
        ApexPages.currentPage().getParameters().put('retURL','/stadd/apex/GoalTaskHomepage');
        //ApexPages.currentPage().getParameters().put(System.Label.Case_Lkid, 'CF00Nf0000000Pwl5_lkid');
        
        Apexpages.standardcontroller sc = new Apexpages.standardcontroller(casdocument);    
        //CreateCaseDocAttachController obj = new CreateCaseDocAttachController (sc);
        //obj.Submit();
        system.assertNotEquals(casdocument.id, null);
        test.stoptest();
    }
    
    static testMethod void GoalTasktestNew() {
       
        Account perAcc = new Account();
        perAcc.LastName ='FN Test';
        perAcc.firstName ='LN Test';
        perAcc.Type_custom__c = 'Private Contact';      
        perAcc.PersonBirthdate = system.today();
        perAcc.Gender__c = 'Male';
        perAcc.Work_Phone__c = '9999999999';
        List<RecordType> accrectype =[Select Id,Name From RecordType Where Name = 'Individual' and SobjectType ='Account' limit 1];// changed recordtype for defect 320
        perAcc.RecordTypeId = accrectype.get(0).id;
        insert perAcc;
        
        Case cas = new case();
        cas.Status = 'New';
        cas.AccountId = perAcc.id;
                
        insert cas;
 
        Referral__c ref = new Referral__c();           
        ref.Status__c = 'Case Created';
        ref.Individual_First_Name__c ='Individual';
        ref.Individual_Last_Name__c ='User';
        ref.Individual_Date_of_Birth__c = system.today();
        ref.Individual_Home_Phone_Number__c = '1231231';
        ref.Physical_Address_City__c='City';
        ref.Physical_Address_Line_1__c ='12th street';
        ref.Physical_Address_Postal_Code__c='22222';
        insert ref;
        
        Case_Document__c casdocument = new Case_Document__c();
        casdocument.Sub_Category__c = 'Legal';
        casdocument.Category__c = 'Individual';
        casdocument.Description__c = 'test';
        casdocument.Name = 'test';
       
        List<RecordType> rectype =[Select Id,Name From RecordType Where Name = 'Restricted' and SobjectType ='Case_Document__c' limit 1];// changed recordtype for defect 320
        string recordtype= rectype.get(0).id;
        
        casdocument.RecordTypeId = recordtype;
        insert casdocument;
        
        Attachment att = new Attachment();
        att.ParentId = casdocument.id;
        att.Name = 'test doc';
        att.body = blob.valueOf('test body');
         
        insert att;
        
        test.starttest();
        
        pagereference pageref = Page.CreateCaseDocAttachPage; 
        test.setCurrentPageReference(pageref);
        ApexPages.currentPage().getParameters().put('id',casdocument.id); 
        ApexPages.currentPage().getParameters().put('RecordType',recordtype);
        ApexPages.currentPage().getParameters().put('retURL','/stadd/apex/GoalTaskHomepage');
        //ApexPages.currentPage().getParameters().put(System.Label.Case_Lkid, 'CF00Nf0000000Pwl5_lkid');
        
        Apexpages.standardcontroller sc = new Apexpages.standardcontroller(casdocument);    
        //CreateCaseDocAttachController obj = new CreateCaseDocAttachController (sc);
        //obj.Submit();
        system.assertNotEquals(casdocument.id, null);
        test.stoptest();
    }
    
}