src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Cell_Phone__c</fullName>
        <encrypted>true</encrypted>
        <label>Cell Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Disclosed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_same_as_Physical_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Mailing Address same as Physical Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <encrypted>true</encrypted>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Cell_Phone__c</fullName>
        <formula>Account.Cell_Phone__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cell Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eligibility_Type__c</fullName>
        <label>Eligibility Type</label>
        <picklist>
            <picklistValues>
                <fullName>DD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSI FASD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PSI ASD/PDD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Contact__c.object
<CustomObject>
    <description>Contact details of the  Individual referred in STADD Program.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Referral_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Case Contacts</relationshipLabel>
        <relationshipName>Referral_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Relationship_Subtype__c</fullName>
        <label>Relationship to Individual</label>
        <picklist>
            <picklistValues>
                <fullName>Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nurse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self-Advocate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Therapist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLBC (Community Living BC) Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAA (Delegated Aboriginal Agency)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CFD (Children and Family Development)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Contact</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Case Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Document__c.object
<CustomObject>
    <customHelpPage>Help_Case_Document_VF</customHelpPage>
    <description>Some are restricted, some are collaborative: this object represents all the shared documents on an individual file (assessments, consents ... )</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Documents</relationshipLabel>
        <relationshipName>Case_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Case_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Consent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correspondence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health / Safety Reports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Protocol / Safeguard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFSN - Template</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFSN - Picture Template</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education - IEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service / Support Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Plans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crisis / Contingency Plans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diagnosis Proof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive Behavioural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Psychological / Psychiatric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Document</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Case Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>Details of the Individual referred in the STADD Program</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>filled out by the system (blank until a case is created)</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Eligibility_Type__c</fullName>
        <label>Eligibility Type</label>
        <picklist>
            <picklistValues>
                <fullName>DD</fullName>
                <color>#FFCC66</color>
            </picklistValues>
            <picklistValues>
                <fullName>PSI FASD</fullName>
                <color>#78C953</color>
            </picklistValues>
            <picklistValues>
                <fullName>PSI ASD/PDD</fullName>
                <color>#CC0000</color>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Individual_Date_of_Birth__c</fullName>
        <description>The birth date of the individual being referred to the program</description>
        <inlineHelpText>Choose in order: day/month/year to complete; any other order will not be accepted by the system</inlineHelpText>
        <label>Individual Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Individual_First_Name__c</fullName>
        <description>The first name of the individual being referred to the STADD program</description>
        <encrypted>true</encrypted>
        <label>Individual First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Individual_Home_Phone_Number__c</fullName>
        <description>The Referral should capture multiple phone numbers for the individual.  This type will capture the type of phone number</description>
        <encrypted>true</encrypted>
        <inlineHelpText>You need to enter at least one phone number</inlineHelpText>
        <label>Individual Home Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Individual_Last_Name__c</fullName>
        <description>The last name of the individual being referred to the STADD program</description>
        <encrypted>true</encrypted>
        <label>Individual Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_same_as_Physical_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>if not checked, need to enter the mailing address</inlineHelpText>
        <label>Mailing Address same as Physical Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Physical_Address_City__c</fullName>
        <encrypted>true</encrypted>
        <label>Physical Address City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Address_Line_1__c</fullName>
        <description>The address of the physical location where the individual is living</description>
        <encrypted>true</encrypted>
        <label>Physical Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Address_Postal_Code__c</fullName>
        <encrypted>true</encrypted>
        <label>Physical Address Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Case Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Referral Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CaseNote_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CaseNote_Test {
	static case cas;
    static Referral__c ref;
    static Case_Contact__c refCon;
    static Apexpages.standardcontroller sc;
    static AcceptCaseController obj;

    static testMethod void myUnitTest() {
        
		Profile p = [SELECT Id FROM Profile WHERE Name='STADD Navigator']; 
        User Usr = new User(Alias = 'standt', Email='standarduser@gov.bc.ca', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', ProfileId = p.Id, 
        TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@gov.bc.ca'); 
        insert Usr;
                    
        Account perAcc = new Account();

		perAcc.LastName ='Test';
        
        //acc.Case__pc = cas.id;
        perAcc.PersonBirthdate = system.today();
        perAcc.Gender__c = 'Male';
        perAcc.Work_Phone__c = '9999999999';
        perAcc.Contact_Middle_Name__pc = 'Test';
        perAcc.FirstName = 'tester';
        perAcc.PersonOtherStreet = '123';
        List<RecordType> rectype =[Select Id,Name From RecordType Where Name = 'Individual' and SobjectType ='Account' limit 1];// changed recordtype for defect 320
        perAcc.RecordTypeId = rectype.get(0).id;
        perAcc.PersonOtherCity = 'City';
        perAcc.PersonOtherPostalCode = 'A1A1A1';
        perAcc.PersonOtherState = 'CA';
        perAcc.Mailing_Address_same_as_Physical_Address__c = true;
        perAcc.Primary_Contact_Indicator__pc = true; // GV D-00134
        perAcc.PersonHomePhone ='8888888888';
        perAcc.PersonEmail = 're@re.com';
        perAcc.PersonMailingStreet= '323';
        perAcc.PersonMailingCity ='city';
        perAcc.PersonMailingState= 'cs';
        perAcc.PersonMailingPostalCode='B2B2B2';
        perAcc.Work_Phone__c='7777777777';
        perAcc.Cell_Phone__c='6666666666';
        perAcc.Individual_Preferred_Name__pc = 'tete'; 
        insert perAcc;   
        
        ref = new Referral__c();   
        ref.OwnerId = Usr.id;  
        ref.Status__c = 'Case Created';
        ref.Individual_First_Name__c ='Test';
        ref.Individual_Last_Name__c ='User';
        ref.Individual_Date_of_Birth__c = system.today();
        ref.Individual_Home_Phone_Number__c = '1231231';
        ref.Physical_Address_City__c='City';
        ref.Physical_Address_Line_1__c ='12th street';
        ref.Physical_Address_Postal_Code__c='22222';
        ref.Eligibility_Type__c = 'DD';
        insert ref;
        
        refCon = new Case_Contact__c();
        refCon.Referral__c = ref.id;
        refCon.Relationship_Subtype__c = 'test';
        insert refCon;

		cas = new case ();       
        cas.status = 'New';
        cas.AccountId = perAcc.Id;
        cas.Origin = 'Phone';
        cas.OwnerId =  Usr.Id;            
        insert cas;
        
        Case_Document__c casdoc1 = new Case_Document__c();
        casdoc1.Referral__c =ref.id;
        //casdoc1.Case__c = cas.id;
        casdoc1.Category__c = 'Individual';
        casdoc1.Sub_Category__c = 'Consent';
        insert casdoc1;



    }
}