src/objects/Action_Item__c.object
<CustomObject>
    <customHelpPage>Help_Action_Item_VF</customHelpPage>
    <fields>
        <fullName>Activity__c</fullName>
        <encrypted>true</encrypted>
        <label>Action Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Plan Milestone</label>
        <referenceTo>Plan_Milestone__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Goal</label>
        <referenceTo>Plan_Goal__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <formula>TEXT(Plan__r.Plan_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Plan Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Review_Date__c</fullName>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dependency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Item</label>
    <nameField>
        <displayFormat>AI-{00000}</displayFormat>
        <label>Action Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <customHelpPage>Help_Milestone_VF</customHelpPage>
    <description>BME - Milestones will be used to track the Key Events during the lifecycle of a Project/Release. This object is an important component for status reports and Milestones will be always related to a Release</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Select the current status of this Milestone</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Off Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>A plan developed by the individual to meet certain goals.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Status__c</fullName>
        <label>Plan Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Place/ Signed-off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Support Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contingency Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crisis Plan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Goal__c.object
<CustomObject>
    <customHelpPage>Help_PlanGoals</customHelpPage>
    <description>Goals comprise the plan.</description>
    <fields>
        <fullName>Area_of_Importance__c</fullName>
        <inlineHelpText>The developmental area as described in the functional domain summaries</inlineHelpText>
        <label>Area of Importance</label>
        <picklist>
            <picklistValues>
                <fullName>Personal Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self-Determination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inter-Personal Relations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Inclusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rights</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emotional Well-Being</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Well-Being</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Material Well-Being</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Important_steps_to_reach_this_goal__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>List the most important steps that the individual, family, support network and support team must do for the individual to achieve this goal.</inlineHelpText>
        <label>Important steps to reach this goal</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <description>Plan</description>
        <inlineHelpText>Plan</inlineHelpText>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Plan Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan Goal</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Goal Name (If Goal Type is &apos;Other&apos;)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Milestone__c.object
<CustomObject>
    <customHelpPage>Help_Milestone_VF</customHelpPage>
    <fields>
        <fullName>Plan_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Goal</description>
        <inlineHelpText>Goal</inlineHelpText>
        <label>Plan Goal</label>
        <referenceTo>Plan_Goal__c</referenceTo>
        <relationshipLabel>Plan Milestones</relationshipLabel>
        <relationshipName>Plan_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Plan Milestones</relationshipLabel>
        <relationshipName>Plan_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan Milestone</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PrintPlanController_Test.cls
@isTest
public with sharing class PrintPlanController_Test {
    private static case cas;
    private static Plan__c Pln;
    private static Plan_Goal__c goal;
    private static Plan_Milestone__c Milestone;
    private static Action_Item__c ActionItem ;
    private static Plan_Goal__c goal1;
    private static Plan_Milestone__c Milestone1;
    private static Action_Item__c ActionItem1 ;
    private static Action_Item__c ActionItem2 ;
    
    private static testmethod void testData(){
        cas = new case ();
        cas.status = 'New';
        cas.Origin = 'Phone';
        insert cas;
        Pln = new Plan__c(Name = 'ABC', Plan_Type__c = 'Support Plan', Plan_Status__c = 'Completed', Case__c = cas.Id);
        insert pln;
        goal = new Plan_Goal__c(Name = 'ABC', Area_of_Importance__c = 'Rights', Status__c = 'Completed', Important_steps_to_reach_this_goal__c = 'ACB', Plan__c = pln.id);
        insert goal;
        goal1 = new Plan_Goal__c(Name = 'AsaBC', Area_of_Importance__c = 'Rights', Status__c = 'Completed', Important_steps_to_reach_this_goal__c = 'ACB', Plan__c = pln.id);
        insert goal1;
        Milestone = new Plan_Milestone__c(Name = 'ABC', Status__c = 'Completed', Plan_Goal__c = goal.id, Plan__c = Pln.id );
        insert Milestone;
        Milestone1 = new Plan_Milestone__c(Name = 'ABxSC', Status__c = 'Completed', Plan_Goal__c = goal.id, Plan__c = Pln.id );
        insert Milestone1;
        ActionItem= new Action_Item__c(Activity__c = 'Abcq', Status__c = 'Complete', Review_Date__c = system.Today(), Milestone__c = Milestone.id);
        insert ActionItem;
        ActionItem1= new Action_Item__c(Activity__c = 'Abadscq', Status__c = 'Complete', Review_Date__c = system.Today(), Milestone__c = Milestone.id);
        insert ActionItem1;
        ActionItem2= new Action_Item__c(Activity__c = 'Abadsews', Status__c = 'Complete', Review_Date__c = system.Today(), Milestone__c = Milestone.id);
        insert ActionItem2;
        //milestone
    }    
    private static testmethod void constructorExceptionTest(){
        test.starttest();
        testData();
        ApexPages.currentPage().getParameters().put('id',pln.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(pln);
        PrintPlanController obj = new PrintPlanController(sc);
        //system.assertEquals(obj.GoalLst1.size(), 1);
        test.stoptest();
        
    }
   /*private static testmethod void constructorInsertionTest(){       
        
        test.starttest();
        testData();
        ApexPages.currentPage().getParameters().put('id', cas.id);
        ApexPages.StandardController sc = new ApexPages.StandardController(pln);
        PrintPlanController obj1 = new PrintPlanController(sc);
        test.stoptest();
        system.assertEquals(obj1.GoalLst1.size(), 1);
    }*/
       
}