src/objects/Action_Item__c.object
<CustomObject>
    <customHelpPage>Help_Action_Item_VF</customHelpPage>
    <fields>
        <fullName>Action_Item_Type__c</fullName>
        <label>Action Item Type</label>
        <picklist>
            <picklistValues>
                <fullName>Alert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Protocol</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Activity__c</fullName>
        <encrypted>true</encrypted>
        <label>Action Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_ID__c</fullName>
        <formula>Milestone__r.Plan_Goal__r.Plan__r.Case__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Plan Milestone</label>
        <referenceTo>Plan_Milestone__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Goal</label>
        <referenceTo>Plan_Goal__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <formula>TEXT(Plan__r.Plan_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Plan Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dependency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Item</label>
    <nameField>
        <displayFormat>AI-{00000}</displayFormat>
        <label>Action Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_id__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case_id</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <customHelpPage>Help_Milestone_VF</customHelpPage>
    <description>BME - Milestones will be used to track the Key Events during the lifecycle of a Project/Release. This object is an important component for status reports and Milestones will be always related to a Release</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Select the current status of this Milestone</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Off Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>A plan developed by the individual to meet certain goals.</description>
    <fields>
        <fullName>Assisted_Individual__c</fullName>
        <formula>Case__r.Referral__r.Individual_First_Name__c &amp; &quot; &quot; &amp;  Case__r.Referral__r.Individual_Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assisted Individual</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Owner__c</fullName>
        <description>Case Owner</description>
        <formula>Case__r.Owner:User.FirstName &amp; &quot; &quot; &amp;  Case__r.Owner:User.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <formula>TEXT( DAY( Case__r.Contact.Birthdate )) &amp; &quot;/&quot; &amp; TEXT( MONTH(Case__r.Contact.Birthdate))  &amp; &quot;/&quot; &amp; TEXT(YEAR(Case__r.Contact.Birthdate))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date of Birth</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Meeting_Date__c</fullName>
        <label>First Meeting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_meeting__c</fullName>
        <formula>TEXT(DAY( First_Meeting_Date__c )) &amp; &quot;/&quot; &amp; Text(MONTH( First_Meeting_Date__c )) &amp; &quot;/&quot; &amp;  TEXT(YEAR( First_Meeting_Date__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>First meeting</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Status__c</fullName>
        <label>Plan Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Place/ Signed-off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Support Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contingency Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crisis Plan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Goal__c.object
<CustomObject>
    <customHelpPage>Help_PlanGoals</customHelpPage>
    <description>Goals comprise the plan.</description>
    <fields>
        <fullName>Area_of_Importance__c</fullName>
        <inlineHelpText>The developmental area as described in the functional domain summaries</inlineHelpText>
        <label>Area of Importance</label>
        <picklist>
            <picklistValues>
                <fullName>Personal Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self-Determination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inter-Personal Relations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Inclusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rights</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Emotional Well-Being</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Well-Being</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Material Well-Being</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case_ID__c</fullName>
        <formula>Plan__r.Case__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Goal__c</fullName>
        <label>Goal</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Important_steps_to_reach_this_goal__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>List the most important steps that the individual, family, support network and support team must do for the individual to achieve this goal.</inlineHelpText>
        <label>Important steps to reach this goal</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Important_to_me_because__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Why this goal is important to the individual and how the goal will improve the individual&apos;s quality of life.</inlineHelpText>
        <label>Important to me because</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <description>Plan</description>
        <inlineHelpText>Plan</inlineHelpText>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Plan Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan Goal</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Goal Name (If Goal Type is &apos;Other&apos;)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Milestone__c.object
<CustomObject>
    <customHelpPage>Help_Milestone_VF</customHelpPage>
    <fields>
        <fullName>Case_ID__c</fullName>
        <formula>Plan_Goal__r.Plan__r.Case__r.Id</formula>
        <label>Case ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Goal</description>
        <inlineHelpText>Goal</inlineHelpText>
        <label>Plan Goal</label>
        <referenceTo>Plan_Goal__c</referenceTo>
        <relationshipLabel>Plan Milestones</relationshipLabel>
        <relationshipName>Plan_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Plan Milestones</relationshipLabel>
        <relationshipName>Plan_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan Milestone</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PrintPlanController.cls
/******************************************************************************************
** ICM STADD Project
******************************************************************************************* 
 * @Class Name   : PlanReportPDF
 * @Description  : PDF Report controller Class
 * @Created By   : Gaurav Verma
 * @Created On   : 16 Oct 2013
 * @Modification Log:  
 * -----------------------------------------------------------------------------
 * @Developer                Date                  Description 
 * -----------------------------------------------------------------------------
 * @Gaurav Verma          16 Oct 2013               Created
 * 
 * -----------------------------------------------------------------------------
 */
public with sharing class PrintPlanController {
        public id pnid {get;set;}
        Public Plan__c record {get; set;}
        Public Case CS {get; set;}
        Public List<Plan__c> Plan1 {get; set;}
        public List<Plan_Goal__c> GoalLst1 {get;set;}
        public Plan__c Plan2 {get;set;}
        public List<Plan_Milestone__c> current {set; get;}
    public Map<id,List<Plan_Milestone__c>> mapMsUpdate {get;set;}
    public Map<Id, List<Action_Item__c>> mapMsAi {get;set;}
    public Set<id> setMsid {get;set;}
        // Constructor
        public PrintPlanController(ApexPages.StandardController controller)
        {
                record = (Plan__c)controller.getRecord();//Current Plan Record
                //Plan1 = [Select id, name, Plan_Type__c, Plan_Status__c, First_Meeting_Date__c from Plan__c where id =:record.id limit =1 ]
                Plan2 = [SELECT id, name, Plan_Type__c, Plan_Status__c, Assisted_Individual__c, Case_Owner__c, Date_of_Birth__c,First_meeting__c, First_Meeting_Date__c from Plan__c WHERE id =:record.id];
                //CS = [SELECT id, name from case WHERE id =: Plan2.Case__c];
                //PlanReclist = new list<Plan__c>();//Initializing the list   
        pnid=  ApexPages.currentPage().getParameters().get('id');
        System.debug('####%%%%gvgv%%%%>>>>>' + pnid);
        GoalLst1 = [select id,
                                                Name,
                                                Area_of_Importance__c,
                                                Case_ID__c,
                                                Goal__c,
                                                Plan__c,
                                                Important_steps_to_reach_this_goal__c,
                                                Important_to_me_because__c,
                                                (Select Id, Name From Plan_Milestones__r)
                                 from plan_goal__c where Plan__c =: pnid];
    System.debug('####%%%%gvgv%%%%>>>>>' + GoalLst1.size());
    setMsid = new Set<id>();
    mapMsUpdate = new Map<id,List<Plan_Milestone__c>>();
    mapMsAi = new Map<Id, List<Action_Item__c>>();
    if(GoalLst1.size()>0) 
        {
            mapMsUpdate = new    Map<id,List<Plan_Milestone__c>>(); 
            for(Plan_Goal__c G: GoalLst1)
            {
                list <Plan_Milestone__c> current = new list <Plan_Milestone__c>();
                current = G.Plan_Milestones__r;
                mapMsUpdate.put (G.id,current) ;
                 
                //setMsid.add(current.id);
                for(Plan_Milestone__c MS : current)
                {
                        //if (MS.id != Null)
                        setMsid.add(MS.id);
                }
            }
        }
        else 
        {
            ApexPages.addMessage ( new ApexPages.Message(ApexPages.Severity.ERROR, 'Please Contact the Sysytem Admin'));
            //Return Null;
        } 
        
        //Map<Id, List<Action_Item__c>> mapMsAi = new Map<Id,List<Action_Item__c>>();
        for(Action_Item__c obj : [Select Id,
                                                                        Milestone__c,
                                                                        Action_Item_Type__c,
                                                                        Activity__c,
                                                                        Assigned_To__c,Assigned_To__r.Name,
                                                                        Bring_Forward__c,
                                                                        Bring_Forward_Date__c,
                                                                        Date_Completed__c,
                                                                        Description__c,
                                                                        Plan__c,
                                                                        Plan_Goal__c,
                                                                        Priority__c,
                                                                        Review_Date__c,
                                                                        Status__c
                                                                        From Action_Item__c Where Milestone__c In :setMsid])
        {
                /*List<Id> test = mapMsAi.get(obj.Milestone__c);
                if(test == null)
                {
                        test = new List<Id>();
                }
                test.add(obj.Id);
                mapMsAi.put(obj.Milestone__c,test);*/           
                
                if(mapMsAi.containskey(obj.Milestone__c))
                {
                        List<Action_Item__c> lstAction = mapMsAi.get(obj.Milestone__c);
                        lstAction.add(Obj);
                        mapMsAi.put(obj.Milestone__c,lstAction);
                        //mapMsAi.get(obj.Milestone__c).add(obj);
                }
                else
                {
                        List<Action_Item__c> lstAction = new List<Action_Item__c>(); 
                        lstAction.add(Obj);
                        mapMsAi.put(obj.Milestone__c,lstAction);
                }
                
                
        }
        for(Id PM: setMsid)
        {
                if(!mapMsAi.containskey(PM))
                {
                        List<Action_Item__c> lstAction = new List<Action_Item__c>();                        
                        mapMsAi.put(PM,lstAction);
                }
        }
    }
}