src/objects/Action_Item__c.object
<CustomObject>
    <customHelpPage>Help_Action_Item_VF</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Action Item</label>
    <nameField>
        <displayFormat>AI-{00000}</displayFormat>
        <label>Action Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Assessment_List__c.object
<CustomObject>
    <customHelpPage>Help_Assessment_List_Item_VF</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>List of Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Assessment List Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assessment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Individual_Preferred_Name__c</fullName>
        <formula>Contact.Individual_Preferred_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Individual Preferred Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Northern Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraser Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vancouver Island Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vancouver Coastal Region</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Restricted</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>A Restricted Case Record means that support team users have a very limited view of this individual’s case. They will only be able to see: Individual name, Individual Case ID, Navigator, Case Status and the Case Record Type.</description>
        <label>Restricted</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Alert__c.object
<CustomObject>
    <customHelpPage>Help_CaseAlert</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Alerts</relationshipLabel>
        <relationshipName>Case_Alerts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Alert</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Alerts</pluralLabel>
    <recordTypes>
        <fullName>Restricted</fullName>
        <active>true</active>
        <description>Restricted Case Alerts will only be shared with the Navigator and the user who added the case alert.</description>
        <label>Restricted</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Contact__c.object
<CustomObject>
    <description>Contact details of the  Individual referred in STADD Program.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Referral_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Contact</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Case Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case_Document__c.object
<CustomObject>
    <customHelpPage>Help_Case_Document_VF</customHelpPage>
    <description>Some are restricted, some are collaborative: this object represents all the shared documents on an individual file (assessments, consents ... )</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Documents</relationshipLabel>
        <relationshipName>Case_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Document</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Case Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Documents</pluralLabel>
    <recordTypes>
        <fullName>Restricted</fullName>
        <active>true</active>
        <description>Restricted Case Documents will only be shared with the Navigator and the user who added the document. Any documents containing sensitive information should be uploaded as Restricted.</description>
        <label>Restricted</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Note__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Notes</relationshipLabel>
        <relationshipName>Case_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Note</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Case Note Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Notes</pluralLabel>
    <recordTypes>
        <fullName>Restricted</fullName>
        <active>true</active>
        <description>Restricted Case Notes can only be created by the Navigator and will only be seen by the Navigator for this individual’s case.</description>
        <label>Restricted</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Individual_Preferred_Name__c</fullName>
        <description>Individual Preferred Name</description>
        <encrypted>true</encrypted>
        <inlineHelpText>Individual Preferred Name</inlineHelpText>
        <label>Individual Preferred Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization1__c</fullName>
        <label>Organization</label>
        <picklist>
            <picklistValues>
                <fullName>CFD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLBC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EPBC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFSN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRACTITIONER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SD</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Northern Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraser Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vancouver Island Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vancouver Coastal Region</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Team_Member_Role__c</fullName>
        <label>Support Team Member Role</label>
        <picklist>
            <picklistValues>
                <fullName>Support Team</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFSN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contribution__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>Create</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Edit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contributions History</relationshipLabel>
        <relationshipName>Contributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region field on Contact object (associated with Created by User)</description>
        <encrypted>true</encrypted>
        <label>Region</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Contribution</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Contribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Functional__c.object
<CustomObject>
    <customHelpPage>Help_CAP_Functional_Domain_Summaries_VF</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CAP - Functional Domain Summaries</relationshipLabel>
        <relationshipName>Functional_Domains</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Functional Domain Summary</label>
    <nameField>
        <displayFormat>FD-{0000000}</displayFormat>
        <label>Functional Domain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Domain Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>A plan developed by the individual to meet certain goals.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Protocols_and_Safeguards__c.object
<CustomObject>
    <customHelpPage>Help_Protocol_and_Safeguards_VF</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Protocols and Safeguards</relationshipLabel>
        <relationshipName>Protocols_and_Safeguards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Protocols and Safeguards</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Protocol/Safeguard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols and Safeguards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Supplies_and_Equipment__c.object
<CustomObject>
    <customHelpPage>Help_Supplies_and_Equipment_VF</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Supplies and Equipment</relationshipLabel>
        <relationshipName>Supplies_and_Equipment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Supplies and Equipment</label>
    <nameField>
        <displayFormat>SEL-{0000}</displayFormat>
        <label>Supplies and Equipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplies and Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Support_and_Service__c.object
<CustomObject>
    <customHelpPage>Help_Supports_and_services</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Support_and_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Support and Service</label>
    <nameField>
        <displayFormat>SSL-{0000}</displayFormat>
        <label>Supports and Services Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supports and Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContributionLogHelper.cls
public with sharing class ContributionLogHelper {
//Note**********************************************************************************************//
	public static void CreateContributionFromNote(List<Id> plstCaseNoteId,String strObjectType,String strEventType)
	{
		List<Contribution__c> lstContribution = new List<Contribution__c>();
		List<Case_Note__c> lstCaseNote = [Select id,
												 Recordtype.Name,
												 Case__c,
												 Case__r.Contact.Name,
												 Case__r.Individual_Preferred_Name__c,
												 CreatedBy.Contact.Region__c,
												 CreatedBy.Contact.Organization1__c
												// Case__r.CreatedBy.Contact.Support_Team_Member_Role__c
		 										 from Case_Note__c where Id IN : plstCaseNoteId];
		
		Profile currentUserProfile = [Select id,Name from Profile where ID =: Userinfo.getProfileId() LIMIT 1];
		String strUserProfile = currentUserProfile.Name;
		
		for(Case_Note__c c:lstCaseNote)
		{
			lstContribution.add(CreateContribution(C.Case__c, 
													strEventType, 
													strObjectType,
													C.CreatedBy.Contact.Region__c,
													c.CreatedBy.Contact.Organization1__c,
													strUserProfile,													
													c.Recordtype.Name,													
													c.Case__r.Contact.Name ));
		}
		insert lstContribution;
	}


	public static Contribution__c CreateContribution(id pCaseId, 
														String strEventType, 
														String strObjectType,
														String strRegion,
														String StrOrganization,
														String StrRole,
														String StrRecordType,
														String StrIndividualName)
	{
		Contribution__c Con = new Contribution__c();
				Con.Case__c = pCaseId;
				Con.Action__c = strEventType;
				Con.Contribution_Type__c = strObjectType;
				if(String.isNotBlank(strRegion))
					Con.Region__c = strRegion;
				if(String.isNotBlank(StrOrganization))
					Con.Organization__c = StrOrganization;
				if(String.isNotBlank(StrRole))
					Con.User_Profile__c = StrRole;
				if (StrRecordType == 'Restricted')
					Con.Restricted_Indicator__c = true;
					else
					Con.Restricted_Indicator__c = false;
				if (String.isNotBlank(StrIndividualName))
					Con.Individual_Name__c = StrIndividualName;
			return Con;
	}
	
//Plan Goal*********************************************************************************************//	
	public static void CreateContributionFromGoal(List<Id> plstPlanGoalId,String strObjectType,String strEventType)
	{
		List<Contribution__c> lstContribution = new List<Contribution__c>(); 
		List<Plan_Goal__c> lstPlanGoal = [Select id,
												// Recordtype.Name,
												 Plan__r.Case__c,
												 Plan__r.Case__r.Contact.Name,
												 Plan__r.Case__r.Individual_Preferred_Name__c,
												 CreatedBy.Contact.Region__c,
												 CreatedBy.Contact.Organization1__c
												// Plan__r.Case__r.CreatedBy.Contact.Support_Team_Member_Role__c
		 									from Plan_Goal__c where Id IN : plstPlanGoalId];
		
		Profile currentUserProfile = [Select id,Name from Profile where ID =: Userinfo.getProfileId() LIMIT 1];
		String strUserProfile = currentUserProfile.Name;
		
		for(Plan_Goal__c c:lstPlanGoal)
		{
			lstContribution.add(CreateContributionForPlan(c.Plan__r.Case__c, 
													strEventType, 
													strObjectType,
													c.CreatedBy.Contact.Region__c,
													c.CreatedBy.Contact.Organization1__c,
													strUserProfile,													
													//c.Plan__r.Recordtype.Name,													
													c.Plan__r.Case__r.Contact.Name ));
		}
		insert lstContribution;
	}
	
		public static Contribution__c CreateContributionForPlan(id pCaseId, 
														String strEventType, 
														String strObjectType,
														String strRegion,
														String StrOrganization,
														String StrRole,
														String StrRecordType,
														String StrIndividualName)
	{
		Contribution__c Con = new Contribution__c();
				Con.Case__c = pCaseId;
				Con.Action__c = strEventType;
				Con.Contribution_Type__c = strObjectType;
				if(String.isNotBlank(strRegion))
					Con.Region__c = strRegion;
				if(String.isNotBlank(StrOrganization))
					Con.Organization__c = StrOrganization;
				if(String.isNotBlank(StrRole))
					Con.User_Profile__c = StrRole;
				if (StrRecordType == 'Restricted')
					Con.Restricted_Indicator__c = true;
					else
					Con.Restricted_Indicator__c = false;
				if (String.isNotBlank(StrIndividualName))
					Con.Individual_Name__c = StrIndividualName;
			return Con;
	}

	//Plan_Milestone**************************************************************************************//
	public static void CreateContributionFromMilestone(List<Id> plstPlanMilestoneId,String strObjectType,String strEventType)
	{
		List<Contribution__c> lstContribution = new List<Contribution__c>(); 
		List<Plan_Milestone__c> lstPlanMilestone = [Select id,
												// Recordtype.Name,
												 Plan__r.Case__c,
												 Plan__r.Case__r.Contact.Name,
												 Plan__r.Case__r.Individual_Preferred_Name__c,
												 CreatedBy.Contact.Region__c,
												 CreatedBy.Contact.Organization1__c
												 //Plan__r.Case__r.CreatedBy.Contact.Support_Team_Member_Role__c
		 									from Plan_Milestone__c where Id IN : plstPlanMilestoneId];
		 									
		Profile currentUserProfile = [Select id,Name from Profile where ID =: Userinfo.getProfileId() LIMIT 1];
		String strUserProfile = currentUserProfile.Name;
		
		for(Plan_Milestone__c c:lstPlanMilestone)
		{
			lstContribution.add(CreateContributionForPlan(c.Plan__r.Case__c, 
													strEventType, 
													strObjectType,
													c.CreatedBy.Contact.Region__c,
													c.CreatedBy.Contact.Organization1__c,
													strUserProfile,													
													//c.Plan__r.Recordtype.Name,													
													c.Plan__r.Case__r.Contact.Name ));
		}
		insert lstContribution;
	}
	
	public static Contribution__c CreateContributionForPlan(id pCaseId, 
														String strEventType, 
														String strObjectType,
														String strRegion,
														String StrOrganization,
														String StrRole,
														//String StrRecordType,
														String StrIndividualName)
	{
		Contribution__c Con = new Contribution__c();
				Con.Case__c = pCaseId;
				Con.Action__c = strEventType;
				Con.Contribution_Type__c = strObjectType;
				if(String.isNotBlank(strRegion))
					Con.Region__c = strRegion;
				if(String.isNotBlank(StrOrganization))
					Con.Organization__c = StrOrganization;
				if(String.isNotBlank(StrRole))
					Con.User_Profile__c = StrRole;
				/*if (StrRecordType == 'Restricted')
					Con.Restricted_Indicator__c = true;
					else
					Con.Restricted_Indicator__c = false;*/
				if (String.isNotBlank(StrIndividualName))
					Con.Individual_Name__c = StrIndividualName;
			return Con;
	}
	
	//Action Item ***********************************************************************************************//
	
		public static void CreateContributionFromActionItem(List<Id> plstPlanActionItemId,String strObjectType,String strEventType)
	{
		Profile currentUserProfile = [Select id,Name from Profile where ID =: Userinfo.getProfileId() LIMIT 1];
		String strUserProfile = currentUserProfile.Name;
		List<Contribution__c> lstContribution = new List<Contribution__c>(); 
		List<Action_Item__c> lstPlanActionItem = [Select id,
												// Recordtype.Name, 
												 Plan__r.Case__c,
												 Plan__r.Case__r.Contact.Name,
												 Plan__r.Case__r.Individual_Preferred_Name__c,
												 CreatedBy.Contact.Region__c,
												 CreatedBy.Contact.Organization1__c
												// currentUserProfile.Name
		 									from Action_Item__c where Id IN : plstPlanActionItemId];
		
		for(Action_Item__c c:lstPlanActionItem)
		{
			lstContribution.add(CreateContributionForActionItem(c.id,
																c.Plan__r.Case__c, 
																strEventType, 
																strObjectType,
																c.CreatedBy.Contact.Region__c,
																c.CreatedBy.Contact.Organization1__c,
																strUserProfile,													
																//c.Plan__r.Recordtype.Name,													
																c.Plan__r.Case__r.Contact.Name ));
		}
		insert lstContribution; 
	}
	
	public static Contribution__c CreateContributionForActionItem(id pActionitemid,
														id pCaseId, 
														String strEventType, 
														String strObjectType,
														String strRegion,
														String StrOrganization,
														String StrRole,
														//String StrRecordType,
														String StrIndividualName)
	{
		Contribution__c Con = new Contribution__c();
				Con.Case__c = pCaseId;
				Con.Action__c = strEventType;
				Con.Contribution_Type__c = strObjectType;
				if(String.isNotBlank(strRegion))
					Con.Region__c = strRegion;
				if(String.isNotBlank(StrOrganization))
					Con.Organization__c = StrOrganization;
				if(String.isNotBlank(StrRole))
					Con.User_Profile__c = StrRole;
				/*if (StrRecordType == 'Restricted')
					Con.Restricted_Indicator__c = true;
					else
					Con.Restricted_Indicator__c = false;*/
					Con.Action_Item_Number__c = pActionitemid;
				if (String.isNotBlank(StrIndividualName))
					Con.Individual_Name__c = StrIndividualName;
			return Con;
	}
	
	//Support and Services**********************************************************************************************//
	public static void CreateContributionFromSupportandservice(List<Id> plstServiceId,String strObjectType,String strEventType)
	{
		List<Contribution__c> lstContribution = new List<Contribution__c>();
		List<Support_and_Service__c> lstSupportandservice = [Select id,
												 //Recordtype.Name,
												 Case__c,
												 Case__r.Contact.Name,
												 Case__r.Individual_Preferred_Name__c,
												 CreatedBy.Contact.Region__c,
												 CreatedBy.Contact.Organization1__c
												 //CreatedBy.Contact.Support_Team_Member_Role__c
		 										from Support_and_Service__c where Id IN : plstServiceId];
		 										
		Profile currentUserProfile = [Select id,Name from Profile where ID =: Userinfo.getProfileId() LIMIT 1];
		String strUserProfile = currentUserProfile.Name; 
		
		for(Support_and_Service__c c:lstSupportandservice)
		{
			lstContribution.add(CreateContributionFromService(C.Case__c, 
													strEventType, 
													strObjectType,
													C.CreatedBy.Contact.Region__c,
													c.CreatedBy.Contact.Organization1__c,
													strUserProfile,													
													//c.Recordtype.Name,													
													c.Case__r.Contact.Name ));
		}
		insert lstContribution;
	}


	public static Contribution__c CreateContributionFromService(id pCaseId, 
														String strEventType, 
														String strObjectType,
														String strRegion,
														String StrOrganization,
														String StrRole,
														//String StrRecordType,
														String StrIndividualName)
	{
		Contribution__c Con = new Contribution__c();
				Con.Case__c = pCaseId;
				Con.Action__c = strEventType;
				Con.Contribution_Type__c = strObjectType;
				if(String.isNotBlank(strRegion))
					Con.Region__c = strRegion;
				if(String.isNotBlank(StrOrganization))
					Con.Organization__c = StrOrganization;
				if(String.isNotBlank(StrRole))
					Con.User_Profile__c = StrRole;
				/*if (StrRecordType == 'Restricted')
					Con.Restricted_Indicator__c = true;
					else
					Con.Restricted_Indicator__c = false;*/
				if (String.isNotBlank(StrIndividualName))
					Con.Individual_Name__c = StrIndividualName;
			return Con;
	}
	
	//Protocols and Safeguards**********************************************************************************************//
	public static void CreateContributionFromProtocolsandsafeguards(List<Id> plstProtocolId,String strObjectType,String strEventType)
	{
		List<Contribution__c> lstContribution = new List<Contribution__c>();
		List<Protocols_and_Safeguards__c> lstProtocolsandsafeguards = [Select id,
												 //Recordtype.Name,
												 Case__c,
												 Case__r.Contact.Name,
												 Case__r.Individual_Preferred_Name__c,
												 CreatedBy.Contact.Region__c,
												 CreatedBy.Contact.Organization1__c
												 //Case__r.CreatedBy.Contact.Support_Team_Member_Role__c
		 										from Protocols_and_Safeguards__c where Id IN : plstProtocolId];
		 										
		Profile currentUserProfile = [Select id,Name from Profile where ID =: Userinfo.getProfileId() LIMIT 1];
		String strUserProfile = currentUserProfile.Name;
		
		for(Protocols_and_Safeguards__c c:lstProtocolsandsafeguards)
		{
			lstContribution.add(CreateContributionFromProtocol(C.Case__c, 
													strEventType, 
													strObjectType,
													C.CreatedBy.Contact.Region__c,
													c.CreatedBy.Contact.Organization1__c,
													strUserProfile,													
													//c.Recordtype.Name,													
													c.Case__r.Contact.Name ));
		}
		insert lstContribution;
	}


	public static Contribution__c CreateContributionFromProtocol(id pCaseId, 
														String strEventType, 
														String strObjectType,
														String strRegion,
														String StrOrganization,
														String StrRole,
														//String StrRecordType,
														String StrIndividualName)
	{
		Contribution__c Con = new Contribution__c();
				Con.Case__c = pCaseId;
				Con.Action__c = strEventType;
				Con.Contribution_Type__c = strObjectType;
				if(String.isNotBlank(strRegion))
					Con.Region__c = strRegion;
				if(String.isNotBlank(StrOrganization))
					Con.Organization__c = StrOrganization;
				if(String.isNotBlank(StrRole))
					Con.User_Profile__c = StrRole;
				/*if (StrRecordType == 'Restricted')
					Con.Restricted_Indicator__c = true;
					else
					Con.Restricted_Indicator__c = false;*/
				if (String.isNotBlank(StrIndividualName))
					Con.Individual_Name__c = StrIndividualName;
			return Con;
	}
	
	//Supplies and Equipments**********************************************************************************************//
	public static void CreateContributionFromSuppliesandEquipments(List<Id> plstSuppliesId,String strObjectType,String strEventType)
	{
		List<Contribution__c> lstContribution = new List<Contribution__c>();
		List<Supplies_and_Equipment__c> lstSuppliesandEquipments = [Select id,
												 //Recordtype.Name,
												 Case__c,
												 Case__r.Contact.Name,
												 Case__r.Individual_Preferred_Name__c,
												 CreatedBy.Contact.Region__c,
												 CreatedBy.Contact.Organization1__c
												 //Case__r.CreatedBy.Contact.Support_Team_Member_Role__c
		 										from Supplies_and_Equipment__c where Id IN : plstSuppliesId];
		 										
		Profile currentUserProfile = [Select id,Name from Profile where ID =: Userinfo.getProfileId() LIMIT 1];
		String strUserProfile = currentUserProfile.Name;
		
		for(Supplies_and_Equipment__c c:lstSuppliesandEquipments)
		{
			lstContribution.add(CreateContributionFromSupplies(C.Case__c, 
													strEventType, 
													strObjectType,
													C.CreatedBy.Contact.Region__c,
													c.CreatedBy.Contact.Organization1__c,
													strUserProfile,													
													//c.Recordtype.Name,													
													c.Case__r.Contact.Name ));
		}
		insert lstContribution;
	}


	public static Contribution__c CreateContributionFromSupplies(id pCaseId, 
														String strEventType, 
														String strObjectType,
														String strRegion,
														String StrOrganization,
														String StrRole,
														//String StrRecordType,
														String StrIndividualName)
	{
		Contribution__c Con = new Contribution__c();
				Con.Case__c = pCaseId;
				Con.Action__c = strEventType;
				Con.Contribution_Type__c = strObjectType;
				if(String.isNotBlank(strRegion))
					Con.Region__c = strRegion;
				if(String.isNotBlank(StrOrganization))
					Con.Organization__c = StrOrganization;
				if(String.isNotBlank(StrRole))
					Con.User_Profile__c = StrRole;
				/*if (StrRecordType == 'Restricted')
					Con.Restricted_Indicator__c = true;
					else
					Con.Restricted_Indicator__c = false;*/
				if (String.isNotBlank(StrIndividualName))
					Con.Individual_Name__c = StrIndividualName;
			return Con;
	}
	
	//List of Assessments**********************************************************************************************//
	public static void CreateContributionFromAssessments(List<Id> plstAssessmentId,String strObjectType,String strEventType)
	{
		List<Contribution__c> lstContribution = new List<Contribution__c>();
		List<Assessment_List__c> lstAssessments = [Select id,
												 //Recordtype.Name,
												 Case__c,
												 Case__r.Contact.Name,
												 Case__r.Individual_Preferred_Name__c,
												 CreatedBy.Contact.Region__c,
												 CreatedBy.Contact.Organization1__c
												 //Case__r.CreatedBy.Contact.Support_Team_Member_Role__c
		 										from Assessment_List__c where Id IN : plstAssessmentId];
		 										
		Profile currentUserProfile = [Select id,Name from Profile where ID =: Userinfo.getProfileId() LIMIT 1];
		String strUserProfile = currentUserProfile.Name;
		
		for(Assessment_List__c c:lstAssessments)
		{
			lstContribution.add(CreateContributionFromAssessments(C.Case__c, 
													strEventType, 
													strObjectType,
													C.CreatedBy.Contact.Region__c,
													c.CreatedBy.Contact.Organization1__c,
													strUserProfile,													
													//c.Recordtype.Name,													
													c.Case__r.Contact.Name ));
		}
		insert lstContribution;
	}


	public static Contribution__c CreateContributionFromAssessments(id pCaseId, 
														String strEventType, 
														String strObjectType,
														String strRegion,
														String StrOrganization,
														String StrRole,
														//String StrRecordType,
														String StrIndividualName)
	{
		Contribution__c Con = new Contribution__c();
				Con.Case__c = pCaseId;
				Con.Action__c = strEventType;
				Con.Contribution_Type__c = strObjectType;
				if(String.isNotBlank(strRegion))
					Con.Region__c = strRegion;
				if(String.isNotBlank(StrOrganization))
					Con.Organization__c = StrOrganization;
				if(String.isNotBlank(StrRole))
					Con.User_Profile__c = StrRole;
				/*if (StrRecordType == 'Restricted')
					Con.Restricted_Indicator__c = true;
					else
					Con.Restricted_Indicator__c = false;*/
				if (String.isNotBlank(StrIndividualName))
					Con.Individual_Name__c = StrIndividualName;
			return Con;
	}
	
	//Case Alert**********************************************************************************************//
	public static void CreateContributionFromCaseAlert(List<Id> plstCaseAlertId,String strObjectType,String strEventType)
	{
		List<Contribution__c> lstContribution = new List<Contribution__c>();
		List<Case_Alert__c> lstCaseAlert = [Select id,
												 Recordtype.Name,
												 Case__c,
												 Case__r.Contact.Name,
												 Case__r.Individual_Preferred_Name__c,
												 CreatedBy.Contact.Region__c,
												 CreatedBy.Contact.Organization1__c
												 //Case__r.CreatedBy.Contact.Support_Team_Member_Role__c
		 										from Case_Alert__c where Id IN : plstCaseAlertId];
		 										
		Profile currentUserProfile = [Select id,Name from Profile where ID =: Userinfo.getProfileId() LIMIT 1];
		String strUserProfile = currentUserProfile.Name;
		
		for(Case_Alert__c c:lstCaseAlert)
		{
			lstContribution.add(CreateContributionFromCaseAlert(C.Case__c, 
													strEventType, 
													strObjectType,
													C.CreatedBy.Contact.Region__c,
													c.CreatedBy.Contact.Organization1__c,
													strUserProfile,													
													c.Recordtype.Name,													
													c.Case__r.Contact.Name ));
		}
		insert lstContribution;
	}


	public static Contribution__c CreateContributionFromCaseAlert(id pCaseId, 
														String strEventType, 
														String strObjectType,
														String strRegion,
														String StrOrganization,
														String StrRole,
														String StrRecordType,
														String StrIndividualName)
	{
		Contribution__c Con = new Contribution__c();
				Con.Case__c = pCaseId;
				Con.Action__c = strEventType;
				Con.Contribution_Type__c = strObjectType;
				if(String.isNotBlank(strRegion))
					Con.Region__c = strRegion;
				if(String.isNotBlank(StrOrganization))
					Con.Organization__c = StrOrganization;
				if(String.isNotBlank(StrRole))
					Con.User_Profile__c = StrRole;
				if (StrRecordType == 'Restricted')
					Con.Restricted_Indicator__c = true;
					else
					Con.Restricted_Indicator__c = false;
				if (String.isNotBlank(StrIndividualName))
					Con.Individual_Name__c = StrIndividualName;
			return Con;
	}
	
	//Case Document**********************************************************************************************//
	public static void CreateContributionFromCaseDocuments(List<Id> plstCaseDocumentId,String strObjectType,String strEventType)
	{
		List<Contribution__c> lstContribution = new List<Contribution__c>();
		List<Case_Document__c> lstCaseDocument = [Select id,
												 Recordtype.Name,
												 Case__c,
												 Case__r.Contact.Name,
												 Case__r.Individual_Preferred_Name__c,
												 CreatedBy.Contact.Region__c,
												 CreatedBy.Contact.Organization1__c
												 //Case__r.CreatedBy.Contact.Support_Team_Member_Role__c
		 										from Case_Document__c where Id IN : plstCaseDocumentId];
		 										
		Profile currentUserProfile = [Select id,Name from Profile where ID =: Userinfo.getProfileId() LIMIT 1];
		String strUserProfile = currentUserProfile.Name;
		
		for(Case_Document__c c:lstCaseDocument) 
		{
			lstContribution.add(CreateContributionFromCaseDocuments(C.Case__c, 
													strEventType, 
													strObjectType,
													C.CreatedBy.Contact.Region__c,
													c.CreatedBy.Contact.Organization1__c,
													strUserProfile,													
													c.Recordtype.Name,													
													c.Case__r.Contact.Name ));
		}
		insert lstContribution;
	}


	public static Contribution__c CreateContributionFromCaseDocuments(id pCaseId, 
														String strEventType, 
														String strObjectType,
														String strRegion,
														String StrOrganization,
														String StrRole,
														String StrRecordType,
														String StrIndividualName)
	{
		Contribution__c Con = new Contribution__c();
				Con.Case__c = pCaseId;
				Con.Action__c = strEventType;
				Con.Contribution_Type__c = strObjectType;
				if(String.isNotBlank(strRegion))
					Con.Region__c = strRegion;
				if(String.isNotBlank(StrOrganization))
					Con.Organization__c = StrOrganization;
				if(String.isNotBlank(StrRole))
					Con.User_Profile__c = StrRole;
				if (StrRecordType == 'Restricted')
					Con.Restricted_Indicator__c = true;
					else
					Con.Restricted_Indicator__c = false;
				if (String.isNotBlank(StrIndividualName))
					Con.Individual_Name__c = StrIndividualName;
			return Con; 
	}
	
	//Case Contact**********************************************************************************************//
	public static void CreateContributionFromCaseContact(List<Id> plstCaseContactId,String strObjectType,String strEventType)
	{
		List<Contribution__c> lstContribution = new List<Contribution__c>();
		List<Case_Contact__c> lstCaseContact = [Select id,
												 //Recordtype.Name,
												 Case__c,
												 Case__r.Contact.Name,
												 Case__r.Individual_Preferred_Name__c,
												 CreatedBy.Contact.Region__c,
												 CreatedBy.Contact.Organization1__c
												 //Case__r.CreatedBy.Contact.Support_Team_Member_Role__c
		 										from Case_Contact__c where Id IN : plstCaseContactId];
		 										
		Profile currentUserProfile = [Select id,Name from Profile where ID =: Userinfo.getProfileId() LIMIT 1];
		String strUserProfile = currentUserProfile.Name;
		
		for(Case_Contact__c c:lstCaseContact)
		{
			lstContribution.add(CreateContributionFromCaseContact(C.Case__c, 
													strEventType, 
													strObjectType,
													C.CreatedBy.Contact.Region__c,
													c.CreatedBy.Contact.Organization1__c,
													strUserProfile,													
													//c.Recordtype.Name,													
													c.Case__r.Contact.Name ));
		}
		insert lstContribution;
	}


	public static Contribution__c CreateContributionFromCaseContact(id pCaseId, 
														String strEventType, 
														String strObjectType,
														String strRegion,
														String StrOrganization,
														String StrRole,
														//String StrRecordType,
														String StrIndividualName)
	{
		Contribution__c Con = new Contribution__c();
				Con.Case__c = pCaseId;
				Con.Action__c = strEventType;
				Con.Contribution_Type__c = strObjectType;
				if(String.isNotBlank(strRegion))
					Con.Region__c = strRegion;
				if(String.isNotBlank(StrOrganization))
					Con.Organization__c = StrOrganization;
				if(String.isNotBlank(StrRole))
					Con.User_Profile__c = StrRole;
				/*if (StrRecordType == 'Restricted')
					Con.Restricted_Indicator__c = true;
					else
					Con.Restricted_Indicator__c = false;*/
				if (String.isNotBlank(StrIndividualName))
					Con.Individual_Name__c = StrIndividualName;
			return Con;
	}
	
	//Case Functional Domain Summaries**********************************************************************************************//
	public static void CreateContributionFromCaseFunctionalDomainSummaries(List<Id> plstCaseFunctionalDomainSummaryId,String strObjectType,String strEventType)
	{
		List<Contribution__c> lstContribution = new List<Contribution__c>();
		List<Functional__c> lstCaseFunctionalDomainSummary = [Select id,
												 //Recordtype.Name,
												 Case__c,
												 Case__r.Contact.Name,
												 Case__r.Individual_Preferred_Name__c,
												 CreatedBy.Contact.Region__c,
												 CreatedBy.Contact.Organization1__c
												 //Case__r.CreatedBy.Contact.Support_Team_Member_Role__c
		 										from Functional__c where Id IN : plstCaseFunctionalDomainSummaryId];
		 										
		Profile currentUserProfile = [Select id,Name from Profile where ID =: Userinfo.getProfileId() LIMIT 1];
		String strUserProfile = currentUserProfile.Name;
		
		for(Functional__c c:lstCaseFunctionalDomainSummary)
		{
			lstContribution.add(CreateContributionFromCaseFunctionalDomainSummaries(C.Case__c, 
													strEventType, 
													strObjectType,
													C.CreatedBy.Contact.Region__c,
													c.CreatedBy.Contact.Organization1__c,
													strUserProfile,													
													//c.Recordtype.Name,													
													c.Case__r.Contact.Name ));
		}
		insert lstContribution;
	}


	public static Contribution__c CreateContributionFromCaseFunctionalDomainSummaries(id pCaseId, 
														String strEventType, 
														String strObjectType,
														String strRegion,
														String StrOrganization,
														String StrRole,
														//String StrRecordType,
														String StrIndividualName)
	{
		Contribution__c Con = new Contribution__c();
				Con.Case__c = pCaseId;
				Con.Action__c = strEventType;
				Con.Contribution_Type__c = strObjectType;
				if(String.isNotBlank(strRegion))
					Con.Region__c = strRegion;
				if(String.isNotBlank(StrOrganization))
					Con.Organization__c = StrOrganization;
				if(String.isNotBlank(StrRole))
					Con.User_Profile__c = StrRole;
				/*if (StrRecordType == 'Restricted')
					Con.Restricted_Indicator__c = true;
					else
					Con.Restricted_Indicator__c = false;*/
				if (String.isNotBlank(StrIndividualName))
					Con.Individual_Name__c = StrIndividualName;
			return Con;
	}

//Case Functional Domain Update**********************************************************************************************//
	public static void CreateContributionFromCaseFunctionalDomainUpdate(List<Id> plstCaseFunctionalDomainUpdateId,String strObjectType,String strEventType)
	{
		List<Contribution__c> lstContribution = new List<Contribution__c>();
		List<Functional_Domain_Update__c> lstCaseFunctionalDomainUpdate = [Select id,
												 //Recordtype.Name,
												 Functional_Domain__r.Case__c,
												 Functional_Domain__r.Case__r.Contact.Name,
												 Functional_Domain__r.Case__r.Individual_Preferred_Name__c,
												 CreatedBy.Contact.Region__c,
												 CreatedBy.Contact.Organization1__c
												 //Functional_Domain__r.CreatedBy.Contact.Support_Team_Member_Role__c
		 										from Functional_Domain_Update__c where Id IN : plstCaseFunctionalDomainUpdateId];
		 										
		Profile currentUserProfile = [Select id,Name from Profile where ID =: Userinfo.getProfileId() LIMIT 1];
		String strUserProfile = currentUserProfile.Name;
		
		for(Functional_Domain_Update__c c:lstCaseFunctionalDomainUpdate)
		{
			lstContribution.add(CreateContributionFromCaseFunctionalDomainUpdate(C.Functional_Domain__r.Case__c, 
													strEventType, 
													strObjectType,
													C.CreatedBy.Contact.Region__c,
													c.CreatedBy.Contact.Organization1__c,
													strUserProfile,													
													//c.Recordtype.Name,													
													c.Functional_Domain__r.Case__r.Contact.Name ));
		}
		insert lstContribution;
	}


	public static Contribution__c CreateContributionFromCaseFunctionalDomainUpdate(id pCaseId, 
														String strEventType, 
														String strObjectType,
														String strRegion,
														String StrOrganization,
														String StrRole,
														//String StrRecordType,
														String StrIndividualName)
	{
		Contribution__c Con = new Contribution__c();
				Con.Case__c = pCaseId;
				Con.Action__c = strEventType;
				Con.Contribution_Type__c = strObjectType;
				if(String.isNotBlank(strRegion))
					Con.Region__c = strRegion;
				if(String.isNotBlank(StrOrganization))
					Con.Organization__c = StrOrganization;
				if(String.isNotBlank(StrRole))
					Con.User_Profile__c = StrRole;
				/*if (StrRecordType == 'Restricted')
					Con.Restricted_Indicator__c = true;
					else
					Con.Restricted_Indicator__c = false;*/
				if (String.isNotBlank(StrIndividualName))
					Con.Individual_Name__c = StrIndividualName;
			return Con;
	}
	
}