src/objects/Action_Item__c.object
<CustomObject>
    <customHelpPage>Help_Action_Item_VF</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Plan Milestone</label>
        <referenceTo>Plan_Milestone__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Goal</label>
        <referenceTo>Plan_Goal__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <formula>TEXT(Plan__r.Plan_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Plan Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Action Item</label>
    <nameField>
        <displayFormat>AI-{00000}</displayFormat>
        <label>Action Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <customHelpPage>Help_Milestone_VF</customHelpPage>
    <description>BME - Milestones will be used to track the Key Events during the lifecycle of a Project/Release. This object is an important component for status reports and Milestones will be always related to a Release</description>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>A plan developed by the individual to meet certain goals.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Status__c</fullName>
        <label>Plan Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Place/ Signed-off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Support Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contingency Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crisis Plan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Goal__c.object
<CustomObject>
    <customHelpPage>Help_PlanGoals</customHelpPage>
    <description>Goals comprise the plan.</description>
    <fields>
        <fullName>Plan__c</fullName>
        <description>Plan</description>
        <inlineHelpText>Plan</inlineHelpText>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Plan Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Plan Goal</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Goal Name (If Goal Type is &apos;Other&apos;)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Milestone__c.object
<CustomObject>
    <customHelpPage>Help_Milestone_VF</customHelpPage>
    <fields>
        <fullName>Plan_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Goal</description>
        <inlineHelpText>Goal</inlineHelpText>
        <label>Plan Goal</label>
        <referenceTo>Plan_Goal__c</referenceTo>
        <relationshipLabel>Plan Milestones</relationshipLabel>
        <relationshipName>Plan_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Plan Milestones</relationshipLabel>
        <relationshipName>Plan_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Plan Milestone</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UpdatePlanAndGoal_Test.cls
/* Class Name  : UpdatePlanAndGoal_Test
 * Description : Test class for an Apex class UpdatePlanAndGoal, UniqueSupportPlan trigger
 * Created By  : Silviu Frantescu
 * Created On  : 10-21-2013
*/

@isTest
private class UpdatePlanAndGoal_Test{
    static case cas;
    static Plan__c plan;
    static Plan_Goal__c goal;
    static Plan_Milestone__c mileStone;
    static Action_Item__c actItem;
    private static testmethod void testData(){
        cas = new case ();
        cas.status = 'New';
        cas.Origin = 'Phone';        
        insert cas;
        plan = new Plan__c();
        plan.Case__c = cas.id;
        insert plan;
        goal = new Plan_Goal__c ();
        goal.Plan__c = plan.Id;
        insert goal;
        mileStone = new Plan_Milestone__c();
        mileStone.Plan_Goal__c = goal.Id;
        milestone.Plan__c = plan.id;
        insert mileStone;
        actItem = new Action_Item__c();
        actItem.Milestone__c = mileStone.Id;
        insert actItem;          
    }
    private static testmethod void testTriggerInsert(){
        test.startTest();
        testData();     
        test.stopTest();    
    }
    
    private static testmethod void testuniquesupportplan(){
    	case cas1;
	     Plan__c plan1;
	     Plan__c plan2;
	    cas1 = new case ();
        cas1.status = 'New';
        cas1.Origin = 'Phone';        
        insert cas1;
        plan1 = new Plan__c();
        plan1.Case__c = cas1.id;
        plan1.Plan_Type__c = 'Support Plan';
        plan1.Plan_Status__c = 'Not Active';
        insert plan1;
        plan2 = new Plan__c();
        plan2.Case__c = cas1.id;
        plan2.Plan_Type__c = 'Crisis Plan';
        plan2.Plan_Status__c = 'Not Active';
        insert plan2;
        test.startTest();
       
        System.assert(true);
        test.stopTest();
    }
}