src/objects/Action_Item__c.object
<CustomObject>
    <customHelpPage>Help_Action_Item_VF</customHelpPage>
    <fields>
        <fullName>Activity__c</fullName>
        <encrypted>true</encrypted>
        <label>Action Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assign_To_Me__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Assign To Me</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <label>Plan Milestone</label>
        <referenceTo>Plan_Milestone__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Goal</label>
        <referenceTo>Plan_Goal__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Review_Date__c</fullName>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dependency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Item</label>
    <nameField>
        <displayFormat>AI-{00000}</displayFormat>
        <label>Action Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Items</pluralLabel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <label>Closed</label>
    </recordTypes>
    <recordTypes>
        <fullName>Restricted</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>A Restricted Case Record means that support team users have a very limited view of this individual’s case. They will only be able to see: Individual name, Individual Case ID, Navigator, Case Status and the Case Record Type.</description>
        <label>Restricted</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Alert__c.object
<CustomObject>
    <customHelpPage>Help_CaseAlert</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Alerts</relationshipLabel>
        <relationshipName>Case_Alerts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Alert</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Alerts</pluralLabel>
    <recordTypes>
        <fullName>Collaborative</fullName>
        <active>true</active>
        <description>Collaborative Case Alerts will be shared with all support team members for this individual&apos;s case.</description>
        <label>Collaborative</label>
    </recordTypes>
    <recordTypes>
        <fullName>Restricted</fullName>
        <active>true</active>
        <description>Restricted Case Alerts will only be shared with the Navigator and the user who added the case alert.</description>
        <label>Restricted</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <customHelpPage>Help_Milestone_VF</customHelpPage>
    <description>BME - Milestones will be used to track the Key Events during the lifecycle of a Project/Release. This object is an important component for status reports and Milestones will be always related to a Release</description>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>Select the current status of this Milestone</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>On Schedule</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Off Schedule</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>A plan developed by the individual to meet certain goals.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Status__c</fullName>
        <label>Plan Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Place/ Signed-off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Goal__c.object
<CustomObject>
    <customHelpPage>Help_PlanGoals</customHelpPage>
    <description>Goals comprise the plan.</description>
    <fields>
        <fullName>Plan__c</fullName>
        <description>Plan</description>
        <inlineHelpText>Plan</inlineHelpText>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Plan Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan Goal</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Goal Name (If Goal Type is &apos;Other&apos;)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Goals</pluralLabel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Milestone__c.object
<CustomObject>
    <customHelpPage>Help_Milestone_VF</customHelpPage>
    <fields>
        <fullName>Plan_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Goal</description>
        <inlineHelpText>Goal</inlineHelpText>
        <label>Plan Goal</label>
        <referenceTo>Plan_Goal__c</referenceTo>
        <relationshipLabel>Plan Milestones</relationshipLabel>
        <relationshipName>Plan_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Plan Milestones</relationshipLabel>
        <relationshipName>Plan_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan Milestone</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Milestones</pluralLabel>
    <recordTypes>
        <fullName>Closed</fullName>
        <active>true</active>
        <label>Closed</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CaseCloseTrigger_Test.cls
/* Class Name  : CaseCloseTrigger_Test
 * Description : Test class for an Apex trigger CaseCloseTrigger
 * Created By  : Silviu Frantescu
 * Created On  : 10-29-2013
*/

@isTest
public class CaseCloseTrigger_Test{
    private static case cas;
    
    public static testmethod void testData(){
    	Profile profiles = [Select p.name, p.id From Profile p where p.Name like 'System Administrator'];
        
        User usr = new User(alias = 'standt', email='testcasealert@gov.bc.ca', emailencodingkey='UTF-8', 
									lastname='test', firstname='test', languagelocalekey='en_US', 
									localesidkey='en_CA', profileid = profiles.id,
									timezonesidkey='America/Los_Angeles', username='testcasealert@test.com');
		insert usr;
        cas = new case();
        cas.Status = 'New';
        cas.OwnerId = usr.id;
        insert cas;
        
        Case_Alert__c alert1 = new Case_Alert__c ();
        alert1.Name = 'test alert';
        alert1.Case__c = cas.id;
        alert1.Status__c = 'Open';
        alert1.Priority__c ='Normal';
        //List<RecordType> rectype =[Select Id,Name From RecordType Where Name = 'Restricted' and SobjectType ='Case_Alert__c' limit 1];
        
        string AlertRecordID = Schema.SObjectType.Case_Alert__c.RecordTypeInfosByName.get('Restricted').RecordTypeId; 
        alert1.RecordTypeId = AlertRecordID;
        insert alert1;
        
        Plan__c plan = new Plan__c ();
        plan.Case__c = cas.Id;
        plan.Plan_Status__c = 'Draft in Progress';
        insert plan;
        Plan_Goal__c goal = new Plan_Goal__c ();
        goal.Plan__c = plan.Id;
        
        goal.Status__c = 'Active';
        insert goal;
        goal.Status__c = 'Future Planning';
        update goal;
        Plan_Milestone__c milestone = new Plan_Milestone__c ();
        milestone.Plan_Goal__c = goal.Id;
        milestone.Plan__c = plan.id;
        milestone.Status__c = 'Active';
        insert milestone;
        milestone.Status__c = 'Completed';
        update milestone;
        Action_Item__c actItem = new Action_Item__c ();
        actItem.Milestone__c = milestone.Id;
        actItem.Status__c ='Not Started';
        insert actItem;
        actItem.Status__c = 'Complete';
        update actItem;
        
        test.startTest();
        try{
            testData();
            cas.Status = 'Closed';
            update cas;
            update alert1;
            System.assert(false);
        }
        catch(Exception ex){
            //Expected
        }
        test.stopTest();
									
    }
    private static testmethod void testCloseCase(){
        
    }
    
    private static testmethod void testNotifyCaseAlert(){
    	Profile profiles = [Select p.name, p.id From Profile p where p.Name like 'System Administrator'];
        
        User usr = new User(alias = 'stand3', email='test1234@gov.bc.ca', emailencodingkey='UTF-8', 
                                    lastname='test', firstname='test', languagelocalekey='en_US', 
                                    localesidkey='en_CA', profileid = profiles.id,
                                    timezonesidkey='America/Los_Angeles', username='testcollalert2121@test.com');
        insert usr;
        Case casnew= new Case();
        casnew.Status = 'New';
        casnew.OwnerId = usr.Id;
        insert casnew;
        CaseTeamMember casteam = new CaseTeamMember();
        casteam.ParentId= casnew.id;
        casteam.MemberId =usr.id;
        List<CaseTeamRole> teamrole = [Select Id, Name, AccessLevel FROM CaseTeamRole limit 1];
        casteam.TeamRoleId = teamrole[0].id;      
        insert casteam;       
        Case_Alert__c alert = new Case_Alert__c ();
        //List<RecordType> rectype = [Select Id,Name From RecordType Where Name = 'Collaborative' and SobjectType ='Case_Alert__c' limit 1];
        //alert.RecordTypeId = rectype[0].id;
        string AlertRecordID = Schema.SObjectType.Case_Alert__c.RecordTypeInfosByName.get('Collaborative').RecordTypeId; 
        alert.RecordTypeId = AlertRecordID;
        alert.Case__c = casnew.id;
        alert.Status__c = 'Open';
        alert.Priority__c ='Normal';
        alert.Name = 'test';
        insert alert;
        
                
        /*Plan__c plan = new Plan__c ();
        plan.Case__c = casnew.Id;
        plan.Plan_Status__c = 'Draft in Progress';
        insert plan;
        Plan_Goal__c goal = new Plan_Goal__c ();
        goal.Plan__c = plan.Id;
        goal.Status__c = 'Active';
        insert goal;
        Plan_Milestone__c milestone = new Plan_Milestone__c ();
        milestone.Plan_Goal__c = goal.Id;
        milestone.Status__c = 'Active';
        insert milestone;
        Action_Item__c actItem = new Action_Item__c ();
        actItem.Milestone__c = milestone.Id;
        actItem.Status__c ='Not Started';
        insert actItem;*/
        
        
        test.startTest();
        
        try{
			casnew.Status = 'Closed';
            update casnew;
            update alert;
            System.assert(false);
        	}
        catch(Exception ex){
            //Expected
        }
        test.stopTest();
    }
    
    
    private static testmethod void SetActionitemAssignedTo(){
    	Profile profiles = [Select p.name, p.id From Profile p where p.Name like 'System Administrator'];
        
        User usr = new User(alias = 'standt', email='testAssignto@gov.bc.ca', emailencodingkey='UTF-8', 
									lastname='test', firstname='test', languagelocalekey='en_US', 
									localesidkey='en_CA', profileid = profiles.id,
									timezonesidkey='America/Los_Angeles', username='testcaseartassign@test.com');
		insert usr;
    	Case cas2= new Case();
        cas2.Status = 'New';
        cas2.OwnerId = usr.id;
        insert cas2;
        Case_Alert__c alert = new Case_Alert__c ();
        alert.Case__c = cas2.id;
        alert.Status__c = 'open';
        alert.Priority__c = 'Normal';
        alert.Name ='testalert3';
        string AlertRecordID = Schema.SObjectType.Case_Alert__c.RecordTypeInfosByName.get('Restricted').RecordTypeId; 
        alert.RecordTypeId = AlertRecordID;
        insert alert;
        Plan__c plan = new Plan__c ();
        plan.Case__c = cas2.Id;
        plan.Plan_Status__c = 'Draft in Progress';
        insert plan;
        Plan_Goal__c goal = new Plan_Goal__c ();
        goal.Plan__c = plan.Id;
        goal.Status__c = 'Active';
        insert goal;
        Plan_Milestone__c milestone = new Plan_Milestone__c ();
        milestone.Plan_Goal__c = goal.Id;
        milestone.Status__c = 'Active';
        milestone.Plan__c = plan.id;
        insert milestone;
        Action_Item__c actItem = new Action_Item__c ();
        actItem.Milestone__c = milestone.Id;
        actItem.Status__c ='Not Started';
        actItem.Activity__c = 'Test';
        actItem.Review_Date__c = system.today();
        actItem.Assign_To_Me__c = true;
        insert actItem;
        
        
        test.startTest();
        
        try{
			cas2.Status = 'Closed';
            update cas2;
            update alert;
            System.assert(false);
        	}
        catch(Exception ex){
            //Expected
        }
        test.stopTest();
    }
    
	private static testmethod void CaseAlertCount(){
    	Profile profiles = [Select p.name, p.id From Profile p where p.Name like 'System Administrator'];
        
        User usr = new User(alias = 'standt', email='testAssigncount@gov.bc.ca', emailencodingkey='UTF-8', 
									lastname='test', firstname='test', languagelocalekey='en_US', 
									localesidkey='en_CA', profileid = profiles.id,
									timezonesidkey='America/Los_Angeles', username='testcasealertcount@test.com');
		insert usr;
    	Case cas3= new Case();
        cas3.Status = 'New';
        cas3.OwnerId = usr.id;
        insert cas3;
        Case_Alert__c alert = new Case_Alert__c ();
        alert.Case__c = cas3.id;
        alert.Status__c = 'open';
        string AlertRecordID = Schema.SObjectType.Case_Alert__c.RecordTypeInfosByName.get('Restricted').RecordTypeId; 
        alert.RecordTypeId = AlertRecordID;
        alert.Priority__c = 'Normal';
        alert.Name ='testalert3';
        insert alert;
        
        Plan__c plan = new Plan__c ();
        plan.Case__c = cas3.Id;
        plan.Plan_Status__c = 'Draft in Progress';
        insert plan;
        Plan_Goal__c goal = new Plan_Goal__c ();
        goal.Plan__c = plan.Id;
        goal.Status__c = 'Active';
        insert goal;
        Plan_Milestone__c milestone = new Plan_Milestone__c ();
        milestone.Plan_Goal__c = goal.Id;
        milestone.Status__c = 'Active';
        milestone.Plan__c = plan.id;
        insert milestone;
        Action_Item__c actItem = new Action_Item__c ();
        actItem.Milestone__c = milestone.Id;
        actItem.Status__c ='Not Started';
        actItem.Activity__c = 'Test';
        actItem.Review_Date__c = system.today();
        actItem.Assign_To_Me__c = true;
        insert actItem;
        
        
        test.startTest();
        
        try{
			cas3.Status = 'Closed';
            update cas3;
            update alert;
            System.assert(false);
        	}
        catch(Exception ex){
            //Expected
        }
        test.stopTest();
    }
}