src/objects/Action_Item__c.object
<CustomObject>
    <customHelpPage>Help_Action_Item_VF</customHelpPage>
    <fields>
        <fullName>Action_Item_Type__c</fullName>
        <label>Action Item Type</label>
        <picklist>
            <picklistValues>
                <fullName>Alert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complaint</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Protocol</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Activity__c</fullName>
        <encrypted>true</encrypted>
        <label>Action Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Action items can be assigned to users of Collaborate only.  If you need to assign an action item to a person who does not access Collaborate, please assign to yourself and describe who will complete the item in the description.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encrypted>true</encrypted>
        <label>Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Individual_Name__c</fullName>
        <formula>Plan__r.Case__r.Contact.FirstName &amp; &quot; &quot; &amp; Plan__r.Case__r.Contact.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Individual Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Action Items</relationshipLabel>
        <relationshipName>Action_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Review_Date__c</fullName>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dependency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Action Item</label>
    <nameField>
        <displayFormat>AI-{00000}</displayFormat>
        <label>Action Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Action Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Alert__c.object
<CustomObject>
    <customHelpPage>Help_CaseAlert</customHelpPage>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Alerts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Alerts</relationshipLabel>
        <relationshipName>Case_Alerts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encrypted>true</encrypted>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Alert</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Alerts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Document__c.object
<CustomObject>
    <customHelpPage>Help_Case_Document_VF</customHelpPage>
    <description>Some are restricted, some are collaborative: this object represents all the shared documents on an individual file (assessments, consents ... )</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Documents</relationshipLabel>
        <relationshipName>Case_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <encrypted>true</encrypted>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Case Document</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Case Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contribution__c.object
<CustomObject>
    <fields>
        <fullName>Action_Item_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Action Item</label>
        <referenceTo>Action_Item__c</referenceTo>
        <relationshipLabel>Contributions</relationshipLabel>
        <relationshipName>Contributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contributions History</relationshipLabel>
        <relationshipName>Contributions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Individual_Name__c</fullName>
        <encrypted>true</encrypted>
        <label>Individual Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Contribution</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Contribution Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contributions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Functional__c.object
<CustomObject>
    <customHelpPage>Help_CAP_Functional_Domain_Summaries_VF</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CAP - Functional Domain Summaries</relationshipLabel>
        <relationshipName>Functional_Domains</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Individual_Name__c</fullName>
        <formula>Case__r.Contact.FirstName + &quot; &quot; +  Case__r.Contact.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Individual Name</label>
        <type>Text</type>
    </fields>
    <label>Functional Domain Summary</label>
    <nameField>
        <displayFormat>FD-{0000000}</displayFormat>
        <label>Functional Domain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Domain Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>A plan developed by the individual to meet certain goals.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GoalTaskHomepageController.cls
public with sharing class GoalTaskHomepageController {
    
    public CaseVO[] cases {get; set;}
    public Action_Item__c[] actionItems {get; set;}
    public Contribution__c[] contributions {get; set;} 
    public String actionItemFilter {get; set;}
    
    // URL construction helpers
    public static String baseUrl {get; private set;}
    public static String caseAlertObjectPrefix {get; private set;}
    public static String contributionObjectPrefix {get; private set;}
    public static String functionalDomainObjectPrefix {get; private set;}
    public static String caseAlertRelatedListId {get; private set;}
    public static String contributionRelatedListId {get; private set;}
    public static String functionalDomainRelatedListId {get; private set;}

    public static String alertCase_fieldId {get; private set;}
    public static String contributionCase_fieldId {get; private set;}
    public static String docCase_fieldId {get; private set;}
    public static String actionItemStatus_fieldId {get; private set;}

    static {
        loadUrlHelpers();
    }
    
    public Datetime lastLoginDate {get; private set;}
    
    public class CaseVO {
        public Case obj {get; set;} // 'case' is a reserved keyword.
        public Boolean selected {get; set;}
        
        public Boolean hasNewAlert {get{
            return newAlertCount != 0;
        }}
        public Integer newAlertCount {get{
            return (obj.Case_Alerts1__r == null) ? 0 : obj.Case_Alerts1__r.size();
        }}
        
        public Boolean hasNewContribution {get{
            return newContributionCount != 0;
            }}
        public Integer newContributionCount {get{
            return (obj.Contributions__r == null) ? 0 : obj.Contributions__r.size();
        }}
        
        public Boolean hasNewFunctionalDomain {get{
            return newFunctionalDomainCount != 0;
        }}
        public Integer newFunctionalDomainCount {get{
            return (obj.Functional_Domains__r == null) ? 0 : obj.Functional_Domains__r.size();
        }}
        
        private List<Action_Item__c> overdueActionItems {get; set;}
        public Boolean hasOverdueActionItems {get{
            return overdueActionItemsCount > 0;
        }}
        public Integer overdueActionItemsCount {get{
            return (overdueActionItems == null) ? 0 : overdueActionItems.size();
        }}
        
        public CaseVO(Case c, List<Action_Item__c> overdueActionItems) {
            obj = c;
            selected = false;
            this.overdueActionItems = overdueActionItems;
        } 
    }

    public GoalTaskHomepageController() {
        setLastLogin();
        loadCases();
        loadActionItems();
    }
    
    public void loadCases() {
        this.cases = new List<CaseVO>();
        Case[] caseObjects =
            [Select CaseNumber, ContactId, Contact.Name, Subject, Status, LastModifiedDate,
            (Select Name, CreatedDate From Case_Alerts1__r Where CreatedDate >= :lastLoginDate),
            (Select Name, CreatedDate From Contributions__r Where CreatedDate >= :lastLoginDate),
            (Select Name, CreatedDate From Functional_Domains__r Where CreatedDate >= :lastLoginDate)
            From Case Order By LastModifiedDate DESC Limit 250];
        Map<Id, List<Action_Item__c>> overdueActionItemsMap = loadOverdueActionItems(caseObjects);
        for (Case c : caseObjects) {
            this.cases.add(new CaseVO(c, overdueActionItemsMap.get(c.id))); 
        }
    }
    
    public void loadActionItems() {
        actionItemFilter = (actionItemFilter == null) ? 'allOpen' : actionItemFilter;
        this.actionItems = new List<Action_Item__c>();
        Date today = Date.today();
        String query = 'Select Name, Status__c, Individual_Name__c, Activity__c, Description__c, Review_Date__c, Action_Item_Type__c, Priority__c';
        query += ' From Action_Item__c Where Assigned_To__c = \'' + UserInfo.getUserId() + '\'';
        if (actionItemFilter == 'allOpen') {
            this.actionItems = Database.query(query + ' and Status__c != \'Complete\' and Status__c != \'No Longer Required\' ORDER BY Review_Date__c ASC'); // Reju modified for defect D-00180 and D-00349
        }
        if (actionItemFilter == 'overdue') {
            this.actionItems = Database.query(query + ' and Status__c != \'Complete\' and Status__c != \'No Longer Required\' and Review_Date__c <= :today ORDER BY Review_Date__c ASC'); // Reju modified for defect D-00180 and D-00349
        }
        if (actionItemFilter == 'nextSevenDays') {
            Date sevenFromToday = Date.today().addDays(7);
            this.actionItems = Database.query(query + ' and Status__c != \'Complete\' and Status__c != \'No Longer Required\' and Review_Date__c <= :sevenFromToday and Review_Date__c >= :today ORDER BY Review_Date__c ASC'); // Reju modified for defect D-00180 and D-00349
        }
        if (actionItemFilter == 'nextTwoWeeks') {
            Date fourteenFromToday = Date.today().addDays(14);
            this.actionItems = Database.query(query + ' and Status__c != \'Complete\' and Status__c != \'No Longer Required\' and Review_Date__c <= :fourteenFromToday and Review_Date__c >= :today ORDER BY Review_Date__c ASC'); //Reju modified for defect D-00180 and D-00349
        }
        
    }
    
    public Map<Id, List<Action_Item__c>> loadOverdueActionItems(Case[] caseObjects) {
        Set<Id> caseIds = new Set<Id>();
        for (Case c : caseObjects) {
            caseIds.add(c.Id);
        }
        map<Id, List<Action_Item__c>> caseIdsToOverdueActionItems = new Map<Id, List<Action_Item__c>>();
        List<Action_Item__c> actionItems = [Select Id, Plan__r.Case__c,Individual_Name__c from Action_Item__c 
          where Status__c != :'Complete' and Review_Date__c <= TODAY and Plan__r.Case__c IN :caseIds];

        for(Action_Item__c actionItem : actionItems) {
            Id caseId = actionItem.Plan__r.Case__c;
            if (!caseIdsToOverdueActionItems.containsKey(caseId)) {
                caseIdsToOverdueActionItems.put(caseId, new List<Action_Item__c>()); 
            }
            caseIdsToOverdueActionItems.get(caseId).add(actionItem);
        }
        
        return caseIdsToOverdueActionItems;
    }
    
    private static void loadUrlHelpers() {
        baseUrl = URL.getSalesforceBaseUrl().toExternalForm();
        if (Site.getPrefix() != null) {
            baseUrl +=  Site.getPrefix();
        }
        caseAlertObjectPrefix = ObjectHelper.getObjectPrefix('Case_Alert__c');
        // This changes between orgs. Update after deploying to production.        
        caseAlertRelatedListId = '00Ni000000BeUcS'; //config
        // 00Ni0000008Excf config
        // 00Nf0000000HuKO sprint2
        // 00Nf0000000Py7S sprint1
        // 00Ni000000BeUcS production
        
        contributionObjectPrefix = ObjectHelper.getObjectPrefix('Contribution__c');
        // This changes between orgs. Update after deploying to production.        
        contributionRelatedListId = '00Ni000000EpmPB';
        // 00Nf0000000ttfm config
        // 00Ni000000EpmPB production
       
        functionalDomainObjectPrefix = ObjectHelper.getObjectPrefix('Functional__c');
        // This changes between orgs. Update after deploying to production.
        functionalDomainRelatedListId = '00Ni000000BeUdX'; //config
        // 00Nf0000000Pztg config
        // 00Nf0000000IO9d sprint2
        // 00Nf0000000Q159 sprint1
        // 00Ni000000BeUdX production

        alertCase_fieldId = ObjectHelper.fieldIdMap('Case_Alert__c').get('Case');
        contributionCase_fieldId = ObjectHelper.fieldIdMap('Contribution__c').get('Case');
        docCase_fieldId = ObjectHelper.fieldIdMap('Case_Document__c').get('Case');
        
        actionItemStatus_fieldId = ObjectHelper.fieldIdMap('Action_Item__c').get('Status');
    }
    
    private void setLastLogin() {
        // Always skip last 3 days.
        LoginHistory lastLogin = null;
        for (LoginHistory l : [SELECT UserId, LoginTime from LoginHistory 
            where UserId = :System.UserInfo.getUserId() and LoginTime < :Datetime.now().addDays(-3)
            ORDER BY LoginTime DESC NULLS LAST Limit 1]) {
            lastLogin = l;
        }
        
        // if no previous login, set back 2 months
        lastLoginDate = (lastLogin == null) ? Datetime.now().addDays(-60) : lastLogin.LoginTime;
    }
}