src/objects/Assessment_List__c.object
<CustomObject>
    <customHelpPage>Help_Assessment_List_Item_VF</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>List of Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Functional_Domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Domain</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Functional__c.Case__c</field>
                <operation>equals</operation>
                <valueField>$Source.Case__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Functional__c</referenceTo>
        <relationshipLabel>Assessments List Items</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Assessment List Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assessment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Functional__c.object
<CustomObject>
    <customHelpPage>Help_CAP_Functional_Domain_Summaries_VF</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CAP - Functional Domain Summaries</relationshipLabel>
        <relationshipName>Functional_Domains</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Functional Domain Summary</label>
    <nameField>
        <displayFormat>FD-{0000000}</displayFormat>
        <label>Functional Domain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Domain Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PopulateCaseOnAssessmentHelper.cls
/* @Trigger Name : PopulateCaseOnAssessmentHelper 
 * @Description  : This class is a helper class for the Assessment trigger
 * @Created By   : Reju Palathingal 
 * @Created On   : 10/03/2013
 * @Modification Log:  
 * -----------------------------------------------------------------------------
 * @Developer                Date                  Description 
 * -----------------------------------------------------------------------------
 * @Reju Palathingal         10/03/2013                Created
 * 
 * -----------------------------------------------------------------------------
 */

public with sharing class PopulateCaseOnAssessmentHelper {


Public static Set<id>parentIds = new Set<id>();

public static void manageInsertCase(List<Assessment_List__c> newTriggerList)
		
	{
	
	    for(Assessment_List__c ast :newTriggerList)
	    {
	        parentIds.add(ast.Functional_Domain__c);
	    }
	    Map<id,Functional__c> pro = new Map<id,Functional__c>([select id, Case__c from Functional__c where id in :parentIds]);
	    system.debug('Map' +pro);
	    for(Assessment_List__c astlst :newTriggerList)
	    {
	        
	            if(pro.containsKey(astlst.Functional_Domain__c))
	            	
	            {
	                        
	                astlst.Case__c = pro.get(astlst.Functional_Domain__c).Case__c;
	            }   
	    }           
	}
}