src/objects/Assessment_List__c.object
<CustomObject>
    <customHelpPage>Help_Assessment_List_Item_VF</customHelpPage>
    <fields>
        <fullName>Assessment_Name__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Assessment Name and Date are mandatory</inlineHelpText>
        <label>Assessment Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>List of Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Assessed__c</fullName>
        <encrypted>true</encrypted>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <label>Assessment List Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assessment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Functional__c.object
<CustomObject>
    <customHelpPage>Help_CAP_Functional_Domain_Summaries_VF</customHelpPage>
    <fields>
        <fullName>Assesor_Role__c</fullName>
        <encrypted>true</encrypted>
        <label>Profession of Assessor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessment_Date__c</fullName>
        <encrypted>true</encrypted>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CAP - Functional Domain Summaries</relationshipLabel>
        <relationshipName>Functional_Domains</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Functional_Domain_Type__c</fullName>
        <label>Functional Domain Type</label>
        <picklist>
            <picklistValues>
                <fullName>Physical Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Living Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Participation Skills and Social Inclusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Interaction and Self-Determination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Styles and Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language and Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reason and Decision-Making</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioral and Emotional Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health: Diagnostic Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Space Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <encrypted>true</encrypted>
        <label>Functional Domain Summary Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Functional Domain Summary</label>
    <nameField>
        <displayFormat>FD-{0000000}</displayFormat>
        <label>Functional Domain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Domain Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Mapping_object__c.object
<CustomObject>
    <fields>
        <fullName>Context_prompt__c</fullName>
        <label>Context prompt</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Functional_Domain_Type__c</fullName>
        <label>Functional Domain Type</label>
        <picklist>
            <picklistValues>
                <fullName>Physical Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Living Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Participation Skills and Social Inclusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Interaction and Self-Determination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Styles and Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language and Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reason and Decision-Making</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioral and Emotional Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health: Diagnostic Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Space Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReferralPage1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReferralPage2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReferralPage3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FunctionalDomainPage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PortalUserRegistration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Mapping object</label>
    <nameField>
        <displayFormat>Map-{0000}</displayFormat>
        <label>Mapping object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapping objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateFuncDomainController_Test.cls
/* Class Name  : CaseControllerExtension_Test
 * Description : Test class for an Apex class CaseControllerExtension 
 * Created By  : Silviu Frantescu
 * Created On  : 09-30-2013
*/

@isTest
private class CreateFuncDomainController_Test{
    /*public Integer numberOfRowToRemove=1; 
     private static testmethod void createControllerTest(){       
        Case cas = new case ();
        cas.status = 'New';
        cas.Origin = 'Phone';
        test.starttest();
        insert cas; 
        Functional__c fun= new Functional__c();
        fun.Case__c =cas.id;
        fun.Assesor_Role__c ='Test';
        fun.Assessment_Date__c =system.today();
        fun.Summary__c = 'test';
        fun.Functional_Domain_Type__c ='Physical Functioning';
        insert fun;
        Assessment_List__c asList = new Assessment_List__c();
        asList.Case__c =cas.Id;
        asList.Assessment_Name__c = 'Test Name';
        asList.Date_Assessed__c = system.today();
       
       
        Mapping_object__c mapobj = new Mapping_object__c();
        mapobj.Functional_Domain_Type__c = 'FunctionalDomainPage';
        mapobj.Context_prompt__c= 'Test';
        insert mapobj;
         
      
        ApexPages.StandardController sc = new ApexPages.StandardController(cas); 
        CreateFuncDomainController obj = new CreateFuncDomainController (sc);
        
        //obj.assesmentlist = new list<Assessment_List__c> ();
        obj.test = true;    
        
        //obj.assesmentlist.add(asList);
        obj.getcontext();       
        obj.addassesment();
        //obj.removeassesment();      
        obj.SubmitandAdd();
        obj.submit();
 
        test.stoptest();
        system.assertNotEquals(obj.assesmentlist, null);      
    }   
     private static testmethod void createControllerSubmitTest(){       
        Case cas = new case ();
        cas.status = 'New';
        cas.Origin = 'Phone';
        test.starttest();
        insert cas; 
        Functional__c fun= new Functional__c();
        fun.Case__c =cas.Id;
        fun.Assesor_Role__c ='Test';
        fun.Assessment_Date__c =system.today();
        fun.Summary__c = 'test';
        fun.Functional_Domain_Type__c ='Physical Functioning';
        insert fun;
        Assessment_List__c asList = new Assessment_List__c();
        asList.Case__c =cas.Id;
        asList.Assessment_Name__c = 'Test Name';
        
        asList.Date_Assessed__c = system.today();
        Mapping_object__c mapobj = new Mapping_object__c();
        mapobj.Functional_Domain_Type__c = 'FunctionalDomainPage';
        mapobj.Context_prompt__c= 'Test';
        insert mapobj;
       
        ApexPages.StandardController sc = new ApexPages.StandardController(cas); 
        CreateFuncDomainController obj = new CreateFuncDomainController (sc);
        obj.test = true;        
        //obj.assesmentlist = new list<Assessment_List__c> ();
        //obj.assesmentlist.add(asList);
        
        obj.submit();
        obj.SubmitandAdd();   
        test.stoptest();        
        system.assertNotEquals(obj.finalUpdateAsseslst, null);
    }   
    
    private static testmethod void createControllerremovetest(){       
        Case cas = new case ();
        cas.status = 'New';
        cas.Origin = 'Phone';
        test.starttest();
        insert cas; 
        Functional__c fun= new Functional__c();
        fun.Case__c =cas.Id;
        fun.Assesor_Role__c ='Test';
        fun.Assessment_Date__c =system.today();
        fun.Summary__c = 'test';
        fun.Functional_Domain_Type__c ='Physical Functioning';
        insert fun;
        Assessment_List__c asList = new Assessment_List__c();
        asList.Case__c =cas.Id;
        asList.Assessment_Name__c = 'Test Name';
        
        asList.Date_Assessed__c = system.today();
        Mapping_object__c mapobj = new Mapping_object__c();
        mapobj.Functional_Domain_Type__c = 'FunctionalDomainPage';
        mapobj.Context_prompt__c= 'Test';
        insert mapobj;
       
        ApexPages.StandardController sc = new ApexPages.StandardController(cas); 
        CreateFuncDomainController obj = new CreateFuncDomainController (sc);
        obj.test = true;        
        
        obj.addassesment();
        //obj.removeassesment();
          
        test.stoptest();        
       // system.assertNotEquals(obj.finalUpdateAsseslst, null);
    } */  
}