src/objects/Assessment_List__c.object
<CustomObject>
    <customHelpPage>Help_Assessment_List_Item_VF</customHelpPage>
    <fields>
        <fullName>Assessment_Name__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Assessment Name and Date are mandatory</inlineHelpText>
        <label>Assessment Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>List of Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Credential_Role_of_Assessor__c</fullName>
        <defaultValue>$User.Relationship__c</defaultValue>
        <encrypted>true</encrypted>
        <label>Credential/Role of Assessor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Assessed__c</fullName>
        <encrypted>true</encrypted>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <label>Assessment List Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assessment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PopulateCaseOnAssessment_Test.cls
/* Class Name  : CaseControllerExtension_Test
 * Description : Test class for an Apex trigger PopulateCaseOnAssessment 
 * Created By  : Reju Palathingal
 * Created On  : 10-03-2013
*/

@isTest

public with sharing class PopulateCaseOnAssessment_Test 
{
     private static testmethod void PopulatecontrollerTest()
     {    
     	Case cas = new case ();
        cas.status = 'New';
        cas.Origin = 'Phone';
        insert cas; 
        Assessment_List__c ast = new Assessment_List__c ();
        ast.Assessment_Name__c = 'test';
        ast.Date_Assessed__c = system.today();
        ast.Credential_Role_of_Assessor__c ='pro';
        ast.Case__c = cas.id;
        test.starttest();
        insert ast;      
        
        
       system.assertNotEquals(ast.Case__c, null);      
        test.stoptest();   
    }   

}