src/objects/Assessment_List__c.object
<CustomObject>
    <customHelpPage>Help_Assessment_List_Item_VF</customHelpPage>
    <fields>
        <fullName>Assessment_Name__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Assessment Name and Date are mandatory</inlineHelpText>
        <label>Assessment Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessor_First_Name__c</fullName>
        <defaultValue>$User.FirstName</defaultValue>
        <encrypted>true</encrypted>
        <label>Assessor First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessor_Last_Name__c</fullName>
        <defaultValue>$User.LastName</defaultValue>
        <encrypted>true</encrypted>
        <label>Assessor Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>List of Assessments</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Assessed__c</fullName>
        <encrypted>true</encrypted>
        <label>Assessment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Functional_Domain__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Functional Domain</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Functional__c.Case__c</field>
                <operation>equals</operation>
                <valueField>$Source.Case__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Functional__c</referenceTo>
        <relationshipLabel>Assessments List Items</relationshipLabel>
        <relationshipName>Assessments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <encrypted>true</encrypted>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Assessment List Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assessment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Functional__c.object
<CustomObject>
    <customHelpPage>Help_CAP_Functional_Domain_Summaries_VF</customHelpPage>
    <fields>
        <fullName>Assessor_First_Name__c</fullName>
        <defaultValue>$User.FirstName</defaultValue>
        <encrypted>true</encrypted>
        <label>Assessor First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessor_Last_Name__c</fullName>
        <defaultValue>$User.LastName</defaultValue>
        <encrypted>true</encrypted>
        <label>Assessor Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CAP - Functional Domain Summaries</relationshipLabel>
        <relationshipName>Functional_Domains</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Functional_Domain_Type__c</fullName>
        <label>Functional Domain Type</label>
        <picklist>
            <picklistValues>
                <fullName>Physical Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Living Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Participation Skills and Social Inclusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Interaction and Self-Determination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Styles and Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language and Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reason and Decision-Making</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioral and Emotional Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health: Diagnostic Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Space Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Functional Domain Summary</label>
    <nameField>
        <displayFormat>FD-{0000000}</displayFormat>
        <label>Functional Domain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Domain Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Mapping_object__c.object
<CustomObject>
    <fields>
        <fullName>Context_prompt__c</fullName>
        <label>Context prompt</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Functional_Domain_Type__c</fullName>
        <label>Functional Domain Type</label>
        <picklist>
            <picklistValues>
                <fullName>Physical Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Living Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Participation Skills and Social Inclusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Interaction and Self-Determination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Styles and Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language and Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reason and Decision-Making</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioral and Emotional Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health: Diagnostic Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Space Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReferralPage1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReferralPage2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReferralPage3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FunctionalDomainPage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PortalUserRegistration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Mapping object</label>
    <nameField>
        <displayFormat>Map-{0000}</displayFormat>
        <label>Mapping object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapping objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreateFuncDomainController.cls
/******************************************************************************************
** ICM STADD Project
*******************************************************************************************
** Class Name: Functional domain wizard
** Description: Creation of the functional domain, assessment recods and navigate to upload documents controller.
** Version: 1.0
** 
**-----------------------------------------------------------------------------------------
**Modification Log:
**----------------
**Developer                  Date          Version               Description
**-----------------------------------------------------------------------------------------
**Reju Palathingal           25/9/2013         1.0                   Created** 
**
********************************************************************************************/

public class CreateFuncDomainController 
{
    Case cs;
    public Boolean test{get; set;}
    public List<Assessment_List__c> assesmentlist{get;set;} 
   // public Assessment_List__c astlst{get;set;}
    public Mapping_object__c mapobj{get; set;}
    public Mapping_object__c mapobjText{get; set;}
    public Functional__c funcdom {get;set;} 
    public List<Assessment_List__c> finalUpdateAsseslst{get; set;}
    public List<Assessment_List__c> errorlist{get; set;}
    public List<Assessment_List__c> insertlist{get; set;}
    public boolean isButtonDisabled {get; set;}
    String result = '';
    public String caseid{get;set;}
    public Integer numberOfRowToRemove { get; set; }
    public Integer rowNumber {get; set;}
        
            
        //Controller for creating a new Functional Document
    public CreateFuncDomainController(ApexPages.StandardController controller) 
    {
        funcdom = new Functional__c();      
        mapobj = new Mapping_object__c();
        
        mapobjText = [select id,Functional_Domain_Type__c,Context_prompt__c 
                                from Mapping_object__c where Functional_Domain_Type__c = 'FunctionalDomainPage' LIMIT 1];
        assesmentlist =  new List<Assessment_List__c>();
        
                cs = (case)controller.getrecord();
                caseid= cs.Id;
                assesmentlist.add(new Assessment_List__c());
                
                //predefault the userfirstname and lastname for assessment records
                for(Assessment_List__c alst : assesmentlist)
                {
                        alst.Assessor_First_Name__c = UserInfo.getFirstName();
                        alst.Assessor_Last_Name__c = UserInfo.getLastName();
                }
                
    }  
    //Fetch the context from Mapping Object
    public PageReference getcontext()
    {
        try
        {           
            mapobj = [select id,Functional_Domain_Type__c,Context_prompt__c 
                                from Mapping_object__c 
                                where Functional_Domain_Type__c =: funcdom.Functional_Domain_Type__c LIMIT 1];               
        }
        catch(exception e)
        {
            String result = System.Label.Create_Functional_Domain_2; //You do not have a helptext
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, result));
        }   
            return null;
    }
    
    //Add new assesment section  
    public PageReference addassesment()
    {
    	if(assesmentlist.size()< 4)
    	{
    		assesmentlist.add(new Assessment_List__c());
        
       		for(Assessment_List__c lst : assesmentlist){    
        
        	lst.Assessor_First_Name__c = UserInfo.getFirstName();
            lst.Assessor_Last_Name__c = UserInfo.getLastName();
        	}
    	}
        else if(assesmentlist.size()== 4)
        {
        	assesmentlist.add(new Assessment_List__c());
        	for(Assessment_List__c lst : assesmentlist){    
        
        	lst.Assessor_First_Name__c = UserInfo.getFirstName();
            lst.Assessor_Last_Name__c = UserInfo.getLastName();
        	}
        	isButtonDisabled = true; //disable the add button
        }   
        
    return null;    
    }   
    
    //Delete the Assesment section
    public PageReference removeassesment()
    {
	    assesmentlist.remove(numberOfRowToRemove);
	        if(assesmentlist.size()<5)
	        {
	                isButtonDisabled = false; //enable the add button
	        }
          
    return null;    
    }   
    
    public PageReference SubmitandAdd()
    {
        try{        
                  
                        finalUpdateAsseslst = new list<Assessment_List__c>();
                        errorlist = new list<Assessment_List__c>();
                        insertlist = new list<Assessment_List__c>();
                        if(test == true)
                        {
                                for(Assessment_List__c ast : assesmentlist)               
                                {
                                        //checks for any of the 3 fields are populated, then assessment gets created
                                        if(ast.Assessment_Name__c != null || ast.Date_Assessed__c != null || ast.Notes__c != null)
                                        {
                                
                                if(ast.Assessment_Name__c != null && ast.Date_Assessed__c != null)
                                                {  
                                                        finalUpdateAsseslst.add(ast);
                                                }   
                                                else
                                                {
                                                        errorlist.add(ast);//list creates the warning message for the required fields for assessment
                                                }   
                                        }   
                                }
                                if(errorlist.size() >0)
                                {                       
                                system.debug('error');
                                String result = System.Label.Create_Functional_Domain_1; //Please complete the assessment details
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, result));                          
                                return null;   
                                }      
                                else
                                {
                                funcdom.Case__c = cs.Id;

                                insert funcdom;

                                if(finalUpdateAsseslst.size() >0)
                                { 
                                    for(Assessment_List__c fin : finalUpdateAsseslst)
                                     {
                                            fin.Functional_Domain__c = funcdom.id;
                                            //fin.Case__c = cs.Id;                          
                                            
                                            insertlist.add(fin);
                                     }               
                                     insert insertlist;//inserts the Assessments
                                 }

                                }
                }
                        else
                        {
                                funcdom.Case__c = cs.Id;
                                insert funcdom;// inserts functional domain record
                        }  
                }            
                     
            
        catch (DMLException e) 
                {
                      String result = System.Label.Create_Functional_Domain_3; //Please contact the administrator
                          ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, result));
                      return null;
                 } 
        finally{
                }   
                PageReference refPage = new PageReference('/apex/uploadAssesmentDoc?id='+ cs.Id) ;              
                refPage.setRedirect(true);
                return refPage; 
    }
    

        
    public PageReference submit() // MH+SF: changed from "save" to "submit" 27/9/2013
    {
        
        try{                
                   
                  finalUpdateAsseslst = new list<Assessment_List__c>();
                  errorlist = new list<Assessment_List__c>();
                  insertlist = new list<Assessment_List__c>();
                  if(test == true)
                  {
                          for(Assessment_List__c ast : assesmentlist)               
                          {
                                //checks for any of the 3 fields are populated, then assessment gets created
                                if(ast.Assessment_Name__c != null || ast.Date_Assessed__c != null || ast.Notes__c != null)
                                                {       
                                        if(ast.Assessment_Name__c != null && ast.Date_Assessed__c != null)
                                        {  
                                        finalUpdateAsseslst.add(ast);
                                        }   
                                    else
                                    {
                                        errorlist.add(ast);//list creates the warning message for the required fields for assessment
                                    }   
                                                }
                          }
                          if(errorlist.size() >0)
                          {                       
                                system.debug('error');
                                                String result = System.Label.Create_Functional_Domain_1; //Please complete the assessment details
                                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, result));                
                              return null;   
                          }      
                          else
                          {
                                funcdom.Case__c = cs.Id;
                                
                                insert funcdom;
                              
                                if(finalUpdateAsseslst.size() >0)
                                      { 
                                        for(Assessment_List__c fin : finalUpdateAsseslst) {
                                                fin.Functional_Domain__c = funcdom.id;
                                                //fin.Case__c = cs.Id;                          
                                                
                                                insertlist.add(fin);
                                        }               
                                        insert insertlist;//inserts the Assessments
                                      }
                        
                                }
                      }
                  else
                  {
                        funcdom.Case__c = cs.Id;
                            insert funcdom;// inserts functional domain record
                                        }  
        }            
            
        catch (DMLException e) 
                {
                      String result = System.Label.Create_Functional_Domain_3; //Please contact the administrator
                          ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, result));                      
                      return null;
                 } 
        finally{
                }   
    
                PageReference refPage = new PageReference('/' + funcdom.Id);                
                refPage.setRedirect(true);
                return refPage;
    }
         
}