src/objects/Case.object
<CustomObject>
    <recordTypes>
        <fullName>Restricted</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>A Restricted Case Record means that support team users have a very limited view of this individual’s case. They will only be able to see: Individual name, Individual Case ID, Navigator, Case Status and the Case Record Type.</description>
        <label>Restricted</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Document__c.object
<CustomObject>
    <customHelpPage>Help_Case_Document_VF</customHelpPage>
    <description>Some are restricted, some are collaborative: this object represents all the shared documents on an individual file (assessments, consents ... )</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Documents</relationshipLabel>
        <relationshipName>Case_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Consent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correspondence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health / Safety Reports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Protocol / Safeguard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFSN - Template</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFSN - Picture Template</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education - IEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service / Support Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Plans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crisis / Contingency Plans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diagnosis Proof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive Behavioural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Psychological / Psychiatric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Document</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Case Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Documents</pluralLabel>
    <recordTypes>
        <fullName>Restricted</fullName>
        <active>true</active>
        <description>Restricted Case Documents will only be shared with the Navigator and the user who added the document. Any documents containing sensitive information should be uploaded as Restricted.</description>
        <label>Restricted</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UploadAssessmentDocController.cls
/******************************************************************************************
** ICM STADD Project
*******************************************************************************************
** Class Name: Upload documents
** Description: Upload the assessment documents for the case.
** Version: 1.0
** 
**-----------------------------------------------------------------------------------------
**Modification Log:
**----------------
**Developer                  Date          Version               Description
**-----------------------------------------------------------------------------------------
**Reju Palathingal           27/9/2013         1.0                   Created** 
**
********************************************************************************************/

public without sharing class UploadAssessmentDocController {

	public id csid{get;set;}
	public Case casrecord{get;set;}
    public Case_Document__c casdocument{get;set;}
    public Attachment vDocument{get; set;} 
    public List<Account> acclst{get; set;} 
    public String accname{get;set;}
    public String accfirstname{get;set;}
    public id recdid{get; set;}
//Constructor

	public UploadAssessmentDocController(ApexPages.StandardController controller) 

	{
		csid = ApexPages.currentPage().getParameters().get('id');
		casdocument = new Case_Document__c();
		casdocument.Category__c = 'Assessment'; //GV
		vDocument = new Attachment();
		
		recdid = controller.getId();
		Case record = [select id,AccountId from Case where id =:recdid limit 1];
		string casaccid = record.AccountId;
		system.debug(casaccid);
		acclst = [select id,Name,LastName,FirstName from Account where id =:casaccid limit 1];
		if(acclst.size()>0)
		{
			accname = acclst[0].LastName;
			accfirstname =acclst[0].FirstName;
			system.debug('accname'+accname);
		}
	}
	// Logic for upload button
	public PageReference Upload()
	{
		if(vDocument.Body != null){
		try{
			System.debug('####%%%%%%%%GV>>>>>' +csid + vDocument.Body);
			
						
			List<RecordType> casdocrectype2 =[Select Id,Name From RecordType Where Name = 'Restricted' and SobjectType ='Case_Document__c' limit 1];
            casdocument.RecordTypeId = casdocrectype2.get(0).id;
			casdocument.Case__c = csid;
			casdocument.Category__c = 'Assessment';
			casdocument.Name = 'Assessment'+ '-'+casdocument.Sub_Category__c;
			insert casdocument;
			
			string dname = vDocument.Name;
			//List<String> parts = dname.split('\\.');                                      
      		//string split = parts[parts.size()-1];       		
      		//vDocument.Name = casdocument.Sub_Category__c+'.'+split;  Commented as not required post CC  release post R1.2
      		
			vDocument.ParentId = casdocument.id;
			insert vDocument;
			}
			
		Catch(exception e){
			String MSG = System.Label.Upload_Doc_4; //Please contact the administrator
        	ApexPages.addMessage ( new ApexPages.Message(ApexPages.Severity.ERROR, MSG));
            return null;
			
		}
		finally{
			vDocument.body = null;
			
		}

		PageReference refPage = new PageReference ('/' + csid);              
	    refPage.setRedirect(true);
	    return refPage;	
    	}
		else
		{
			System.debug('####%%%%%%%%GV>>>>>' +csid + vDocument.Body);
			String MSG = System.Label.Upload_Doc_1;
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, MSG));
		return null;	
		}
	}
	//Logic for Upload and Add button
	public PageReference Uploadandadd()
	{
		if(vDocument.Body != null){
		try{
			
			System.debug('####%%%%%%%%>>>>>' +csid);
			List<RecordType> casdocrectype2 =[Select Id,Name From RecordType Where Name = 'Restricted' and SobjectType ='Case_Document__c' limit 1];
            casdocument.RecordTypeId = casdocrectype2.get(0).id;
			casdocument.Case__c = csid;
			casdocument.Category__c = 'Assessment';
			casdocument.Name = 'Assessment'+ '-'+casdocument.Sub_Category__c;
			insert casdocument;
			
			string dname2 = vDocument.Name;			
			//List<String> parts1 = dname2.split('\\.');                                      
      		//string split2 = parts1[parts1.size()-1]; 
      		
      		//vDocument.Name = casdocument.Sub_Category__c+'.'+split2;  Commented as not required post CC  release post R1.2
			vDocument.ParentId = casdocument.id;
			insert vDocument;
			
		  }
		Catch(exception e){
			
			String MSG = System.Label.Upload_Doc_2;  //Please attach the documents
        	ApexPages.addMessage ( new ApexPages.Message(ApexPages.Severity.ERROR, MSG));
			
            return null;
			
		}
		finally{
			vDocument.body = null;
			
		}
		
		
		PageReference refPage = new PageReference('/apex/uploadAssesmentDoc?id='+ csid);              
	    refPage.setRedirect(true);
	    return refPage;
		}	
    else
		{
			System.debug('####%%%%%%%%GV>>>>>' +csid + vDocument.Body);
			String MSG = System.Label.Upload_Doc_3;//Please choose the file before uploading
        	ApexPages.addMessage ( new ApexPages.Message(ApexPages.Severity.ERROR, MSG));
		return null;	
		}
	}
	
}