src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Northern Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraser Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vancouver Island Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vancouver Coastal Region</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Contact__c.object
<CustomObject>
    <description>Contact details of the  Individual referred in STADD Program.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Referral_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Person_Profession_Role__c</fullName>
        <encrypted>true</encrypted>
        <label>Profession / Role</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Case Contacts</relationshipLabel>
        <relationshipName>Case_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Professional_Identifying_Number__c</fullName>
        <label>Professional Identifying Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Case Contact</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Case Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Middle_Name__c</fullName>
        <encrypted>true</encrypted>
        <label>Middle Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Person_Profession_Role__c</fullName>
        <label>Contact Person Profession Role</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>On_Behalf_Of__c</fullName>
        <encrypted>true</encrypted>
        <label>On Behalf Of</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Professional_Identifying_Number__c</fullName>
        <label>Professional Identifying Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Northern Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraser Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vancouver Island Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vancouver Coastal Region</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Relationship_to_Individual_if_Other__c</fullName>
        <label>Relationship to Individual (if Other)</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Portal_User_Counter__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Portal User Counter</description>
    <fields>
        <fullName>PortalUserCount__c</fullName>
        <defaultValue>1</defaultValue>
        <label>PortalUserCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Portal User Counter</label>
</CustomObject>

src/objects/Portal_User_Org__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Portal_User_Org__c</fullName>
        <description>Config</description>
        <label>Portal User Org</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Portal User Org</label>
</CustomObject>

src/objects/System_Access_Request__c.object
<CustomObject>
    <fields>
        <fullName>Case_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Case Contact</description>
        <label>Case Contact</label>
        <referenceTo>Case_Contact__c</referenceTo>
        <relationshipLabel>System Access Requests</relationshipLabel>
        <relationshipName>System_Access_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Phone_Number__c</fullName>
        <encrypted>true</encrypted>
        <label>Contact Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>EIS_Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Northern Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraser Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vancouver Island Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vancouver Coastal Region</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encrypted>true</encrypted>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Part of full name of the user requesting EIS Access</description>
        <encrypted>true</encrypted>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encrypted>true</encrypted>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name_Initial__c</fullName>
        <description>Part of full name of the user requesting EIS Access</description>
        <encrypted>true</encrypted>
        <label>Middle Initial</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>On_Behalf_Of__c</fullName>
        <encrypted>true</encrypted>
        <label>On Behalf Of</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Portal_Access_Granted__c</fullName>
        <description>Portal Access Granted</description>
        <label>Portal Access Granted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Professional_Identifying_Number__c</fullName>
        <label>Professional Identifying Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Relationship_to_Individual_if_Other__c</fullName>
        <label>Relationship to Individual (if Other)</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SiteMinder_GUID__c</fullName>
        <label>SiteMinder GUID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Credentials_OR_Role_Profession__c</fullName>
        <description>Be very careful when changing values of this picklist as the code is trying to match exactly with the case team role (i.e. compares the exact text of the string)</description>
        <inlineHelpText>will dictate the case team role once user created and added to case team</inlineHelpText>
        <label>User Credentials OR Role/Profession</label>
        <picklist>
            <picklistValues>
                <fullName>Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLBC Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCFD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nurse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self-Advocate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Therapist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>System Access Request</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>System Access Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Access Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Federation_ID__c</fullName>
        <description>Siteminder GUID</description>
        <label>Federation ID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/PartnerPortalUserController.cls
/* Class Name  : PartnerPortalUserController 
 * Description : This class is used to create partner community user and it provides access to community users for their respective cases.
 * Created By  : Silviu Frantescu
 * Created On  : 10-24-2013
*/

public class PartnerPortalUserController {
       public Contact con {get;set;}
       public User u {get;set;}
       public User newUser {get;set;}
       public Decimal counter {get; set;}
       public String Org {get; set;}
       public  System_Access_Request__c accessObj {get;set;}
       public String sSelectedProfileId {get;set;}
       public String sSystemRequestId {get;set;}
       public Boolean bIsNewUserFound {get;set;}
       public String role;
       Savepoint sp;
       //Constructor
       public PartnerPortalUserController () {
       		Portal_User_Counter__c C = Portal_User_Counter__c.getOrgDefaults();
       		Portal_User_Org__c O = Portal_User_Org__c.getOrgDefaults();
            counter = C.PortalUserCount__c + 1 ;
            Org = O.Portal_User_Org__c;
            
            sSystemRequestId = apexpages.currentpage().getparameters().get('id');
            accessObj = [select First_Name__c, Middle_Name_Initial__c, Last_Name__c, Email__c, Status__c, On_Behalf_Of__c, User_Credentials_OR_Role_Profession__c, Relationship_to_Individual_if_Other__c, EIS_Region__c,
                            Contact_Phone_Number__c, Professional_Identifying_Number__c, SiteMinder_GUID__c, Case_Contact__c, Case_Contact__r.Case__c from System_Access_Request__c where id = :sSystemRequestId];
            con = new Contact();
            u = new User();
            u.Username = Org+'Communityuser'+ integer.valueof(counter) +'@stadd.com';//accessObj.Email__c;
            newUser= new User();
            bIsNewUserFound = false;
            
        }
        
       public PageReference checkForNewUser(){
        try{
            System.debug('bIsNewUserFound: ' + bIsNewUserFound);
            if(bIsNewUserFound == true)
                return null;            
            System.debug('checking for new user with username:' + u.username);
            User usr = [select id, name, username from User where username= :u.username LIMIT 1];
            if(usr!=null && usr.username == u.username){
             newUser = usr;
             bIsNewUserFound = true;
             //counter= counter+1;
          }
          return null;
        }catch(Exception ex){
            System.debug('...didnt find user yet...');
            return null;
        }
       }    
       
       //Controller method invoked from the VF page button
       public PageReference createPortaluser()
	   {
			try
			{            
				//Create the Contact associated to the previously created Contact
				Id contactId = createContact(sSystemRequestId);            
				//Since the user is created asynchronously, we want to do some data validation to ensure the proper fields are populated
				if(sSelectedProfileId == null || u.username==null){
					if(sSelectedProfileId==null){
						ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Profile is required: Please select a profile to associate new user');
						ApexPages.addMessage(myMsg);
					}
					if(u.username==null){
					   ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Username is required: Please a username for the new user');
					   ApexPages.addMessage(myMsg);
					}
					return null;
				}
				//Create the User
				//createUser((String)contactId, con.Email, con.FirstName, con.lastname, u.Username, sSelectedProfileId, accessObj.SiteMinder_GUID__c);
				Database.DMLOptions dmo = new Database.DMLOptions();
				dmo.EmailHeader.triggerUserEmail = false;
				dmo.EmailHeader.triggerOtherEmail = false;             
				User u = new User(alias = 'standt', email=con.Email, FederationIdentifier = accessObj.SiteMinder_GUID__c, emailencodingkey='UTF-8', 
									lastname=con.lastname, firstname=con.FirstName, languagelocalekey='en_US', 
									localesidkey='en_CA', profileid = sSelectedProfileId, contactId=(String)contactId,
									timezonesidkey='America/Los_Angeles', username=u.Username, Federation_ID__c = accessObj.SiteMinder_GUID__c);            
				u.setOptions(dmo);
				//sp = Database.setSavepoint();
				insert u;
				
				Portal_User_Counter__c C = Portal_User_Counter__c.getOrgDefaults();
				Portal_User_Counter__c tempC =  new Portal_User_Counter__c( Id = C.id);
				tempC.PortalUserCount__c = counter;
				update tempc;
				//PortalUserCount = Counter.
				System_Access_Request__c accessObj1 = [select Id, Portal_Access_Granted__c  from System_Access_Request__c where id = :sSystemRequestId];
				accessObj1.Portal_Access_Granted__c = system.now();
				Update accessObj1;
				System.debug('User Record Inserted');
				counter= counter+1;
				role = accessObj.User_Credentials_OR_Role_Profession__c;
				if(ApexPages.currentPage() != null)
				{                
					system.debug('----accessObj.Case_Contact__c-----'+accessObj.Case_Contact__c);
					system.debug('----accessObj.Case_Contact__r.Case__c-----'+accessObj.Case_Contact__r.Case__c);
					system.debug('accessObj.SiteMinder_GUID__c'+accessObj.SiteMinder_GUID__c);
					if(accessObj.Case_Contact__r.Case__c != null)
					{                  
						system.debug('----before query-----'+accessObj.Case_Contact__c);
						// Start of change for Defect 176 & 288
						//CaseTeamRole teamRole = [Select Name, Id, AccessLevel From CaseTeamRole where name='Support Team'];
						List<CaseTeamRole> teamRoleList = [Select Name, Id, AccessLevel From CaseTeamRole where name =:role];
						//System.debug('Query1 result; CaseTeamMember Role role:::' + teamRoleList[0].Id + teamRoleList[0].name );
						System.debug('Query1 result; CaseTeamMember Role other:::' + teamRoleList.size());
						if(!teamRoleList.isEmpty()){
							System.debug('Query1 result; CaseTeamMember Role NAME:::' + teamRoleList[0].name );
						}
						if(teamRoleList.isEmpty())
						{
							teamRoleList = [Select Name, Id, AccessLevel From CaseTeamRole where name = 'Other'];
							System.debug('Query2 result; CaseTeamMember Role other:::' + teamRoleList.size());
							//System.debug('Query2 result; CaseTeamMember Role other:::' + teamRoleList[0].Id );
						}
						// End of change for Defect 176 & 288
						//system.debug('----after query-----'+teamRole);
						CaseTeamMember teamMem = new CaseTeamMember ();
						//teamMem.MemberId = '005f0000000iWJn';
						teamMem.MemberId = u.id;
						teamMem.ParentId = accessObj.Case_Contact__r.Case__c;
						//teamMem.TeamRoleId= teamRole.Id;
						if(!teamRoleList.isEmpty())
							teamMem.TeamRoleId = teamRoleList[0].Id;
						System.debug('CaseTeamMember Role:::' + teamMem.TeamRoleId );
						insert teamMem;
						System.debug('CaseTeamMember Record Inserted with Role:::' + teamMem.TeamRoleId );
	
					}
					if(accessObj.Case_Contact__c != null )
					{
						Case_Contact__c refCon = [select id, Contact__c from Case_Contact__c where id= :accessObj.Case_Contact__c];
						refCon.Contact__c = con.Id;
						update refCon;
						accessObj.Status__c = 'Active';
						
						update accessObj;
						
						//ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO, 'successfully created Partner community user and linked it to its respective case 	record');
						//ApexPages.addMessage(myMsg);
					}
					//Select c.TeamTemplateMemberId, c.TeamRoleId,  c.ParentId, c.MemberId, c.Id, c.CreatedDate, c.CreatedById From CaseTeamMember c
					//ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO, 'Successfully created Portal Contact & User records.');
					//ApexPages.addMessage(myMsg);
					//PageReference newpage = new PageReference('/'+u.id);
					//return newpage;
					//isDisabled=true;
				}           
			}catch(Exception ex){
        	system.debug('****Exception****'+ex.getMessage() + ex.getStackTraceString () +  ex.getLineNumber() );
            //Display error message to VF page
            if(ApexPages.currentPage() != null){
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, ex.getMessage()); //+ ex.getStackTraceString () +  ex.getLineNumber() );
                ApexPages.addMessage(myMsg);
            }
            return null;
        }
        PageReference newpage = new PageReference('/'+sSystemRequestId);
        return newpage;
       }
    
    //Method to create the Contact
    public Id createContact(Id sysId){
        Account acc;
        list<Account> listacc = [select id, name from Account where name='All partner portal users'];
        if(listacc.size() > 0){
            acc = listacc[0];
        }
        else{
            acc = new Account ();
            acc.name = 'All partner portal users';
            insert acc;
            System.debug('Account Record Inserted with Name:::' + acc.name );
        }
        if(accessObj!= null){
				/*if(accessObj.First_Name__c == ''|| accessObj.First_Name__c == null ){
					ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO, 'First Name is required field.');
					ApexPages.addMessage(myMsg);
				}
				if(accessObj.Last_Name__c == ''|| accessObj.Last_Name__c == null ){
					ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO, 'Last Name is a required field.');
					ApexPages.addMessage(myMsg);
				}
				if(accessObj.Email__c == ''|| accessObj.Email__c == null ){
					ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO, 'Email is a required field.');
					ApexPages.addMessage(myMsg);
				}*/
            con = new Contact();
            con.LastName = accessObj.Last_Name__c;
            con.FirstName = accessObj.First_Name__c;
            con.Contact_Middle_Name__c = accessObj.Middle_Name_Initial__c;
            con.FirstName = accessObj.First_Name__c;
            con.On_Behalf_Of__c = accessObj.On_Behalf_Of__c;
            con.Contact_Person_Profession_Role__c = accessObj.User_Credentials_OR_Role_Profession__c;
            con.Relationship_to_Individual_if_Other__c = accessObj.Relationship_to_Individual_if_Other__c;
            con.Phone = accessObj.Contact_Phone_Number__c;
            con.Professional_Identifying_Number__c = accessObj.Professional_Identifying_Number__c;                  
            con.Email = accessObj.Email__c;
            con.AccountId = acc.Id;
            con.Region__c = accessObj.EIS_Region__c; //Balaji; update the region field (on the access request) maps over to the newly created contact record
            insert con;
            System.debug('successfully created test contact with Id::::' + con.id);
            return con.id;
        }
        return null;
    }
    

    public List<SelectOption> getCustomerPortalProfiles() {
        //Execute query to get all profiles associated to Partner Community
        Profile[] profiles = [Select p.name, p.id From Profile p where p.UserLicense.Name like '%Partner Community%'];
        List<SelectOption> options = new List<SelectOption>();
        for(Profile p: profiles)
              options.add(new SelectOption(p.id,p.name));
        return options;
    }
    
    public PageReference reset(){
        PageReference newpage = new PageReference('/'+sSystemRequestId);
        //newpage.getParameters().clear();
        newpage.setRedirect(true);
        return newpage;
    }

}