src/objects/Case_Document__c.object
<CustomObject>
    <customHelpPage>Help_Case_Document_VF</customHelpPage>
    <description>Some are restricted, some are collaborative: this object represents all the shared documents on an individual file (assessments, consents ... )</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Documents</relationshipLabel>
        <relationshipName>Case_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assessment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub Category</label>
        <picklist>
            <controllingField>Category__c</controllingField>
            <picklistValues>
                <fullName>Consent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correspondence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health / Safety Reports</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Protocol / Safeguard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFSN - Template</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFSN - Picture Template</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education - IEP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service / Support Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Plans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crisis / Contingency Plans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diagnosis Proof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adaptive Behavioural</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Psychological / Psychiatric</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Therapy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Document</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Case Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Documents</pluralLabel>
    <recordTypes>
        <fullName>Collaborative</fullName>
        <active>true</active>
        <description>Collaborative Case Documents will be shared with all support team members for this individual&apos;s case. Collaborative documents should be relevant to assist others in picture and planning activities.</description>
        <label>Collaborative</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PopulateCaseOnCaseDocHelper_Test.cls
/* Class Name  : PopulateCaseOnCaseDocHelper_Test
 * Description : Test class for an Apex trigger PopulateCaseOnCaseDocHelper 
 * Created By  : Reju Palathingal
 * Created On  : 15-09-2013
 */
@isTest
private class PopulateCaseOnCaseDocHelper_Test {

    static testMethod void PopulateCaseonCD() {
        // TO DO: implement unit test
        
        Case_Document__c ast = new Case_Document__c ();
        ast.Name = 'test';
        ast.Category__c = 'Individual';
        ast.Sub_Category__c = 'Consent';
        List<RecordType> rectype =[Select Id,Name From RecordType Where Name = 'Collaborative' and SobjectType ='Case_Document__c' limit 1];
        ast.RecordTypeId = rectype.get(0).id;
        test.starttest();
        insert ast;      
        
        
        system.assertEquals(ast.Case__c, null);    
        test.stoptest();   
    }
}