src/objects/Case_Alert__c.object
<CustomObject>
    <customHelpPage>Help_CaseAlert</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Alerts</relationshipLabel>
        <relationshipName>Case_Alerts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Normal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Case Alert</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Alerts</pluralLabel>
    <recordTypes>
        <fullName>Collaborative</fullName>
        <active>true</active>
        <description>Collaborative Case Alerts will be shared with all support team members for this individual&apos;s case.</description>
        <label>Collaborative</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CaseAlertCountTrigger_Test.cls
/* Class Name  : CaseAlertCountTrigger_Test
 * Description : Test class for an Apex trigger CaseAlertCountTrigger 
 * Created By  : Silviu Frantescu
 * Created On  : 10-18-2013
*/

@isTest
private class CaseAlertCountTrigger_Test{
    static case cas;
    static Case_Alert__c alert;
    static RecordType recType = [Select Id From RecordType  Where SobjectType = 'Case_Alert__c' and DeveloperName = 'Collaborative'];
    private static testmethod void testData(){
        cas = new case ();
        cas.status = 'New';
        cas.Origin = 'Phone';        
        insert cas;
        alert = new Case_Alert__c();
        alert.name = 'test alert';
        alert.Case__c = cas.id;
        alert.Priority__c = 'High';
        alert.Status__c = 'Open';
        insert alert;
    }
    private static testmethod void testCountMethod(){
        Test.startTest();
        testData();
        alert.RecordTypeId = recType.id;
        update alert;
        Test.stopTest();        
        system.assertEquals(alert.Priority__c, 'High');
    }
}