src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>Details of the Individual referred in the STADD Program</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>filled out by the system (blank until a case is created)</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Individual_Date_of_Birth__c</fullName>
        <description>The birth date of the individual being referred to the program</description>
        <inlineHelpText>Choose in order: day/month/year to complete; any other order will not be accepted by the system</inlineHelpText>
        <label>Individual Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Individual_First_Name__c</fullName>
        <description>The first name of the individual being referred to the STADD program</description>
        <encrypted>true</encrypted>
        <label>Individual First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Individual_Home_Phone_Number__c</fullName>
        <description>The Referral should capture multiple phone numbers for the individual.  This type will capture the type of phone number</description>
        <encrypted>true</encrypted>
        <inlineHelpText>You need to enter at least one phone number</inlineHelpText>
        <label>Individual Home Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Individual_Last_Name__c</fullName>
        <description>The last name of the individual being referred to the STADD program</description>
        <encrypted>true</encrypted>
        <label>Individual Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Address_City__c</fullName>
        <encrypted>true</encrypted>
        <label>Physical Address City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Address_Line_1__c</fullName>
        <description>The address of the physical location where the individual is living</description>
        <encrypted>true</encrypted>
        <label>Physical Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Address_Postal_Code__c</fullName>
        <encrypted>true</encrypted>
        <label>Physical Address Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Case Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Referral Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RejectCaseController_Test.cls
/* Class Name  : RejectCaseController_Test
 * Description : Test class for an Apex class RejectCaseController
 * Created By  : Silviu Frantescu
 * Created On  : 09-30-2013
*/

@isTest
private class RejectCaseController_Test{
    static Referral__c ref;
    static Apexpages.standardcontroller sc;
    static RejectCaseController obj;
    
    private static testmethod void testData(){       
        Case cas = new case ();
        cas.status = 'New';
        cas.Origin = 'Phone';
        insert cas; 
        ref = new Referral__c();
        ref.Case__c = cas.id;
        ref.Status__c = 'Pending';
        ref.Individual_First_Name__c ='Test';
        ref.Individual_Last_Name__c ='User';
        ref.Individual_Date_of_Birth__c = system.today();
        ref.Individual_Home_Phone_Number__c = '1231231';
        ref.Physical_Address_City__c='City';
        ref.Physical_Address_Line_1__c ='12th street';
        ref.Physical_Address_Postal_Code__c='22222';
        ID id1 = userinfo.getUserId();
        insert ref;
      } 
        private static testmethod void rejectControllerTest(){ 
        testdata();
        test.starttest();
        sc = new ApexPages.StandardController(ref);
        ApexPages.currentPage().getParameters().put('id', ref.id); 
        obj = new RejectCaseController(sc);
        obj.RejectCase();
        system.assertNotEquals(obj.record, null); 
        test.stoptest();       
    }
    
    private static testmethod void rejectControllerNegativeTest()	
    { 
	    Profile p = [SELECT Id FROM Profile WHERE Name='STADD Executive']; 
        User Usr = new User(Alias = 'standt', 
                            Email='standarduser@gov.bc.ca', 
        					EmailEncodingKey='UTF-8', 
                            LastName='Testing', 
                            LanguageLocaleKey='en_US', 
        					LocaleSidKey='en_US', 
                            ProfileId = p.Id, 
        					TimeZoneSidKey='America/Los_Angeles', 
                            UserName='standarduser@gov.bc.ca'); 
        insert Usr;
        testdata();
        QueueSObject q=[Select Queue.Id from QueueSObject where Queue.Name = 'Coastal Region'];
        ref.OwnerId = q.Queue.Id; 
        update ref;
        
        test.starttest();
    	
        PageReference pageRef = Page.RejectCase;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc1 = new ApexPages.StandardController(ref);
        ApexPages.currentPage().getParameters().put('id', ref.id); 
        RejectCaseController rej = new RejectCaseController(sc1);
        system.runAs(Usr)
        {     
       		Pagereference ref1 = rej.RejectCase();
            System.assertEquals(null,ref1);
        }
        test.stoptest();          
    }
}