src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>Details of the Individual referred in the STADD Program</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Case Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Sub_Status__c</fullName>
        <label>Status Stage</label>
        <picklist>
            <controllingField>Status__c</controllingField>
            <picklistValues>
                <fullName>Acceptance in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Converted to Case</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual Doesn&apos;t Qualify - Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual Doesn&apos;t Qualify - Outside of Service Area (Location)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual Doesn’t Qualify - Eligibility Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual Doesn’t Qualify - Outside of Program Age Parameters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt-Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Assignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deceased</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Referral Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/RejectCaseController.cls
/*
******************************************************************************************
** ICM STADD Project
*******************************************************************************************
* @Class Name   : RejectCaseController
* @Description  : Created the controller for Reject case button
* @Created By   : Reju Palathingal
* @Created On   : 06/09/2013
* @Modification Log:  
* -----------------------------------------------------------------------------
* @Developer                Date                  Description 
* -----------------------------------------------------------------------------
*                                       
* -----------------------------------------------------------------------------
*/
public class RejectCaseController{
    public Referral__c record {get;set;}
    //Public list<Case> caseReclist {get; set;}
    public Id id{get;set;}
    //Constructor for the page
    public RejectCaseController(ApexPages.StandardController controller) {
         id=  ApexPages.currentPage().getParameters().get('id');
         record =[Select Id,status__c,Sub_Status__c,Ownerid from Referral__c where id =:id];
         if(record != null){
         record.Status__c = 'Rejected';
         //record.Sub_Status__c = 'Duplicate';
         }
    }
    // Logic for reject 
    public pagereference RejectCase(){
        Id recordId = System.currentPagereference().getParameters().get('id');  
        List<Referral__c> ref = [Select Id,OwnerId,status__c,Sub_Status__c from Referral__c where id =:recordId];
        String own;
        If(!ref.isEmpty())
        own = ref[0].OwnerId;
        Profile PR = [select Name from Profile where id =:userinfo.getProfileId()];
        if (own!=null && own.startsWith('00G') && PR.Name != 'STADD Coordinator') 
            {
                 ApexPages.addMessage ( new ApexPages.Message(ApexPages.Severity.ERROR, 'Please make sure the referral has been assigned to a navigator before accepting/rejecting it; only navigators who own the referral can accept/reject'));
                 return null;
            }
        //List<User> portaluser = [SELECT Id, Name, IsPortalEnabled, UserType FROM User WHERE Id=:userinfo.getUserId() LIMIT 1];
        //userinfo.getProfileId();
        if (PR.Name == 'STADD Navigator' )
        {
            ID id1 = userinfo.getUserId();
            if(id1 != ref[0].OwnerId)
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please make sure the referral has been assigned to a navigator before accepting/rejecting it; only navigators who own the referral can accept/reject'));
                return null;
            }
        }
        if(record != null){
        update record;
        //PageReference casPage = new PageReference('/' + record[0].Id);
        PageReference casPage = new PageReference('/' + record.Id);
        casPage.setRedirect(true);
        return casPage;
        }
        else{
            return null;
        }        
    }
}