src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact_is_Individual_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Cannot be checked if individual has a legal authority</inlineHelpText>
        <label>Primary Contact is Individual Indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <businessProcess>Standard</businessProcess>
        <description>A Standard Case Record means that the individual’s case is visible to any support team users.</description>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Contact__c.object
<CustomObject>
    <description>Contact details of the  Individual referred in STADD Program.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Referral_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Person_Last_Name__c</fullName>
        <encrypted>true</encrypted>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Postal_Code__c</fullName>
        <encrypted>true</encrypted>
        <label>Mailing Address Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Province__c</fullName>
        <label>Mailing Address Province</label>
        <picklist>
            <picklistValues>
                <fullName>BC</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Case Contacts</relationshipLabel>
        <relationshipName>Referral_Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Contact</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Case Contact Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Mapping_object__c.object
<CustomObject>
    <fields>
        <fullName>Context_prompt__c</fullName>
        <label>Context prompt</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Functional_Domain_Type__c</fullName>
        <label>Functional Domain Type</label>
        <picklist>
            <picklistValues>
                <fullName>Physical Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Living Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Participation Skills and Social Inclusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Interaction and Self-Determination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Styles and Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language and Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reason and Decision-Making</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioral and Emotional Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health: Diagnostic Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Space Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReferralPage1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReferralPage2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReferralPage3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FunctionalDomainPage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PortalUserRegistration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Mapping object</label>
    <nameField>
        <displayFormat>Map-{0000}</displayFormat>
        <label>Mapping object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapping objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>Details of the Individual referred in the STADD Program</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>filled out by the system (blank until a case is created)</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EIS_Location__c</fullName>
        <description>The EIS Office Locations will be the names of the 5 regional offices</description>
        <label>Location</label>
        <picklist>
            <controllingField>EIS_Region__c</controllingField>
            <picklistValues>
                <fullName>Abbotsford</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bulkley / Stikine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burnaby</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campbell River</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cariboo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chilliwack</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>City Centre</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comox Valley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Downtown Eastside</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East Kootenay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraser / Cascades</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold Trail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haida Gwaii / Prince Rupert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kamloops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Langley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nanaimo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nechako Lakes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Westminster</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parksville / Qualicum</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Peace North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prince George</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quesnel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ridge Meadows</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Okanagan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Surrey East</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Surrey North</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Surrey South</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tri-Cities</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>EIS_Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Northern Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraser Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vancouver Island Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vancouver Coastal Region</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Individual_Date_of_Birth__c</fullName>
        <description>The birth date of the individual being referred to the program</description>
        <inlineHelpText>Choose in order: day/month/year to complete; any other order will not be accepted by the system</inlineHelpText>
        <label>Individual Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Individual_First_Name__c</fullName>
        <description>The first name of the individual being referred to the STADD program</description>
        <encrypted>true</encrypted>
        <label>Individual First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Individual_Home_Phone_Number__c</fullName>
        <description>The Referral should capture multiple phone numbers for the individual.  This type will capture the type of phone number</description>
        <encrypted>true</encrypted>
        <inlineHelpText>You need to enter at least one phone number</inlineHelpText>
        <label>Individual Home Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Individual_Last_Name__c</fullName>
        <description>The last name of the individual being referred to the STADD program</description>
        <encrypted>true</encrypted>
        <label>Individual Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Line_1__c</fullName>
        <encrypted>true</encrypted>
        <label>Mailing Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Line_2__c</fullName>
        <encrypted>true</encrypted>
        <label>Mailing Address Line 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Postal_Code__c</fullName>
        <encrypted>true</encrypted>
        <label>Mailing Address Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_Province__c</fullName>
        <label>Mailing Address Province</label>
        <picklist>
            <picklistValues>
                <fullName>BC</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Physical_Address_City__c</fullName>
        <encrypted>true</encrypted>
        <label>Physical Address City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Address_Line_1__c</fullName>
        <description>The address of the physical location where the individual is living</description>
        <encrypted>true</encrypted>
        <label>Physical Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Address_Postal_Code__c</fullName>
        <encrypted>true</encrypted>
        <label>Physical Address Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_Is_Individual_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Cannot be used if the Rep/ Guardian/Committee indicator  is used</description>
        <inlineHelpText>Cannot be checked if Individual has a legal authority</inlineHelpText>
        <label>Individual is Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Case Created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Referral Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <recordTypes>
        <fullName>Standard</fullName>
        <active>true</active>
        <label>Standard</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/newCaseController_Test.cls
/* Class Name  : newCaseController_Test
 * Description : Test class for an Apex class newCaseController  
 * Created By  : Silviu Frantescu
 * Created On  : 09-30-2013
*/

@isTest
private class newCaseController_Test{
    static case cas;
    static Referral__c ref;
    static Mapping_object__c mapobj;
    static Mapping_object__c mapobj1;
    static Mapping_object__c mapobj2;
    static Case_contact__c refcon;
    
    private static testmethod void testdata(){
        cas = new case ();
        cas.status = 'New';
        cas.Origin = 'Phone';
        insert cas; 
        ref = new Referral__c();
        refcon = new Case_contact__c ();
        ref.Case__c = cas.id;
        ref.Status__c = 'Pending';
        ref.Individual_First_Name__c ='Test';
        ref.Individual_Last_Name__c ='User';
        ref.Individual_Date_of_Birth__c = system.today();
        ref.Individual_Home_Phone_Number__c = '1234567890';
        ref.Physical_Address_City__c='City';
        ref.Physical_Address_Line_1__c ='12th street';
        ref.Physical_Address_Postal_Code__c='V1V1V1';
        ref.Mailing_Address_Line_1__c='line1';
        ref.Mailing_Address_Line_2__c='Line2';
        ref.Mailing_Address_Postal_Code__c ='Code';
        ref.Mailing_Address_Province__c='Province';
        ref.Individual_Date_of_Birth__c= system.today();
        ref.Primary_Contact_Is_Individual_Indicator__c = true;
        ref.EIS_Region__c = 'Northern Region';
        ref.EIS_Location__c = 'Prince George / Haida Gwaii';
        insert ref;
        mapobj= new Mapping_object__c();
        mapobj.Functional_Domain_Type__c = 'ReferralPage2';
        mapobj.Context_prompt__c = 'Test';
        
        mapobj1= new Mapping_object__c();
        mapobj1.Functional_Domain_Type__c = 'ReferralPage1';
        mapobj1.Context_prompt__c = 'Test';       
        mapobj2= new Mapping_object__c();
        mapobj2.Functional_Domain_Type__c = 'ReferralPage3';
        mapobj2.Context_prompt__c = 'Test';
        insert mapobj;
        insert mapobj1;
        insert mapobj2;
        
        system.assertNotEquals(ref, null);
        
        /*refcon.Contact_Person_Last_Name__c = 'Test';
        refcon.Contact_Person_Last_Name__c = 'Test';
        refcon.Relationship_Subtype__c = 'Other';
        refcon.Contact_Person_Work_Phone_Number__c = '1234567890';
        refcon.Contact_Person_Home_Phone_Number__c = '1456789876';
        refcon.Contact_Person_Cell_Phone_Number__c = '6753289765';
        insert refcon;*/
         
    }
    private static testmethod void controllerTest(){  
        test.starttest();
        testdata();
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        ApexPages.currentPage().getParameters().put('id', ref.id);
        ApexPages.currentPage().getParameters().put('name', ref.id);
        newCaseController obj = new newCaseController(sc);
        obj.fetchId();
        obj.step1();
        obj.step2();
        obj.step3();
        obj.save();
        test.stoptest();
     }
     private static testmethod void controllerTestFirstName(){  
        test.starttest();
        testdata();
        ref.Individual_First_Name__c ='';
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        ApexPages.currentPage().getParameters().put('id', ref.id);
        ApexPages.currentPage().getParameters().put('name', ref.id);
        newCaseController obj = new newCaseController(sc);
        obj.fetchId();
        obj.step1();
        obj.step2();
        obj.step3();
        obj.save();
        test.stoptest();
     }
     private static testmethod void controllerTestLastName(){  
        test.starttest();
        testdata();
        ref.Individual_Last_Name__c ='';
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        ApexPages.currentPage().getParameters().put('id', ref.id);
        ApexPages.currentPage().getParameters().put('name', ref.id);
        newCaseController obj = new newCaseController(sc);
        obj.fetchId();
        obj.step1();
        obj.step2();
        obj.step3();
        obj.save();
        test.stoptest();
     }    
     private static testmethod void controllerTestAddr(){ 
        test.starttest();
        testdata();
        ref.Physical_Address_City__c='';
        ref.Physical_Address_Line_1__c ='';
        ref.Physical_Address_Postal_Code__c='';
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        ApexPages.currentPage().getParameters().put('id', ref.id);
        ApexPages.currentPage().getParameters().put('name', ref.id);
        newCaseController obj = new newCaseController(sc);
        obj.fetchId();
        obj.step1();
        obj.step2();
        obj.step3();
        obj.save();
        test.stoptest();
     }    
     private static testmethod void controllerTestAddr1(){ 
        test.starttest();
        testdata();
        ref.Mailing_Address_Line_1__c='ad';
        ref.Mailing_Address_Line_2__c='';
        ref.Mailing_Address_Postal_Code__c ='';
        ref.Mailing_Address_Province__c='';
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        ApexPages.currentPage().getParameters().put('id', ref.id);
        ApexPages.currentPage().getParameters().put('name', ref.id);
        newCaseController obj = new newCaseController(sc);
        obj.fetchId();
        obj.step1();
        obj.step2();
        obj.step3();
        obj.save();
        test.stoptest();
     }
     private static testmethod void controllerTestNoPhone(){ 
        test.starttest();
        testdata();
        ref.Individual_Work_Phone_Number__c='';
        ref.Individual_Cell_Phone_Number__c='';
        ref.Individual_Home_Phone_Number__c ='';
        ref.Individual_Email_Address__c='';
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        ApexPages.currentPage().getParameters().put('id', ref.id);
        ApexPages.currentPage().getParameters().put('name', ref.id);
        newCaseController obj = new newCaseController(sc);
        obj.fetchId();
        obj.step1();
        obj.step2();
        obj.step3();
        obj.save();
        test.stoptest();
     }
    private static testmethod void controllerBirthdayTest(){  
        test.starttest();
        testdata();
        ref.Individual_Date_of_Birth__c= date.today().addyears(-99); 
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        ApexPages.currentPage().getParameters().put('id', ref.id);
        ApexPages.currentPage().getParameters().put('name', ref.id);
        newCaseController obj = new newCaseController(sc);
        obj.fetchId();
        obj.step1();
        obj.step2();
        obj.step3();
        obj.save();
        test.stoptest();
     }     
       
       

    private static testmethod void controllerBirthdayTest1(){  
        test.starttest();
        testdata();
        
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        ApexPages.currentPage().getParameters().put('id', ref.id);
        ApexPages.currentPage().getParameters().put('name', ref.id);
        newCaseController obj = new newCaseController(sc);
        obj.fetchId();
        obj.step1();
        obj.step2();
        obj.step3();
        obj.save();
        test.stoptest();
    }
             
     private static testmethod void controllerNotNullObjTest(){  
        test.starttest();
        testdata();
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        newCaseController obj = new newCaseController(sc);        
        newCaseController.phoneError(ref);
        obj.ref.Primary_Contact_Is_Individual_Indicator__c = true;
        obj.ref.Has_legal_authority__c = true;
        obj.step3();
        test.stoptest();
     }
     private static testmethod void step3Test(){  
        test.starttest();
        testdata();
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        newCaseController obj = new newCaseController(sc);
        ref.Individual_Home_Phone_Number__c = null;
        ref.Individual_Cell_Phone_Number__c = null;
        ref.Individual_Work_Phone_Number__c = null;
        newCaseController.phoneError(ref);
        newCaseController.mailAddressError(null);
        obj.ref.Primary_Contact_Is_Individual_Indicator__c = null;
        obj.refcon = new case_contact__c ();
        obj.refcon.Contact_Person_Last_Name__c = 'test';
        obj.refcon.Contact_Person_First_Name__c = 'test';
        obj.refcon.Contact_Person_Home_Phone_Number__c = '12345';
        obj.refcon.Contact_Person_Work_Phone_Number__c  = '3456';
        obj.refcon.Contact_Person_Cell_Phone_Number__c  = '98763';
        obj.refcon.Relationship_Subtype__c = 'test';
        obj.step3();
        test.stoptest();        
        system.assertNotEquals(obj.refcon, null);
     }
     
     private static testmethod void step3TestForFirstName(){  
        test.starttest();
        testdata();
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        newCaseController obj = new newCaseController(sc);
        newCaseController.phoneError(ref);
        newCaseController.mailAddressError(null);
        obj.ref.Primary_Contact_Is_Individual_Indicator__c = false;
        obj.refcon = new case_contact__c ();
        obj.refcon.Contact_Person_Last_Name__c = 'test';
        obj.refcon.Contact_Person_First_Name__c = null;
        obj.refcon.Contact_Person_Home_Phone_Number__c = '12345';
        obj.refcon.Contact_Person_Work_Phone_Number__c  = '3456';
        obj.refcon.Contact_Person_Cell_Phone_Number__c  = '98763';
        obj.refcon.Relationship_Subtype__c = 'test';
        obj.step3();
        obj.refcon.Contact_Person_First_Name__c = 'test';
        obj.refcon.Relationship_Subtype__c = null;
        obj.step3();
        obj.refcon.Relationship_Subtype__c = 'test';
        obj.refcon.Contact_Person_Home_Phone_Number__c = null;
        obj.refcon.Contact_Person_Work_Phone_Number__c  = null;
        obj.refcon.Contact_Person_Cell_Phone_Number__c  = null;
        obj.step3();
        test.stoptest();        
        system.assertNotEquals(obj.refcon, null);
     }
     
     private static testmethod void step3TestForLastName(){  
        test.starttest();
        testdata();
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        newCaseController obj = new newCaseController(sc);
        ref.Individual_Home_Phone_Number__c = null;
        ref.Individual_Cell_Phone_Number__c = null;
        ref.Individual_Work_Phone_Number__c = null;
        newCaseController.phoneError(ref);
        newCaseController.mailAddressError(null);
        obj.ref.Primary_Contact_Is_Individual_Indicator__c = null;
        obj.refcon = new case_contact__c ();
        obj.refcon.Contact_Person_Last_Name__c = '';
        obj.refcon.Contact_Person_First_Name__c = 'test';
        obj.refcon.Contact_Person_Home_Phone_Number__c = '12345';
        obj.refcon.Contact_Person_Work_Phone_Number__c  = '3456';
        obj.refcon.Contact_Person_Cell_Phone_Number__c  = '98763';
        obj.refcon.Relationship_Subtype__c = 'test';
        obj.step3();
        test.stoptest();        
        system.assertNotEquals(obj.refcon, null);
        system.assertNotEquals(obj.refcon, null);
     }     
     private static testmethod void step3TestForPhone(){  
        test.starttest();
        testdata();
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        newCaseController obj = new newCaseController(sc);
        ref.Individual_Home_Phone_Number__c = null;
        ref.Individual_Cell_Phone_Number__c = null;
        ref.Individual_Work_Phone_Number__c = null;
        newCaseController.phoneError(ref);
        newCaseController.mailAddressError(null);
        obj.ref.Primary_Contact_Is_Individual_Indicator__c = null;
        obj.refcon = new case_contact__c ();
        obj.refcon.Contact_Person_Last_Name__c = '';
        obj.refcon.Contact_Person_First_Name__c = 'test';
        obj.refcon.Contact_Person_Home_Phone_Number__c = '';
        obj.refcon.Contact_Person_Work_Phone_Number__c  = '';
        obj.refcon.Contact_Person_Cell_Phone_Number__c  = '';
        obj.refcon.Relationship_Subtype__c = 'Other';
        obj.step3();
        test.stoptest();        
        system.assertNotEquals(obj.refcon, null);
        system.assertNotEquals(obj.refcon, null);
     }     
      private static testmethod void saveTest(){  
        test.starttest();
        testdata();
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        newCaseController obj = new newCaseController(sc);
        obj.ref = new Referral__c();
        obj.ref.Case__c = cas.id;
        obj.ref.Status__c = 'Pending';
        obj.ref.Individual_First_Name__c ='Test';
        obj.ref.Individual_Last_Name__c ='User';
        obj.ref.Individual_Date_of_Birth__c = system.today();
        obj.ref.Individual_Home_Phone_Number__c = '1231231';
        obj.ref.Physical_Address_City__c='City';
        obj.ref.Physical_Address_Line_1__c ='12th street';
        obj.ref.Physical_Address_Postal_Code__c='22222';
        obj.ref.Is_the_Individual_Attending_School_Indic__c = true;
        obj.socon.Contact_Person_First_Name__c = 'test';
        obj.socon.Contact_Person_Last_Name__c = 'test';
        obj.ref.Is_the_individual_being_supported_by_CFD__c = true;
        obj.cfdcon.Contact_Person_First_Name__c = 'test';
        obj.cfdcon.Contact_Person_Last_Name__c = 'test';
        obj.ref.Is_the_Individual_eligible_for_CLBC_Serv__c = true;
        obj.clbccon.Contact_Person_First_Name__c = 'test';
        obj.clbccon.Contact_Person_Last_Name__c = 'test'; 
        obj.vDocument.Name = 'test'; 
        obj.vDocument.Body = Blob.valueof('test');
        obj.vDocument2.Name = 'test2'; 
        obj.vDocument2.Body = Blob.valueof('test');    
        obj.save();        
        test.stoptest();
        system.assertNotEquals(obj.vDocument, null);
        system.assertNotEquals(obj.vDocument2, null);
     }
     private static testmethod void controllerNullObjTest(){  
        test.starttest();
        testdata();
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        newCaseController obj = new newCaseController(sc);
        newCaseController.phoneError(null);
        obj.ref.Individual_Home_Phone_Number__c = '123';
        obj.ref.Individual_Cell_Phone_Number__c = '1234';
        obj.ref.Individual_Work_Phone_Number__c = '345';
        newCaseController.phoneError(obj.ref);
        obj.ref.Mailing_Address_same_as_Physical_Address__c = true;
        obj.ref.Mailing_Address_Line_1__c = 'address1';
        obj.ref.Mailing_Address_City__c = 'address mailing';
        obj.ref.Mailing_Address_Postal_Code__c = '12345';
        newCaseController.mailAddressError(obj.ref);
        test.stoptest();
     }
     
     private static testmethod void methodsTest(){  
        test.starttest();
        testdata();
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        newCaseController obj = new newCaseController(sc);
        obj.ref.Individual_Date_of_Birth__c = system.today().addYears(20);
        //obj.getRelationships();
        obj.refcon.Relationship_Subtype__c = 'Other';
        obj.ref.Individual_Date_of_Birth__c = system.today().addYears(-20);
        //obj.getRelationships();
        obj.refcon.Relationship_Subtype__c ='Parent';
        obj.addcontact();
        obj.updatefield();
        obj.updatefield1();
        obj.contactlist = new list<Case_Contact__c>();
        obj.contactlist.add(refcon);
        obj.addcontact();
        Case_Contact__c casCon2 = new Case_Contact__c();
        obj.contactlist.add(casCon2);
        obj.addcontact();
        obj.numberOfRowToRemove = 1;
        obj.removecontact();
        Case_Contact__c casCon3 = new Case_Contact__c();
        obj.contactlist.add(casCon3);
         obj.addcontact();
        Case_Contact__c casCon4 = new Case_Contact__c();
        obj.contactlist.add(casCon4);
        obj.addcontact();
        Case_Contact__c casCon5 = new Case_Contact__c();
        casCon5.Contact_Person_First_Name__c = 'fName';
        casCon5.Contact_Person_Last_Name__c = 'lName';
        casCon5.Relationship_Subtype__c = 'Other';
        casCon5.Other_Relationship__c ='person';
        obj.contactlist.add(casCon5);
        obj.addcontact();
        obj.vDocument.Name = 'test'; 
        obj.vDocument.Body = Blob.valueof('test');
        obj.vDocument2.Name = 'test2'; 
        obj.vDocument2.Body = Blob.valueof('test');    
        obj.save();
        obj.ref.Primary_Contact_Is_Individual_Indicator__c = true;
        obj.step3();
        test.stoptest();
     }
         
     private static testmethod void runAsTest(){  
        test.starttest();
        testdata();
        ApexPages.StandardController sc = new ApexPages.StandardController(ref);
        newCaseController obj = new newCaseController(sc);
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@gov.bc.ca', EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@testorg.com.testUser');         
        System.runAs(u) 
        {
          //  PageReference pg = obj.save();
        //    system.assertequals(pg , null);
        }
        test.stoptest();
     }
     
 }