src/objects/Case_Document__c.object
<CustomObject>
    <customHelpPage>Help_Case_Document_VF</customHelpPage>
    <description>Some are restricted, some are collaborative: this object represents all the shared documents on an individual file (assessments, consents ... )</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Documents</relationshipLabel>
        <relationshipName>Case_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Protocols_and_Safeguards__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Protocols and Safeguards</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Protocols_and_Safeguards__c.Case__c</field>
                <operation>equals</operation>
                <valueField>$Source.Case__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Protocols_and_Safeguards__c</referenceTo>
        <relationshipLabel>Case Documents</relationshipLabel>
        <relationshipName>Case_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Document</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Case Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Protocols_and_Safeguards__c.object
<CustomObject>
    <customHelpPage>Help_Protocol_and_Safeguards_VF</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Protocols and Safeguards</relationshipLabel>
        <relationshipName>Protocols_and_Safeguards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Protocols and Safeguards</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Protocol/Safeguard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Protocols and Safeguards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PopulateCaseOnCaseDocHelper.cls
/* @Trigger Name : PopulateCaseOnCaseDocHelper 
 * @Description  : This class is a helper class for the Case Document trigger
 * @Created By   : Reju Palathingal 
 * @Created On   : 10/03/2013
 * @Modification Log:  
 * -----------------------------------------------------------------------------
 * @Developer                Date                  Description 
 * -----------------------------------------------------------------------------
 * @Reju Palathingal         10/03/2013                Created
 * 
 * -----------------------------------------------------------------------------
 */
public with sharing class PopulateCaseOnCaseDocHelper {
	
	public static Set<id>parentIds = new Set<id>();
	public static void manageInsertCase(List<Case_Document__c> newTriggerList)
	{
	
	    for(Case_Document__c ast :newTriggerList)
	    {
	        parentIds.add(ast.Protocols_and_Safeguards__c);
	    }
	    Map<id,Protocols_and_Safeguards__c> pro = new Map<id,Protocols_and_Safeguards__c>([select id, Case__c from Protocols_and_Safeguards__c where id in :parentIds]);
	    
	    for(Case_Document__c astlst :newTriggerList)
	    {
	        
	        	if(pro.containsKey(astlst.Protocols_and_Safeguards__c))
	        	{
	        		      	
	           		astlst.Case__c = pro.get(astlst.Protocols_and_Safeguards__c).Case__c;
	        	}	
	        
	    }
	    
	}
}