src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region</description>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Northern Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraser Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interior Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vancouver Island Region</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vancouver Coastal Region</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Plan__c.object
<CustomObject>
    <description>A plan developed by the individual to meet certain goals.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Status__c</fullName>
        <label>Plan Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Place/ Signed-off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Support Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contingency Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crisis Plan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Goal__c.object
<CustomObject>
    <customHelpPage>Help_PlanGoals</customHelpPage>
    <description>Goals comprise the plan.</description>
    <fields>
        <fullName>Goal_Type__c</fullName>
        <inlineHelpText>If goal type is &quot;Other&quot;, please enter an unique description in &quot;Goal Name&quot;.</inlineHelpText>
        <label>Goal Type</label>
        <picklist>
            <picklistValues>
                <fullName>Positive Relationships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safety in My Home &amp; Community</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Connections</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decision-making Agreements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health &amp; Wellness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <description>Plan</description>
        <inlineHelpText>Plan</inlineHelpText>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Plan Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan Goal</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Goal Name (If Goal Type is &apos;Other&apos;)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Plan_Milestone__c.object
<CustomObject>
    <customHelpPage>Help_Milestone_VF</customHelpPage>
    <fields>
        <fullName>Plan_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Goal</description>
        <inlineHelpText>Goal</inlineHelpText>
        <label>Plan Goal</label>
        <referenceTo>Plan_Goal__c</referenceTo>
        <relationshipLabel>Plan Milestones</relationshipLabel>
        <relationshipName>Plan_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Plan Milestones</relationshipLabel>
        <relationshipName>Plan_Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Future Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan Milestone</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Support_and_Service__c.object
<CustomObject>
    <customHelpPage>Help_Supports_and_services</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipName>Support_and_Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <encrypted>true</encrypted>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Service_Support_Type__c</fullName>
        <encrypted>true</encrypted>
        <label>Service / Support Type</label>
        <type>TextArea</type>
    </fields>
    <label>Support and Service</label>
    <nameField>
        <displayFormat>SSL-{0000}</displayFormat>
        <label>Supports and Services Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supports and Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SendEmailAndUpdateGoalType_Test.cls
/** ICM STADD Project Enhancements
*******************************************************************************************
** Class Name: SendEmailAndUpdateGoalType_Test.cls
** Description: Test class which includes the test class coverage for SendEmailToCaseTeam class and Update Goal Type trigger
** Version: 1.0
** 
**-----------------------------------------------------------------------------------------
**Modification Log:
**----------------
**Developer                  Date          Version               Description
**-----------------------------------------------------------------------------------------
**sanjoy Joseph          1/16/2016         1.0                   Created** 

********************************************************************************************/
@isTest
private class SendEmailAndUpdateGoalType_Test {
 
    @isTest static void TestFunction() {
       
        //insert case object and case team members
        
       insert new Case(Subject = 'testCase',Description = 'Test',Region__c = 'Northern Region', Status = 'Picture');
       User testUser = new User(); 
       testUser.FirstName = 'TestFname';
       testUser.LastName  = 'TestLname';
       testUser.Email     = 'samplemail@gov.bc.ca';
       testUser.Username  = 'samplemail@gov.bc.ca';
       testUser.Alias     = 'test';
       profile p = [SELECT id,Name FROM Profile WHERE Name = 'System Administrator'];
       testUser.ProfileId = p.id;
       testUser.TimeZoneSidKey    = 'America/Denver';
       testUser.LocaleSidKey      = 'en_US';
       testUser.EmailEncodingKey  = 'UTF-8';
       testUser.LanguageLocaleKey = 'en_US';  
       insert testUser;    
       CaseTeamRole role = [Select ID from CaseTeamRole LIMIT 1];
       Case caseinstance=[SELECT Id FROM Case WHERE Subject = 'testCase' LIMIT 1];
       User userinstance=[SELECT Id FROM User WHERE FirstName = 'TestFname' LIMIT 1];
       insert new CaseTeamMember(ParentID = caseinstance.ID, MemberID = userinstance.ID, TeamRoleID = role.ID);  
        
        //insert child object record
        insert new Plan__c(Name = 'test123',Plan_Type__c = 'Crisis Plan',Plan_Status__c = 'Draft In Progress', Case__c = caseinstance.Id);
        Plan__c planinstance=[SELECT Id FROM Plan__c WHERE Name = 'test123' LIMIT 1];
        insert new  Support_and_Service__c(Service_Support_Type__c = 'SST',Notes__c = 'notes_ss',Case__c = caseinstance.Id);
        Support_and_Service__c childinstance1=[SELECT Id FROM Support_and_Service__c WHERE Service_Support_Type__c = 'SST' LIMIT 1];
        insert new Plan_Goal__c(Name = 'testgoal',Status__c = 'Active',Plan__c = planinstance.Id);
        Plan_Goal__c childinstance2=[SELECT Id FROM Plan_Goal__c WHERE Name = 'testgoal' LIMIT 1];
        insert new Plan_Milestone__c(Name = 'testmilestone',Status__c = 'Active',Plan__c = planinstance.Id,Plan_Goal__c=childinstance2.id);
        Plan_Milestone__c childinstance3=[SELECT Id FROM Plan_Milestone__c WHERE Name = 'testmilestone' LIMIT 1];
        
        //test the SendEmailToCaseTeam apex class
        SendEmailToCaseTeam.SendEmail (caseinstance.Id,childinstance1.Id);
        SendEmailToCaseTeam.SendEmail (caseinstance.Id,childinstance2.Id);
        SendEmailToCaseTeam.SendEmail (caseinstance.Id,childinstance3.Id);
        //test the Update_Gol_Type trigger
        insert new Plan_Goal__c(Name = '*',Goal_Type__c = 'Positive Relationships',Status__c = 'Active',Plan__c = planinstance.Id);
        Plan_Goal__c childinstance4=[SELECT Id,Name,Goal_Type__c FROM Plan_Goal__c WHERE Name = 'Positive Relationships' LIMIT 1];
        system.assertEquals(childinstance4.Name, childinstance4.Goal_Type__c);    
        
    }}