src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Document__c.object
<CustomObject>
    <customHelpPage>Help_Case_Document_VF</customHelpPage>
    <description>Some are restricted, some are collaborative: this object represents all the shared documents on an individual file (assessments, consents ... )</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Documents</relationshipLabel>
        <relationshipName>Case_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Documents</relationshipLabel>
        <relationshipName>Case_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Document</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Case Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Social Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLBC Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nurse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Therapist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/File_Download_Audit__c.object
<CustomObject>
    <fields>
        <fullName>Case_Document_Name__c</fullName>
        <description>Stores Case Document Name</description>
        <encrypted>true</encrypted>
        <label>Case Document Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Number__c</fullName>
        <description>Store the case number</description>
        <label>Case Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>File_name__c</fullName>
        <description>Stores File name</description>
        <encrypted>true</encrypted>
        <label>Title / File name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Date_of_Download__c</fullName>
        <label>Time / Date of Download</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>stores type of the file</description>
        <label>Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <description>Stores user name</description>
        <encrypted>true</encrypted>
        <label>User Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Profile__c</fullName>
        <description>Store users profile</description>
        <label>User Profile</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>File Download Audit</label>
    <nameField>
        <displayFormat>FD-{00000}</displayFormat>
        <label>File Download Audit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Files Download Audit</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>Details of the Individual referred in the STADD Program</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>filled out by the system (blank until a case is created)</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Referral Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/NotesAndAttachmentsContoller.cls
/******************************************************************************************
** ICM STADD Project
*******************************************************************************************
** Class Name: Case Documents sharing
** Description: Sharing Case documents records ,if the community user has access to Case or the Referral associated.
** Version: 1.0
** 
**-----------------------------------------------------------------------------------------
**Modification Log:
**----------------
**Developer                  Date          Version               Description
**-----------------------------------------------------------------------------------------
**Reju Palathingal           2/5/2014         1.0                   Created** 

********************************************************************************************/
public without sharing class NotesAndAttachmentsContoller {

public List<Case_Document__c> casrecord{get; set;}
public List<UserRecordAccess> caids{get; set;}
public List<UserRecordAccess> refids{get; set;}
public Id id{get;set;}
public Boolean rend{get; set;}
public List<Id> lstcasid;
public List<Id> lstrefid;
public string caccess;
public string racccess; 
public string DocId {get; set;}
public List<Profile> userprofile{get; set;}
public List<Attachment> att{get; set;}
public List<Case> Caselist{get; set;}
    
    public NotesAndAttachmentsContoller(ApexPages.StandardController controller) 
    {
        id=  ApexPages.currentPage().getParameters().get('id'); 
        casrecord = [select id,Referral__c,Case__c from Case_Document__c where id =: id limit 1];
        string cid= casrecord[0].Case__c;
        string rid= casrecord[0].Referral__c;   
        system.debug(cid);
        system.debug(rid);
        string userid = Userinfo.getUserId();
        
        List<User> usr = [Select Id, Username, UserType, ProfileId  FROM User where Id =: userid];
        string usrtype = usr[0].UserType;
        
        if(usrtype == 'PowerPartner')
            
        {
        
            //String strQuery = 'SELECT RecordId, HasEditAccess FROM UserRecordAccess WHERE UserId = \''+ string.escapeSingleQuotes(userid) + '\' AND ';
            if(cid != null || cid != '')
            {
                caids = [SELECT RecordId, HasAllAccess, HasEditAccess,MaxAccessLevel FROM UserRecordAccess WHERE UserId =: userid AND RecordId =:casrecord[0].Case__c];
                //strQuery = strQuery + ' (RecordID = \'' + string.escapeSingleQuotes(casid) + '\'';                
            }
            
            if(rid != null || rid != '')
            {
                refids = [SELECT RecordId, HasAllAccess,HasEditAccess,MaxAccessLevel FROM UserRecordAccess WHERE UserId =: userid AND RecordID =:casrecord[0].Referral__c];         

            }
            system.debug(caids);
            system.debug(refids);
            //system.debug(caids.size());
            //system.debug(refids[0].MaxAccessLevel);
            //List<UserRecordAccess> listUserAccessRecord = database.query(strQuery);
            if(!caids.isempty())
            {
                 caccess = caids[0].MaxAccessLevel;
            }
            
            if(!refids.isempty())
            {
                 racccess = refids[0].MaxAccessLevel;
            }
            system.debug(caccess);
            system.debug(racccess);
        
            if((caccess == 'NONE' || caccess == null) && (racccess == null || racccess == 'NONE' ))
            //if(listUserAccessRecord.Isempty()) 
            {
                //system.debug('Entered ELSE');
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Insufficient Privileges: You do not have access to this record.'));
                rend=false;
                
            }
            else 
            {
                //system.debug('Entered if');
                rend=true;
            }   
        }
        else
        {
            rend=true;
        }
    }
    
 public PageReference fnAuditUserDetails(){
    	
    try{
        
        if(DocId != null)
        {
         string sProfileName;
         string sProfileId;
         string sCaseDocId;
         string sCaseDocName;
         string sAttName;
         string sCaseNum;
         string sCaseId;
         System.debug('*******************DocId: ' + DocId);
        
         sProfileId = UserInfo.getProfileId();           
         if(sProfileId != null){
        	 userprofile = [Select Name from Profile where Id =:sProfileId limit 1];
         	if(!userprofile.isEmpty())
         		 sProfileName = userprofile[0].Name;
         }
                  
         sCaseDocId = Apexpages.currentPage().getParameters().get('Id');           
         if(sCaseDocId != null){
         	casrecord = [select Name, Case__c from Case_Document__c where id =: sCaseDocId limit 1];
         	if(!casrecord.isEmpty()){
         		sCaseDocName = casrecord[0].Name;
         		sCaseId = casrecord[0].Case__c;
         		if(sCaseId != null){
         		 Caselist = [select CaseNumber from Case where id =: sCaseId limit 1];
         		 	if(!Caselist.isEmpty())
         			 sCaseNum = Caselist[0].CaseNumber;
         		   }
         		}
           	}
         
		att = [select Name, ContentType from Attachment where id =:DocId limit 1];
		if(!att.isEmpty())
			sAttName = att[0].Name;

        File_Download_Audit__c  DFAObj = new File_Download_Audit__c();
        
        DFAObj.Case_Document_Name__c = sCaseDocName;
        DFAObj.Time_Date_of_Download__c = System.now();
        DFAObj.File_name__c = sAttName;
        DFAObj.Type__c= 'Attachment';
        DFAObj.User_Name__c = UserInfo.getFirstName() +' '+ UserInfo.getLastName();
        DFAObj.User_Profile__c = sProfileName;
        DFAObj.Case_Number__c = sCaseNum;
        
        insert DFAObj;
     }
    }
    catch (DMLException e)
        {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Please contact the administrator'));
            return null;
        } 
        finally
        {
        	userprofile = null;
        	att = null;
        	Caselist = null;
        }
     return null;
    }
  }