src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Note__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Notes</relationshipLabel>
        <relationshipName>Case_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Referral__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Referral</label>
        <referenceTo>Referral__c</referenceTo>
        <relationshipLabel>Case Notes</relationshipLabel>
        <relationshipName>Case_Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Note</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Case Note Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>Details of the Individual referred in the STADD Program</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>filled out by the system (blank until a case is created)</inlineHelpText>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Referrals</relationshipLabel>
        <relationshipName>Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Referral Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CaseNotesSharingController.cls
/******************************************************************************************
** ICM STADD Project
*******************************************************************************************
** Class Name: Case Notes sharing
** Description: Sharing Case Notes records ,if the community user has access to Case or the Referral associated.
** Version: 1.0
** 
**-----------------------------------------------------------------------------------------
**Modification Log:
**----------------
**Developer                  Date          Version               Description
**-----------------------------------------------------------------------------------------
**Reju Palathingal           2/5/2014         1.0                   Created** 

********************************************************************************************/

public without sharing class CaseNotesSharingController {


public List<Case_Note__c> casrecord{get; set;}
public List<UserRecordAccess> caids{get; set;}
public List<UserRecordAccess> refids{get; set;}
public Id id{get;set;}
public Boolean rend{get; set;}
public List<Id> lstcasid;
public List<Id> lstrefid;
public string caccess;
public string racccess;

	public CaseNotesSharingController(ApexPages.StandardController controller) 
	{
		id=  ApexPages.currentPage().getParameters().get('id');	
		casrecord = [select id,Referral__c,Case__c from Case_Note__c where id =: id limit 1];
		string cid= casrecord[0].Case__c;
		string rid= casrecord[0].Referral__c;	
		system.debug(cid);
		system.debug(rid);
		string userid = Userinfo.getUserId();
		
		List<User> usr = [Select Id, Username, UserType, ProfileId  FROM User where Id =: userid];
		string usrtype = usr[0].UserType;
		
		if(usrtype == 'PowerPartner')
			
		{
		
			//String strQuery = 'SELECT RecordId, HasEditAccess FROM UserRecordAccess WHERE UserId = \''+ string.escapeSingleQuotes(userid) + '\' AND ';
			if(cid != null || cid != '')
			{
				caids = [SELECT RecordId, HasAllAccess, HasEditAccess,MaxAccessLevel FROM UserRecordAccess WHERE UserId =: userid AND RecordId =:casrecord[0].Case__c];
				//strQuery = strQuery + ' (RecordID = \'' + string.escapeSingleQuotes(casid) + '\'';				
			}
			
			if(rid != null || rid != '')
			{
				refids = [SELECT RecordId, HasAllAccess,HasEditAccess,MaxAccessLevel FROM UserRecordAccess WHERE UserId =: userid AND RecordID =:casrecord[0].Referral__c];			

			}
			system.debug(caids);
			system.debug(refids);
			//system.debug(caids.size());
			//system.debug(refids[0].MaxAccessLevel);
			//List<UserRecordAccess> listUserAccessRecord = database.query(strQuery);
			if(!caids.isempty())
			{
				 caccess = caids[0].MaxAccessLevel;
			}
			
			if(!refids.isempty())
			{
				 racccess = refids[0].MaxAccessLevel;
			}
			system.debug(caccess);
			system.debug(racccess);
		
			if((caccess == 'NONE' || caccess == null) && (racccess == null || racccess == 'NONE' ))
			//if(listUserAccessRecord.Isempty()) 
			{
				//system.debug('Entered ELSE');
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Insufficient Privileges: You do not have access to this record.'));
				rend=false;
				
			}
			else 
			{
				//system.debug('Entered if');
				rend=true;
			}	
		}
		else
		{
			rend=true;
		}
	
	}
}