src/objects/Change_Request__c.object
<CustomObject>
    <description>BME - A Change Request represents an additional segment of work that has been presented during the project in which new Requirement(s) can be associated to it.</description>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Critical</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted for approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Package</label>
        <referenceTo>Work_Package__c</referenceTo>
        <relationshipLabel>Change Requests</relationshipLabel>
        <relationshipName>Change_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Change Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>BME - A component represents a bundle of code that makes logical sense to move (from org to org) together. The component object can be associated to Work Packages, which will allow developers to see what code bundles support what functionality and can be used to identify dependencies between components and track migration. This object is only in the Full version.</description>
    <fields>
        <fullName>Work_Package__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work Package</label>
        <referenceTo>Work_Package__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CR_Components_Join__c.object
<CustomObject>
    <description>BME - Object to link Components and Change Request for migrating from one org to another</description>
    <fields>
        <fullName>Change_Request__c</fullName>
        <description>Change Request which triggered migration of the component</description>
        <label>Change Request</label>
        <referenceTo>Change_Request__c</referenceTo>
        <relationshipLabel>CR Components Join</relationshipLabel>
        <relationshipName>CR_Components_Join</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Component__c</fullName>
        <description>Component that has been migrated</description>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>CR Components Join</relationshipLabel>
        <relationshipName>CR_Components_Join</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CR Components Join</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CR Components Join</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Project__c.object
<CustomObject>
    <description>BME: A project is an proposed initiative undertaken by business and technology groups to support key business functions and value drivers</description>
    <fields>
        <fullName>Project_Status__c</fullName>
        <label>Project Status</label>
        <picklist>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Summary__c</fullName>
        <description>Summary of the overall project.</description>
        <label>Project Summary</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Release__c.object
<CustomObject>
    <description>BME - A Release represents a segment or phase of a project. Releases can happen consecutively, overlap, or happen concurrently. A Release represents the highest level object which serves as an umbrella to the other objects.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Project the release is a part of.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Releases</relationshipLabel>
        <relationshipName>Releases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Scoping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Released</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hot Fix</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Release</label>
    <nameField>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Releases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Work_Package__c.object
<CustomObject>
    <description>BME - A Work Package represents a logical grouping of work in order to assign to owners. Multiple Open Item, Requirement, Use Case, and Test Case records can be associated to each Work Package, making it a very central object by which to track project progress.</description>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Release</label>
        <referenceTo>Release__c</referenceTo>
        <relationshipLabel>Work Packages</relationshipLabel>
        <relationshipName>Work_Packages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In QA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Work Package</label>
    <nameField>
        <displayFormat>WP-{000}</displayFormat>
        <label>Work Package Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CRController_Test.cls
/* Class Name  : CRController_Test
 * Description : Test class for an Apex class CRController
 * Created By  : Silviu Frantescu
 * Created On  : 10-03-2013
*/

@isTest
private class CRController_Test{
    private static testMethod void ControllerTest() {
        Project__c proj = new Project__c(Name = 'Test Project', Project_Summary__c = 'Test', Project_Status__c = 'In Progress');
        insert proj;
        Release__c rel = new Release__c(Name = 'Test Release', Type__c = 'Major', Status__c = 'In Progress', Start_Date__c = Date.Today(), End_Date__c = Date.Today() + 1, Project__c = proj.Id);
        insert rel;
        Work_Package__c wp = new Work_Package__c(Status__c = 'In Progress', Priority__c = 'Medium', Release__c = rel.Id);
        insert wp;
        Change_Request__c cr = new Change_Request__c(Status__c = 'Submitted for approval', Summary__c = 'Test', Work_Package__c = wp.Id);
        insert cr;
        List<Component__c> compList = new List<Component__c>{new Component__c(Work_Package__c = wp.Id, Name = 'Test1'), new Component__c(Work_Package__c = wp.Id, Name = 'Test2')};
        insert compList;
        Id cmpId;
        for(Component__c cmp : compList){
            cmpId = cmp.Id;
            break;
        }
        CR_Components_Join__c crj = new CR_Components_Join__c(Change_Request__c = cr.Id, Component__c = cmpId);
        insert crj;
        Test.startTest();
        CRController pageCon = new CRController(new ApexPages.StandardController(cr));
        for(CRController.ComponentWrapper wrp :  pageCon.componentList){
            if(!wrp.created){
                wrp.selected = true;
            }
        }
        pageCon.attach();
        pageCon.addRows();
        pageCon.createCompNJoin();
        pageCon.newCompList = compList.clone();
        pageCon.createCompNJoin();
        pageCon.newCompList = null;
        pageCon.createCompNJoin();
        Test.stopTest();
        system.assertEquals(pageCon.newCompList, null);
    }
}