src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Functional__c.object
<CustomObject>
    <customHelpPage>Help_CAP_Functional_Domain_Summaries_VF</customHelpPage>
    <fields>
        <fullName>Assesor_Role__c</fullName>
        <encrypted>true</encrypted>
        <label>Profession of Assessor</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessor_First_Name__c</fullName>
        <defaultValue>$User.FirstName</defaultValue>
        <encrypted>true</encrypted>
        <label>Assessor First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessor_Last_Name__c</fullName>
        <defaultValue>$User.LastName</defaultValue>
        <encrypted>true</encrypted>
        <label>Assessor Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessor_Name__c</fullName>
        <description>The name of the person who performed the assessment</description>
        <encrypted>true</encrypted>
        <label>Assessor Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assessor_Name_formula__c</fullName>
        <formula>Assessor_First_Name__c &amp; &quot; &quot; &amp; Assessor_Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assessor Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Name__c</fullName>
        <formula>Case__r.CaseNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CAP - Functional Domain Summaries</relationshipLabel>
        <relationshipName>Functional_Domains</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cross_Reference_Domain_s__c</fullName>
        <label>Cross-Reference Domain(s)</label>
        <picklist>
            <picklistValues>
                <fullName>Physical Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Living Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Comm Participation Skills &amp; Social Incl</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Interaction &amp; Self-Determination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Styles and Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language and Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reason and Decision-Making</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioral and Emotional Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health: Diagnostic Info</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Space Only</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <formula>TEXT(YEAR(Case__r.Contact.Birthdate)) + &quot;/&quot; + TEXT(MONTH(Case__r.Contact.Birthdate)) + &quot;/&quot; + TEXT(DAY(Case__r.Contact.Birthdate))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date of Birth</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Functional_Domain_Type__c</fullName>
        <label>Functional Domain Type</label>
        <picklist>
            <picklistValues>
                <fullName>Physical Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Living Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Participation Skills and Social Inclusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Interaction and Self-Determination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Styles and Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language and Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reason and Decision-Making</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioral and Emotional Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health: Diagnostic Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Space Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Individual_Name__c</fullName>
        <formula>Case__r.Contact.FirstName + &quot; &quot; +  Case__r.Contact.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Individual Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_Functional_Domain__c</fullName>
        <label>Other Functional Domain</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <encrypted>true</encrypted>
        <label>Functional Domain Summary Text</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Functional Domain Summary</label>
    <nameField>
        <displayFormat>FD-{0000000}</displayFormat>
        <label>Functional Domain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Domain Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Functional_Domain_Update__c.object
<CustomObject>
    <customHelpPage>Help_FunctionalDomainSummary_updates_VF</customHelpPage>
    <description>Functional Domain Summary Update</description>
    <fields>
        <fullName>Functional_Domain__c</fullName>
        <description>Functional Domain</description>
        <label>Functional Domain</label>
        <referenceTo>Functional__c</referenceTo>
        <relationshipName>Functional_Domain_Updates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Update__c</fullName>
        <description>Updates</description>
        <encrypted>true</encrypted>
        <label>Update</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Functional Domain Summary Update</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Functional Domain Update Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Domain Summary Updates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FunctionalDomainReportPDF.cls
/******************************************************************************************
** ICM STADD Project
******************************************************************************************* 
 * @Class Name   : FunctionalDomainReportPDF
 * @Description  : PDF Report controller Class
 * @Created By   : Gaurav Verma
 * @Created On   : 09 Sep 2013
 * @Modification Log:  
 * -----------------------------------------------------------------------------
 * @Developer                Date                  Description 
 * -----------------------------------------------------------------------------
 * @Gaurav Verma          27 Sep 2013               Created
 * 
 * -----------------------------------------------------------------------------
 */
public with sharing class FunctionalDomainReportPDF
{
    public id csid {get;set;}
    public string fundom {get;set;}
    public List<Functional__c> FdLst1 {get;set;}
    public List<Functional__c> FdLst2 {get;set;}
    public List<Functional_Domain_Update__c> current {set; get;}
    public Map<id,List<Functional_Domain_Update__c>> mapFdUpdate {get;set;}
   
    public FunctionalDomainReportPDF()
    {
        csid = ApexPages.currentPage().getParameters().get('id');
        fundom = ApexPages.currentPage().getParameters().get('fundom');
        System.debug('####%%%%%%%%>>>>>' +csid);        
      
      FdLst1 = [select id, name,
                                             Assesor_Role__c, 
                                             Case__c, 
                                             CreatedByid,
                                             CreatedDate, // MH 26/9/13
                                             Assessor_Name_formula__c, // MH 26/9/13
                                             LastModifiedByid,
                                             //Ownerid,
                                             Date_of_Birth__c,
                                             
                                             Case__r.Contact.Birthdate,
                                             
                                             Assessor_Name__c,
                                             Assessor_First_Name__c,
                                             Assessor_Last_Name__c , 
                                             Case_Name__c,
                                             Individual_Name__c,
                                             Cross_Reference_Domain_s__c,   
                                             Functional_Domain_Type__c, 
                                             Other_Functional_Domain__c, 
                                             Summary__c ,
                                             (Select Id, Name, Update__c, createddate From Functional_Domain_Updates__r)                                      
                                             from Functional__c 
                                             where (Functional_Domain_Type__c =:fundom  AND Case__c =:csid)
                                             ];
                                             //Reshma added for enhancement of print all functionality    
        FdLst2 = [select id, name,
                                             Assesor_Role__c, 
                                             Case__c, 
                                             CreatedByid,
                                             CreatedDate, // MH 26/9/13
                                             Assessor_Name_formula__c, // MH 26/9/13
                                             LastModifiedByid,
                                             //Ownerid,
                                             Date_of_Birth__c,
                                             
                                             Case__r.Contact.Birthdate,
                                             
                                             Assessor_Name__c,
                                             Assessor_First_Name__c,
                                             Assessor_Last_Name__c , 
                                             Case_Name__c,
                                             Individual_Name__c,
                                             Cross_Reference_Domain_s__c,   
                                             Functional_Domain_Type__c, 
                                             Other_Functional_Domain__c, 
                                             Summary__c ,
                                             (Select Id, Name, Update__c, createddate From Functional_Domain_Updates__r)                                      
                                             from Functional__c 
                                             where (Case__c =:csid)
                                             ORDER BY Functional_Domain_Type__c, name
                                               ];
         
                system.debug('####%%%%%%%% query>>>' + fundom+ '##Case ID##' + csid );
                //system.debug('####FdLst1[0].Functional_Domain_Type__c%%%%%%%% query>>>' + FdLst1[0].Functional_Domain_Type__c);
                //system.debug('####%%%%%%%%  FdLst1.size>>>' + FdLst1.size());
        if(FdLst1.size()>0) 
        {
            mapFdUpdate = new    Map<id,List<Functional_Domain_Update__c>>(); 
            for(Functional__c F: FdLst1)
            {
                list <Functional_Domain_Update__c> current = new list <Functional_Domain_Update__c>();
                current = F.Functional_Domain_Updates__r;
                mapFdUpdate.put (F.id,current) ; 

            }
        }
        
       else if(FdLst2.size()>0) 
        {    
           
            mapFdUpdate = new  Map<id,List<Functional_Domain_Update__c>>(); 
            for(Functional__c F: FdLst2)
            {
                
                list <Functional_Domain_Update__c> current = new list <Functional_Domain_Update__c>();
                current = F.Functional_Domain_Updates__r;
                mapFdUpdate.put (F.id,current) ; 

            }
        }
        else
        {
            ApexPages.addMessage ( new ApexPages.Message(ApexPages.Severity.ERROR, 'No Functional Domain with this Type available in the system'));
            //Return Null;
        }                                        
       
    }
   }
  
    /*public pagereference printplan(){
        
        PageReference refPage = new PageReference('/apex/FuncDomainPrintPreview?id='+ csid) ;                
        refPage.setRedirect(true);       
        
    return refPage;
    }
    }*/