src/objects/Functional__c.object
<CustomObject>
    <customHelpPage>Help_CAP_Functional_Domain_Summaries_VF</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CAP - Functional Domain Summaries</relationshipLabel>
        <relationshipName>Functional_Domains</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Functional_Domain_Type_For_Print__c</fullName>
        <description>Created this to use in the drop down list.</description>
        <label>Functional Domain Type</label>
        <picklist>
            <picklistValues>
                <fullName>All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physical Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Living Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Participation Skills and Social Inclusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Interaction and Self-Determination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Styles and Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language and Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reason and Decision-Making</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioral and Emotional Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health: Diagnostic Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Space Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Functional_Domain_Type__c</fullName>
        <label>Functional Domain Type</label>
        <picklist>
            <picklistValues>
                <fullName>Physical Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Living Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Participation Skills and Social Inclusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Interaction and Self-Determination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Styles and Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language and Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reason and Decision-Making</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioral and Emotional Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health: Diagnostic Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Space Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Functional Domain Summary</label>
    <nameField>
        <displayFormat>FD-{0000000}</displayFormat>
        <label>Functional Domain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Domain Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FunctionalDomainTypeEntension_Test.cls
/* Class Name  : FunctionalDomainTypeEntension_Test
 * Description : Test class for an Apex class CaseControllerExtension 
 * Created By  : Silviu Frantescu
 * Created On  : 09-30-2013
*/

@isTest
private class FunctionalDomainTypeEntension_Test{
    private static case cas;
    private static testmethod void testData(){
        cas = new case ();
        cas.status = 'New';
        cas.Origin = 'Phone';
        insert cas;        
    }    
    private static testmethod void CaseControllerTest(){        
        test.startTest();
        testData();
        ApexPages.StandardController sc = new ApexPages.StandardController(cas); 
        FunctionalDomainTypeExtension obj = new FunctionalDomainTypeExtension(sc);
        obj.Next();   
        test.stopTest();
        system.assertEquals(obj.FdLst1, null);
    }    
    private static testmethod void CaseControllerFuncObjTest(){        
        test.startTest();
        testData();
        ApexPages.StandardController sc = new ApexPages.StandardController(cas); 
        FunctionalDomainTypeExtension obj = new FunctionalDomainTypeExtension(sc);
        Functional__c funcObj = new Functional__c(Case__c= cas.id);
        insert funcObj;
       
        obj.Next();
        test.stopTest();
        system.assertNotEquals(funcObj, null);
    }
    private static testmethod void CaseControllerFuncObjTest1(){        
        test.startTest();
        testData();
        ApexPages.StandardController sc = new ApexPages.StandardController(cas); 
        FunctionalDomainTypeExtension obj = new FunctionalDomainTypeExtension(sc);
        Functional__c funcObj = new Functional__c(Case__c= cas.id);
		funcObj.Functional_Domain_Type__c = 'Physical Functioning';
        funcObj.Functional_Domain_Type_For_Print__c = 'All';
        insert funcObj;
       
        obj.Next();
        test.stopTest();
        system.assertNotEquals(funcObj, null);
    }
}