src/objects/Functional__c.object
<CustomObject>
    <customHelpPage>Help_CAP_Functional_Domain_Summaries_VF</customHelpPage>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CAP - Functional Domain Summaries</relationshipLabel>
        <relationshipName>Functional_Domains</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Functional_Domain_Type__c</fullName>
        <label>Functional Domain Type</label>
        <picklist>
            <picklistValues>
                <fullName>Physical Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Living Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Participation Skills and Social Inclusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Interaction and Self-Determination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Styles and Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language and Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reason and Decision-Making</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioral and Emotional Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health: Diagnostic Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Space Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Functional Domain Summary</label>
    <nameField>
        <displayFormat>FD-{0000000}</displayFormat>
        <label>Functional Domain Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Functional Domain Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FunctionalDomainReportPDF_Test.cls
/* Class Name  : FunctionalDomainReportPDF_Test
 * Description : Test class for an Apex class FunctionalDomainReportPDF
 * Created By  : Silviu Frantescu
 * Created On  : 09-30-2013
*/

@isTest
private class FunctionalDomainReportPDF_Test{
    private static testmethod void constructorExceptionTest(){
        test.starttest();
        FunctionalDomainReportPDF obj = new FunctionalDomainReportPDF();
        test.stoptest();
        system.assertEquals(obj.FdLst1.size(), 0);
    }
    private static testmethod void constructorInsertionTest(){       
        Case cas = new case ();
        cas.status = 'New';
        cas.Origin = 'Phone';
        test.starttest();
        insert cas; 
        Functional__c funRec = new Functional__c(Case__c=cas.id);
        insert funRec;
        ApexPages.currentPage().getParameters().put('id', cas.id);
        FunctionalDomainReportPDF obj = new FunctionalDomainReportPDF();
        test.stoptest();
        system.assertEquals(obj.FdLst1.size(), 1);
        
    }
     private static testmethod void constructorInsertionTest2(){       
        Case cas = new case ();
        cas.status = 'New';
        cas.Origin = 'Phone';
        test.starttest();
        insert cas; 
        Functional__c funRec = new Functional__c(Case__c=cas.id);
        funRec.Functional_Domain_Type__c ='Physical Functioning';
        insert funRec;
        ApexPages.currentPage().getParameters().put('id', cas.id);
        FunctionalDomainReportPDF obj = new FunctionalDomainReportPDF();
        obj.fundom = 'A';
        test.stoptest();
        system.assertEquals(obj.FdLst2.size(), 1);
        
    }
}