src/objects/Login_Page_Messages__c.object
<CustomObject>
    <description>Creating a page in the application where program admins can edit the messages displayed in the Login page</description>
    <fields>
        <fullName>Display_Announcements__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check to display System Announcements section on the login Page</inlineHelpText>
        <label>Display Message</label>
        <type>Checkbox</type>
    </fields>
    <label>Login Page Messages</label>
    <nameField>
        <displayFormat>MSG-{000}</displayFormat>
        <label>Msg Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Login Page Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CommunitiesLoginControllerTest.cls
/**
 * An apex page controller that exposes the site login functionality
 */
@IsTest global with sharing class CommunitiesLoginControllerTest {
    @IsTest(SeeAllData=true) 
    global static void testCommunitiesLoginController () {
        Login_Page_Messages__c lpm = new Login_Page_Messages__c();
            lpm.Display_Announcements__c=False;
        CommunitiesLoginController controller = new CommunitiesLoginController ();
       System.assertEquals(controller.dispAnnouncements,True);
        controller.forwardToAuthPage();
    }    
}