src/objects/Mapping_object__c.object
<CustomObject>
    <fields>
        <fullName>Context_prompt__c</fullName>
        <label>Context prompt</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Functional_Domain_Type__c</fullName>
        <label>Functional Domain Type</label>
        <picklist>
            <picklistValues>
                <fullName>Physical Functioning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Living Skills</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Participation Skills and Social Inclusion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Interaction and Self-Determination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Learning Styles and Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language and Communication</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reason and Decision-Making</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Behavioral and Emotional Health</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mental Health: Diagnostic Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Space Only</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReferralPage1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReferralPage2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ReferralPage3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FunctionalDomainPage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PortalUserRegistration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Mapping object</label>
    <nameField>
        <displayFormat>Map-{0000}</displayFormat>
        <label>Mapping object Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mapping objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/System_Access_Request__c.object
<CustomObject>
    <fields>
        <fullName>BCeIDorIDIR_DisplayName__c</fullName>
        <encrypted>true</encrypted>
        <inlineHelpText>Field displays as &quot;Surname&quot; then &quot;Given/First Name&quot;</inlineHelpText>
        <label>BCeID / IDIR Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BCeIDorIDIR_Email__c</fullName>
        <encrypted>true</encrypted>
        <label>BCeID / IDIR Email</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BCeIDorIDIR_UserName__c</fullName>
        <encrypted>true</encrypted>
        <label>BCeID / IDIR</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_to_Individual_if_Other__c</fullName>
        <label>Relationship to Individual (if Other)</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SiteMinder_GUID__c</fullName>
        <label>SiteMinder GUID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Credentials_OR_Role_Profession__c</fullName>
        <description>Be very careful when changing values of this picklist as the code is trying to match exactly with the case team role (i.e. compares the exact text of the string)</description>
        <inlineHelpText>will dictate the case team role once user created and added to case team</inlineHelpText>
        <label>User Credentials OR Role/Profession</label>
        <picklist>
            <picklistValues>
                <fullName>Committee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CLBC Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DAA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foster Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Friend</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MCFD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Network</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nurse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Physician</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resource Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self-Advocate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Social Worker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Therapist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>System Access Request</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>System Access Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Access Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CommunitiesSelfRegController.cls
/**
 * An apex page controller that supports self registration of users in communities that allow self registration
 */
public with sharing class CommunitiesSelfRegController {

    public System_Access_Request__c request {get; set;}
    public Mapping_object__c mapobj{get; set;}
    
    public CommunitiesSelfRegController() {
        request = new System_Access_Request__c();
        
        mapobj = [select id,Functional_Domain_Type__c,Context_prompt__c from Mapping_object__c where Functional_Domain_Type__c = 'PortalUserRegistration'
                                    LIMIT 1];
    }
    
    public PageReference submitRequest() {
        request.SiteMinder_GUID__c = ApexPages.currentPage().getParameters().get('guid');
        request.BCeIDorIDIR_DisplayName__c = ApexPages.currentPage().getParameters().get('dname');
        request.BCeIDorIDIR_Email__c = ApexPages.currentPage().getParameters().get('email');
        request.BCeIDorIDIR_UserName__c = ApexPages.currentPage().getParameters().get('uname');
        string role = request.User_Credentials_OR_Role_Profession__c;       
        string other= request.Relationship_to_Individual_if_Other__c;
        if(role == 'Other' && (other == '' || other== null))
        {
        	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Please specify the other relationship'));
        	return null;
        }else
        {
	        insert request;       
	        if (request.Id != null) {
	            PageReference page = System.Page.CommunitiesSelfRegConfirm;
	            page.setRedirect(true);
	            return page;
	        }
	        return null;
	     }
    }
}