src/objects/Plan__c.object
<CustomObject>
    <description>A plan developed by the individual to meet certain goals.</description>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Status__c</fullName>
        <label>Plan Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Place/ Signed-off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Current</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Support Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contingency Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crisis Plan</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plan</label>
    <nameField>
        <encrypted>true</encrypted>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PlanCountTrigger_Test.cls
/* Class Name  : PlanCountTrigger_Test
 * Description : Test class for an Apex trigger PlanCountTrigger
 * Created By  : Silviu Frantescu
 * Created On  : 10-18-2013
*/

@isTest
private class PlanCountTrigger_Test{
    static case cas;
    static plan__c plan;
    private static testmethod void testData(){
        cas = new case ();
        cas.status = 'New';
        cas.Origin = 'Phone';        
        insert cas;
        plan = new plan__c();
        plan.name = 'test plan';
        plan.Case__c = cas.id;
        plan.Plan_Status__c ='Active Plan';
        plan.Plan_Type__c = 'Crisis Plan';
        insert plan;
    }
    private static testmethod void testCountMethod(){
        Test.startTest();
        testData();
        plan.Plan_Type__c = 'Normal Plan';
        update plan;
        Test.stopTest();     
        system.assertEquals(plan.Plan_Status__c, 'Active Plan');   
    }
}