src/objects/Postal_Code__c.object
<CustomObject>
    <description>Postal Code mappings to be used when assigning a &apos;community&apos; value to a referral.</description>
    <fields>
        <fullName>Community__c</fullName>
        <description>The community in BC assigned to this postal code.</description>
        <encrypted>true</encrypted>
        <label>Community</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Six_Digits__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The postal code is 6 digits.</description>
        <label>Six Digits?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Three_Digits__c</fullName>
        <defaultValue>false</defaultValue>
        <description>The postal code is three digits.</description>
        <label>Three Digits?</label>
        <type>Checkbox</type>
    </fields>
    <label>Postal Code</label>
    <nameField>
        <label>Postal Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Postal Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Referral__c.object
<CustomObject>
    <description>Details of the Individual referred in the STADD Program</description>
    <fields>
        <fullName>Community__c</fullName>
        <description>Auto-populated</description>
        <encrypted>true</encrypted>
        <label>Community</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Referral Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UpdatePCCommunity.cls
/* Class: UpdatePCCommunity
 * Developer: Subodh Bahl
 * Description: This class updates the community once the update community button is clicked
 * Modification Logs:
 * Modified By                            Modified Date                      Comments                         
 * Subodh Bahl                            23/01/2015                         Created.
 */

global class UpdatePCCommunity{

    /* Developer : Subodh bahl 
     * Description : This method finds a match for the postal code in the Postal Code Object and calls the update method accordingly
     */
    /*
    webservice static void CheckCommunityCode(String strPostalCode,String id){ 
       
        system.debug('pdcode'+strPostalCode+';..Id :'+id);
        
        // Variables
        List <Postal_Code__c> listPostalCode = new List <Postal_Code__c>();
        String postalCode;
        String communityName;
        Boolean matchFound = false;
        try{
          /*  listPostalCode = [select id,Community__c, Name from Postal_Code__c];
            
            String str3Digit = strPostalCode.left(3);
            system.debug('pststr3Digit...:'+str3Digit);
            
            for(integer i = 0; i < listPostalCode.size(); i++ ){
                postalCode      = listPostalCode[i].Name; 
                if(postalCode == strPostalCode){
                    matchFound = true; 
                    communityName   = listPostalCode[i].Community__c;
                    system.debug('6digit....:'+communityName);
                }
                system.debug('matchFound...:'+matchFound);
               if(postalCode == str3Digit && matchFound != true)
               {
               	 	matchFound = true; 
                    communityName   = listPostalCode[i].Community__c;
                    system.debug('3digit...:'+communityName);
               	
               }
            }
           
            String str3Digit = strPostalCode.left(3);
            system.debug('pststr3Digit...:'+str3Digit);
			List<Postal_Code__c> lstPCobj = [select id,Community__c,Six_Digits__c,Three_Digits__c from Postal_Code__c where Name=: strPostalCode OR Name =: str3Digit order by Name DESC];
				if(!lstPCobj.IsEmpty() && lstPCobj.size()>0)
					{
						system.debug('----Postal Code--------'+lstPCobj[0].Community__c);
						matchFound = true;
						communityName = lstPCobj[0].Community__c;
					}
					            
            if(matchFound == true)
             updateCommunityName(Id, communityName);
            else
             updateCommunityName(Id, 'Unknown');
             
         system.debug(matchFound);   
        }
        catch(Exception ex){
            System.debug('Exception' + ex);
        }
    }   



    /* Developer : Subodh Bahl
     * Description : This method updates a record based on the community name
     */
    /*
    public static void updateCommunityName(String id, String communityName){
        system.debug('JG');
        Referral__c referral    = new Referral__c(Id = id);
        referral.Community__c   = communityName;
        system.debug(referral);
        update referral; 
    } */
}