src/objects/Referral__c.object
<CustomObject>
    <description>Details of the Individual referred in the STADD Program</description>
    <fields>
        <fullName>Community__c</fullName>
        <description>Auto-populated</description>
        <encrypted>true</encrypted>
        <label>Community</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Foundry_BC_Referral__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Individual/youth was directly referred through a Foundry service hub location.</inlineHelpText>
        <label>Foundry BC Referral</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Has_legal_authority__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the individual is the first person to contact regarding the case, this indicator is checked and the primary contact information below is not completed</description>
        <inlineHelpText>&quot;Representative, Guardian, or Committee&quot;</inlineHelpText>
        <label>Has legal authority</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_the_Individual_Attending_School_Indic__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>check the box to enter and save contact information for this organization</inlineHelpText>
        <label>Is the Individual Attending School ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_the_Individual_eligible_for_CLBC_Serv__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check the box to enter and save contact information for this organization</inlineHelpText>
        <label>Is the Individual eligible for CLBC Serv</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_the_individual_being_supported_by_CFD__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check the box to enter and save contact information for this organization</inlineHelpText>
        <label>Is the individual supported by CFD CYSN</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Mailing_Address_same_as_Physical_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>if not checked, need to enter the mailing address</inlineHelpText>
        <label>Mailing Address same as Physical Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Physical_Address_Postal_Code__c</fullName>
        <encrypted>true</encrypted>
        <label>Physical Address Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_Is_Individual_Indicator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Cannot be used if the Rep/ Guardian/Committee indicator  is used</description>
        <inlineHelpText>Cannot be checked if Individual has a legal authority</inlineHelpText>
        <label>Individual is Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Receiving_Services_on_Reserve__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Receiving CLBC Services on Reserve</label>
        <type>Checkbox</type>
    </fields>
    <label>Referral</label>
    <nameField>
        <displayFormat>REF-{000000}</displayFormat>
        <label>Referral Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/UpdateCommunityReferralObject_Test.cls
/******************************************************************************************
** ICM STADD Project
*******************************************************************************************
** Class Name: UpdateCommunityReferralObject_Test
** Description: To test the invocable method on UpdateCommunityReferralObject
** Version: 1.0
** 
**-----------------------------------------------------------------------------------------
**Modification Log:
**----------------
**Developer                  Date          Version               Description
**-----------------------------------------------------------------------------------------
**Sanjoy                     11/11/2018                          Created
********************************************************************************************/
@isTest
private class UpdateCommunityReferralObject_Test{
  @testSetup
  static void setupTestData(){
    test.startTest();
    Referral__c referral_Obj = new Referral__c(Has_legal_authority__c = false, Is_the_Individual_Attending_School_Indic__c = false, Is_the_Individual_eligible_for_CLBC_Serv__c = false, Is_the_individual_being_supported_by_CFD__c = false, Mailing_Address_same_as_Physical_Address__c = true, Physical_Address_Postal_Code__c = 'V1V1V1', Primary_Contact_Is_Individual_Indicator__c = false, Receiving_Services_on_Reserve__c = false, Foundry_BC_Referral__c = false);
    Insert referral_Obj; 
    test.stopTest();
  }
  static testMethod void test_updateCommunityReferral_UseCase1(){
    List<Referral__c> referral_Obj  =  [SELECT Id,Physical_Address_Postal_Code__c,Community__c from Referral__c];
    System.assertEquals(true,referral_Obj.size()>0);
    UpdateCommunityReferralObject obj01 = new UpdateCommunityReferralObject();
    UpdateCommunityReferralObject.updateCommunityReferral(new List<Id>());
    System.assertEquals(referral_Obj[0].Community__c,'Unknown');
  }
}