src/objects/Test_Case__c.object
<CustomObject>
    <description>BME - A Test Case represents a repeatable business scenario which will allow application functionality to be tested. Test Cases are associated to Use Cases, as they should reflect a business scenario.</description>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Test Case ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case_Result__c.object
<CustomObject>
    <description>BME - A Test Case Result represents the result of a specific Test Case Step.</description>
    <fields>
        <fullName>Test_Case_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Case Step</label>
        <referenceTo>Test_Case_Step__c</referenceTo>
        <relationshipLabel>Test Case Results</relationshipLabel>
        <relationshipName>Test_Case_Results</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Case Result</label>
    <nameField>
        <displayFormat>TestResult-{000}</displayFormat>
        <label>Test Case Result ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Case Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Test_Case_Step__c.object
<CustomObject>
    <description>BME - A Test Case Step is the incremental actions that, when joined in sequence, make up a Test Case.</description>
    <fields>
        <fullName>Test_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Case</label>
        <referenceTo>Test_Case__c</referenceTo>
        <relationshipLabel>Test Case Steps</relationshipLabel>
        <relationshipName>Test_Case_Steps_old</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Case Step</label>
    <nameField>
        <displayFormat>TCS-{0000}</displayFormat>
        <label>Test Case Step ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Case Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AddTestCaseStepResultsController_Test.cls
/* Class Name  : AddTestCaseStepResultsController_Test
 * Description : Test class for an Apex class AddTestCaseStepResultsController
 * Created By  : Silviu Frantescu
 * Created On  : 10-03-2013
*/

@isTest
private class AddTestCaseStepResultsController_Test{
    static Test_Case__c testCase;
    static Test_Case_Step__c testCaseStep;
    static list<Test_Case_Step__c> testCaseStepList;
    static Test_Case_Result__c tsResult;
    static list<Test_Case_Result__c> tsResultList;
    
    private static testmethod void testdata(){
        testCase = new Test_Case__c();
        insert testCase;         
        testCaseStep= new Test_Case_Step__c(Test_Case__c=testCase.Id);
        insert testCaseStep;         
        testCaseStepList = new list<Test_Case_Step__c>();
        testCaseStepList.add(TestCaseStep);
        tsResult = new Test_Case_Result__c(Test_Case_Step__c=testCaseStep.Id);
        insert tsResult;         
        tsResultList = new list<Test_Case_Result__c>();
        tsResultList.add(tsResult);
    }

    private static testmethod void testCaseControllerTest(){          
        test.startTest();
        testdata();
        ApexPages.currentPage().getParameters().put('id',testCase.Id);         
        AddTestCaseStepResultsController Obj = new AddTestCaseStepResultsController();
        Obj.SelecteResultRecord = tsResult.id; 
        Obj.editRecord();
        Obj.editResult();
        Obj.Cancel_Click();
        Obj.addNewResult();
        Obj.getTestCaseStepResults();
        Obj.AddTestCaseStepResult();
        Obj.CancelTestCaseStepResult();
        Obj.getTestResult();
        Obj.getTestCaseSteps();
        Obj.setTestCaseSteps(testCaseStepList);
        Obj.settestcaseresultobj(tsResult);
        Obj.gettestcase();
        Obj.DeleteResult();
        Obj.getUserInfo();
        Obj.settestcase(testCase);
        Obj.setTestCaseResults(tsResultList );
        Obj.gettestcaseresultobj();
        Obj.SelecteResultRecord = null;
        Obj.DeleteResult();
        test.stopTest();
        system.assertEquals(Obj.SelecteResultRecord, null);
    }
     private static testmethod void testCaseControllerExceptionTest(){          
        test.startTest();
        testdata();
        ApexPages.currentPage().getParameters().put('id',testCase.Id);         
        AddTestCaseStepResultsController Obj = new AddTestCaseStepResultsController();
        Obj.tsResult= new Test_Case_Result__c(); 
        Obj.editResult();
        system.assertNotEquals(Obj.tsResult, null);
    }
    
    
}